// commands/cmds_10.js
// ❤️ SOCIALHUB — iKON-BOT
module.exports=({api,event,user,reply,users,profile,fun})=>{
const r=t=>api.sendMessage(t,event.threadID,()=>{},event.messageID);
user.social=user.social||{rep:0,likes:0,followers:[],following:[],friends:[],posts:[],streak:0};
user.social.followers=user.social.followers||[];user.social.following=user.social.following||[];user.social.friends=user.social.friends||[];user.social.posts=user.social.posts||[];
const find=uid=>users.get(String(uid||""));
const name=u=>u?.name||u?.firstName||u?.uid||"Unknown";
const cmds=[
{name:"me",aliases:["profileme","aboutme"],run:async()=>r(`👤 ${name(user)}\n⭐ Level: ${user.level||1}\n💰 Wallet: $${(user.wallet||0).toLocaleString()}\n❤️ HP: ${user.health||100}/${user.maxHealth||100}\n⭐ Rep: ${user.social.rep}\n👥 Followers: ${user.social.followers.length}\n🤝 Friends: ${user.social.friends.length}`)},
{name:"social",aliases:["socialhub"],run:async()=>r("❤️ SOCIALHUB\n!me !bio !status !rep !friends !follow <uid>\n!unfollow <uid> !addfriend <uid> !removefriend <uid>\n!post <text> !posts !like <uid> !leaderboard\n!compliment <uid> !roast <uid> !ship <uid> <uid>")},
{name:"bio",aliases:["about"],run:async({args})=>{if(!args.length)return r(`📝 BIO\n${user.bio||"No bio set. Use !bio <text>."}`);user.bio=args.join(" ").slice(0,200);r("📝 Bio updated successfully.")}},
{name:"status",aliases:["mood"],run:async({args})=>{if(!args.length)return r(`💭 STATUS: ${user.status||"Available 🟢"}`);user.status=args.join(" ").slice(0,150);r("💭 Status updated.")}},
{name:"rep",aliases:["reputation"],run:async()=>r(`⭐ ${name(user)} has ${user.social.rep} reputation.`)},
{name:"friends",aliases:["friendlist"],run:async()=>r("🤝 FRIENDS\n"+(user.social.friends.length?user.social.friends.map(x=>`• ${name(find(x))}`).join("\n"):"No friends yet."))},
{name:"follow",aliases:["subscribe"],run:async({args})=>{let u=find(args[0]);if(!u)return r("❌ User not found.");if(u.uid===user.uid)return r("😂 You cannot follow yourself.");if(!user.social.following.includes(u.uid))user.social.following.push(u.uid);u.social=u.social||{rep:0,likes:0,followers:[],following:[],friends:[],posts:[],streak:0};u.social.followers=u.social.followers||[];if(!u.social.followers.includes(user.uid))u.social.followers.push(user.uid);r(`❤️ You followed ${name(u)}.`)}},
{name:"unfollow",aliases:["unsubscribe"],run:async({args})=>{let uid=String(args[0]||"");user.social.following=user.social.following.filter(x=>x!==uid);let u=find(uid);if(u?.social?.followers)u.social.followers=u.social.followers.filter(x=>x!==user.uid);r("💔 Follow removed.")}},
{name:"followers",aliases:["fans"],run:async()=>r(`👥 FOLLOWERS: ${user.social.followers.length}\n${user.social.followers.slice(0,20).map(x=>`• ${name(find(x))}`).join("\n")||"Nobody yet."}`)},
{name:"following",aliases:["followinglist"],run:async()=>r(`❤️ FOLLOWING: ${user.social.following.length}\n${user.social.following.slice(0,20).map(x=>`• ${name(find(x))}`).join("\n")||"Nobody yet."}`)},
{name:"addfriend",aliases:["friend"],run:async({args})=>{let u=find(args[0]);if(!u)return r("❌ User not found.");if(u.uid===user.uid)return r("😂 That's you.");if(!user.social.friends.includes(u.uid))user.social.friends.push(u.uid);u.social=u.social||{friends:[]};u.social.friends=u.social.friends||[];if(!u.social.friends.includes(user.uid))u.social.friends.push(user.uid);user.social.rep+=2;r(`🤝 ${name(u)} added as a friend.\n⭐ Rep +2`)}},
{name:"removefriend",aliases:["unfriend"],run:async({args})=>{let uid=String(args[0]||"");user.social.friends=user.social.friends.filter(x=>x!==uid);let u=find(uid);if(u?.social?.friends)u.social.friends=u.social.friends.filter(x=>x!==user.uid);r("💔 Friendship removed.")}},
{name:"post",aliases:["statuspost"],run:async({args})=>{let text=args.join(" ").slice(0,300);if(!text)return r("📝 Write something: !post <text>");user.social.posts.unshift({text,time:Date.now(),likes:0,author:user.uid});user.social.posts=user.social.posts.slice(0,20);r(`📢 POSTED\n“${text}”\n❤️ 0 likes`)}},
{name:"posts",aliases:["feed"],run:async()=>{let arr=[];for(const u of users.values())for(const p of (u.social?.posts||[]).slice(0,3))arr.push({u,p});arr.sort((a,b)=>b.p.time-a.p.time);r("📰 SOCIAL FEED\n"+(arr.slice(0,10).map(x=>`👤 ${name(x.u)}\n${x.p.text}\n❤️ ${x.p.likes||0}\n`).join("\n")||"No posts yet."))}},
{name:"like",aliases:["love"],run:async({args})=>{let u=find(args[0]);if(!u)return r("❌ User not found.");let p=u.social?.posts?.[0];if(!p)return r("❌ No post found.");p.likes=(p.likes||0)+1;u.social.likes=(u.social.likes||0)+1;user.social.rep++;r(`❤️ You liked ${name(u)}'s latest post.\n⭐ Rep +1`)}},
{name:"likes",aliases:["likestats"],run:async()=>r(`❤️ Total Likes: ${user.social.likes||0}`)},
{name:"compliment",aliases:["praise"],run:async({args})=>{let u=find(args[0]);if(!u)return r("❌ User not found.");let x=["🔥 You are seriously awesome!","👑 Absolute legend!","💎 You're built different!","🚀 Keep shining!","❤️ Your energy is unmatched!"];r(`💌 ${name(u)}: ${x[Math.floor(Math.random()*x.length)]}`);u.social=u.social||{rep:0};u.social.rep=(u.social.rep||0)+3}},
{name:"roast",aliases:["burn"],run:async({args})=>{let u=find(args[0]);if(!u)return r("❌ User not found.");let x=["😂 Bro needs a software update.","💀 Even Google can't find your logic.","🤣 Your Wi-Fi has more connection than you.","😭 You came with confidence and forgot the skills.","💀 The loading bar gave up on you."];r(`🔥 ${name(u)}: ${x[Math.floor(Math.random()*x.length)]}`)}},
{name:"ship",aliases:["couple"],run:async({args})=>{let a=find(args[0]),b=find(args[1]);if(!a||!b)return r("❤️ Use !ship <uid1> <uid2>");let p=Math.floor(Math.random()*101);r(`❤️ SHIP CHECK\n👤 ${name(a)} + 👤 ${name(b)}\n💘 Compatibility: ${p}%\n${p>75?"🔥 Powerful connection!":p>45?"💕 Interesting match!":"😂 Friendship might be safer."}`)}},
{name:"match",aliases:["compatibility"],run:async({args})=>{let u=find(args[0]);if(!u)return r("❌ User not found.");let p=Math.floor(Math.random()*101);r(`💘 MATCH WITH ${name(u)}\n❤️ ${p}% compatibility`) }},
{name:"rate",aliases:["rating"],run:async({args})=>{let u=find(args[0]);if(!u)return r("❌ User not found.");let p=Math.floor(Math.random()*6)+5;r(`⭐ ${name(u)} rating: ${p}/10`) }},
{name:"truth",aliases:["truthgame"],run:async()=>{let x=["What is your biggest goal?","Who inspires you most?","What is one thing you want to change?","What is your funniest memory?","What would you do with $1M?"];r("🎭 TRUTH\n"+x[Math.floor(Math.random()*x.length)])}},
{name:"dare",aliases:["daregame"],run:async()=>{let x=["Send a funny sticker 😂","Change your status for 10 minutes.","Compliment someone in the group.","Tell everyone a funny story.","Use only emojis for your next message."];r("🎭 DARE\n"+x[Math.floor(Math.random()*x.length)])}},
{name:"8ball",aliases:["askball"],run:async()=>{let x=["🎱 Definitely!","🎱 Probably.","🎱 Ask again later.","🎱 Not looking good.","🎱 Absolutely not.","🎱 The universe says yes!"];r(x[Math.floor(Math.random()*x.length)])}},
{name:"dicegame",aliases:["socialdice"],run:async()=>r(`🎲 You rolled ${Math.floor(Math.random()*6)+1}!`)},
{name:"compliments",aliases:["kindness"],run:async()=>r("❤️ KINDNESS BOOST\nGive someone a compliment today.\n✨ Positive energy increases community reputation.")},
{name:"leaderboard",aliases:["sociallb"],run:async()=>{let a=[...users.values()].sort((x,y)=>(y.social?.rep||0)-(x.social?.rep||0)).slice(0,10);r("❤️ SOCIAL LEADERBOARD\n"+a.map((u,i)=>`${i+1}. ${name(u)} — ⭐${u.social?.rep||0}`).join("\n"))}},
{name:"friendrank",aliases:["friendlb"],run:async()=>{let a=[...users.values()].sort((x,y)=>(y.social?.friends?.length||0)-(x.social?.friends?.length||0)).slice(0,10);r("🤝 FRIEND RANK\n"+a.map((u,i)=>`${i+1}. ${name(u)} — 👥${u.social?.friends?.length||0}`).join("\n"))}},
{name:"followrank",aliases:["followlb"],run:async()=>{let a=[...users.values()].sort((x,y)=>(y.social?.followers?.length||0)-(x.social?.followers?.length||0)).slice(0,10);r("❤️ FOLLOWER RANK\n"+a.map((u,i)=>`${i+1}. ${name(u)} — 👥${u.social?.followers?.length||0}`).join("\n"))}},
{name:"postrank",aliases:["postlb"],run:async()=>{let a=[...users.values()].sort((x,y)=>(y.social?.posts?.length||0)-(x.social?.posts?.length||0)).slice(0,10);r("📢 POST RANK\n"+a.map((u,i)=>`${i+1}. ${name(u)} — 📝${u.social?.posts?.length||0}`).join("\n"))}},
{name:"sociallevel",aliases:["socialxp"],run:async()=>{let lv=Math.max(1,Math.floor(user.social.rep/50)+1);r(`❤️ Social Level: ${lv}\n⭐ Rep: ${user.social.rep}`)}},
{name:"socialquest",aliases:["socialmission"],run:async()=>{user.social.rep+=5;r("❤️ SOCIAL QUEST COMPLETE!\n⭐ Rep +5\n🤝 Keep interacting with the community.")}},
{name:"dailychat",aliases:["chatbonus"],run:async()=>{let now=Date.now(),last=user.social.lastDaily||0;if(now-last<86400000)return r("⏳ You already claimed today's social bonus.");user.social.lastDaily=now;user.social.rep+=10;user.wallet=(user.wallet||0)+5000;r("❤️ DAILY SOCIAL BONUS\n⭐ Rep +10\n💰 +$5,000")}},
{name:"socialstats",aliases:["socialinfo"],run:async()=>r(`❤️ SOCIAL STATS\n⭐ Rep: ${user.social.rep}\n❤️ Likes: ${user.social.likes}\n👥 Followers: ${user.social.followers.length}\n❤️ Following: ${user.social.following.length}\n🤝 Friends: ${user.social.friends.length}\n📝 Posts: ${user.social.posts.length}`)},
{name:"socialsearch",aliases:["finduser"],run:async({args})=>{let q=args.join(" ").toLowerCase();let a=[...users.values()].filter(u=>(u.name||"").toLowerCase().includes(q)||String(u.uid).includes(q)).slice(0,10);r("🔎 USER SEARCH\n"+(a.map(u=>`• ${name(u)} — ${u.uid}`).join("\n")||"No users found."))}},
{name:"socialreset",aliases:["resetsocial"],run:async()=>{user.social={rep:0,likes:0,followers:[],following:[],friends:[],posts:[],streak:0};r("🔄 Social profile reset.")}},
{name:"socialhelp",aliases:["helpme"],run:async()=>r("❤️ SOCIALHUB\n!me !bio !status !friends !followers !following\n!follow <uid> !unfollow <uid> !addfriend <uid>\n!post <text> !posts !like <uid>\n!compliment <uid> !roast <uid> !ship <uid> <uid>\n!leaderboard !socialstats !socialsearch <name>")}
];
return cmds;
};
