const R=globalThis.__KLERK_BOT__||(globalThis.__KLERK_BOT__={}),P=R.players||(R.players=new Map()),C={};
const U=id=>{id=String(id||"");let u=P.get(id);if(!u)u={id,cash:100000,bank:0,vault:0,savings:0,coins:100,tokens:0,xp:0,level:1,inventory:{},wanted:0,jail:0,respect:0,crew:null,cars:[],garage:3,fuel:100,missionsDone:0,gtaMissions:{},turf:0,cooldowns:{}};u.cash??=100000;u.bank??=0;u.vault??=0;u.savings??=0;u.inventory??={};u.cars??=[];u.wanted??=0;u.jail??=0;u.respect??=0;u.gtaMissions??={};u.cooldowns??={};P.set(id,u);return u};
const N=x=>String(x||"").toLowerCase().trim(),num=x=>Math.max(0,Number(String(x||"").replace(/[$,]/g,""))||0),money=n=>`$${Math.floor(n||0).toLocaleString()}`,BAR=(v,m=100,n=10)=>{let a=Math.round(Math.max(0,Math.min(m,v))/m*n);return"█".repeat(a)+"░".repeat(n-a)},D=(u,k,n=1)=>u.inventory[k]=(u.inventory[k]||0)+n;
const XP=(c,n=100)=>{let u=U(c.uid),old=u.level;u.xp=(u.xp||0)+n;while(u.xp>=u.level*100){u.xp-=u.level*100;u.level++}return old<u.level?`\n🎉 LEVEL UP ${old} ➜ ${u.level}!`:""};
const REWARD=(c,x=150,cash=75000,it=["🎁 Mission Box","💎 Rare Gem","🪙 GTA Token"])=>{let u=U(c.uid);u.cash+=cash;u.totalEarned=(u.totalEarned||0)+cash;it.slice(0,3).forEach(i=>D(u,i));return`💰 +${money(cash)}\n🎁 ${it.slice(0,3).join(" • ")}\n✨ +${x} XP${XP(c,x)}`};
const CD=(u,k,s)=>{let r=(u.cooldowns[k]||0)-Date.now();if(r>0)return Math.ceil(r/1000);u.cooldowns[k]=Date.now()+s*1000;return 0};
const target=c=>Object.keys(c.event?.mentions||{})[0]||c.event?.messageReply?.senderID||c.replyToUserID||null;
const LIST=(a,p=1)=>{let s=(Math.max(1,num(p))-1)*10;return a.slice(s,s+10).map((x,i)=>`${s+i+1}. ${x}`).join("\n")||"Nothing found."};
const add=(names,fn)=>String(names).split("|").forEach(n=>C[N(n)]={name:N(n),execute:fn,module:"gta"});

const MISSIONS=["Street Deal","Bank Job","Armored Truck","Warehouse Raid","Night Robbery","Casino Run","Port Smuggle","Airport Heist","Train Hijack","Convoy Strike","Safehouse Raid","Diamond Job","Cyber Theft","Mansion Raid","Gold Transport","Gang Takeover","Undercover Job","Prison Break","Military Convoy","Final Syndicate"];
const CARS=["Banshee","Comet","Elegy","Infernus","Bullet","Cheetah","Turismo","Adder","Zentorno","T20","Nightshark","Reaper","Sultan","Buffalo","Jester","Kuruma","Phoenix","Sabre","Vigero","Tempesta"];
const weapons=["Pistol","SMG","Shotgun","Rifle","Sniper","Heavy Pistol","Combat SMG","Assault Rifle","Marksman","Special Carbine"];

add("gta_status",c=>{let u=U(c.uid);c.reply(`🚘 GTA STATUS\n👤 ${c.name}\n💰 Cash: ${money(u.cash)}\n⭐ Wanted: ${u.wanted}/5 ${BAR(u.wanted,5)}\n👮 Jail: ${u.jail?u.jail+" min":"FREE"}\n💪 Respect: ${u.respect}\n🏴 Crew: ${u.crew||"Solo"}\n🚗 Cars: ${u.cars.length}/${u.garage}`)});
add("wanted",c=>{let u=U(c.uid);c.reply(`🚨 WANTED LEVEL\n⭐ ${u.wanted}/5\n${BAR(u.wanted,5)}\n${u.wanted?"👮 Police are searching for you.":"😎 You are clean."}`)});
add("rob",c=>{let u=U(c.uid),t=target(c),r=CD(u,"rob",300);if(r)return c.reply(`⏳ Rob cooldown: ${r}s`);if(!t)return c.reply("💡 !rob @user");if(String(t)===String(c.uid))return c.reply("😂 You can't rob yourself.");let v=U(t),amt=Math.min(v.cash,Math.floor(25000+Math.random()*175000));if(!amt)return c.reply("❌ Target has no available cash.");v.cash-=amt;u.cash+=amt;u.wanted=Math.min(5,u.wanted+1);u.respect+=5;c.reply(`💰 ROBBERY SUCCESS\n💸 Stole ${money(amt)}\n⭐ Wanted +1\n💪 Respect +5`)});
add("hack",c=>{let u=U(c.uid),r=CD(u,"hack",600);if(r)return c.reply(`⏳ Hack cooldown: ${r}s`);let a=100000+Math.floor(Math.random()*400000);u.cash+=a;u.wanted=Math.min(5,u.wanted+1);c.reply(`💻 SYSTEM HACKED\n💰 +${money(a)}\n⭐ Wanted: ${u.wanted}/5\n${BAR(u.wanted,5)}`)});
add("mug|scam|carjack|extort|loan_shark|shred_records|smuggle|safe_crack|wire_tap|informant|underworld|infiltrate|snitch",c=>{let u=U(c.uid),n=N(c.event.body.split(/\s+/)[0].slice(1)),r=CD(u,n,180);if(r)return c.reply(`⏳ ${n} cooldown: ${r}s`);let a=30000+Math.floor(Math.random()*170000);u.cash+=a;u.wanted=Math.min(5,u.wanted+1);u.respect+=3;c.reply(`🕶️ ${n.toUpperCase()}\n💰 +${money(a)}\n⭐ Wanted ${u.wanted}/5\n💪 Respect +3`)});
add("heist",c=>{let u=U(c.uid),r=CD(u,"heist",43200);if(r)return c.reply(`⏳ Heist cooldown: ${Math.ceil(r/3600)}h`);let t=target(c),a=500000+Math.floor(Math.random()*1500000);u.cash+=a;u.respect+=25;u.wanted=Math.min(5,u.wanted+2);c.reply(`💎 HEIST COMPLETE\n${t?"🎯 Target crew involved":"👥 Crew operation"}\n💰 +${money(a)}\n💪 Respect +25\n⭐ Wanted ${u.wanted}/5\n${XP(c,500)}`)});
add("crew_create",c=>{let u=U(c.uid);if(u.crew)return c.reply("🏴 You already have a crew.");let name=c.args.join(" ")||"Klerk Syndicate";u.crew={name,members:[u.id],level:1};c.reply(`🏴 CREW CREATED\n🔥 ${name}\n👥 Members: 1`)});
add("crew_join",c=>{let u=U(c.uid),name=c.args.join(" ")||"Klerk Syndicate";if(u.crew)return c.reply("🏴 Leave your current crew first.");u.crew={name,members:[u.id],level:1};c.reply(`🏴 Joined ${name}.`)});
add("crew_kick",c=>{let u=U(c.uid);if(!u.crew)return c.reply("❌ No crew.");let t=target(c);if(!t)return c.reply("💡 Mention a crew member.");u.crew.members=u.crew.members.filter(x=>String(x)!==String(t));c.reply("👢 Crew member removed.")});
add("heist_plan|heist_prep",c=>{let u=U(c.uid);if(!u.crew)return c.reply("🏴 Create/join a crew first.");u.respect+=10;c.reply(`🗺️ HEIST PLAN READY\n🏴 ${u.crew.name}\n👥 ${u.crew.members.length} member(s)\n💪 +10 Respect`)});
add("bounty_hunt",c=>{let u=U(c.uid),t=target(c),r=CD(u,"bounty",900);if(r)return c.reply(`⏳ Bounty cooldown: ${r}s`);if(!t)return c.reply("💡 !bounty_hunt @user");let v=U(t),a=100000+v.wanted*100000;u.cash+=a;u.respect+=10;v.wanted=0;c.reply(`🎯 BOUNTY HUNT COMPLETE\n💰 +${money(a)}\n💪 +10 Respect\n🚨 Target wanted level cleared.`)});
add("bounty_board",c=>c.reply(`🎯 BOUNTY BOARD\n${LIST(["🚨 Street Boss — $100K","💰 Bank Raider — $250K","💎 Diamond Thief — $500K","🔥 Gang Leader — $750K","👑 Syndicate Boss — $1M","🕶️ Master Hacker — $1.25M","🚘 Car Baron — $1.5M","🏴 Crew Boss — $2M","💀 Most Wanted — $3M","🌟 Crime Legend — $5M"],1)}`));
add("weapons",c=>c.reply(`🔫 WEAPON SHOP\n${LIST(weapons.map((x,i)=>`${x} — ${money(50000+i*25000)}`),1)}\n💡 !buyweapon <name>`));
add("buyweapon",c=>{let u=U(c.uid),n=c.args.join(" ")||"Pistol",a=50000;if(u.cash<a)return c.reply("❌ Not enough cash.");u.cash-=a;D(u,"🔫 "+n);c.reply(`🔫 Purchased ${n} for ${money(a)}.`)});
add("armory_store",c=>c.reply(`🏪 ARMORY\n${LIST(["Ammo Pack","Armor Plate","Med Kit","Smoke Grenade","Vehicle Kit","Repair Kit","Lockpick","Tracker","Fuel Can","Tactical Gear"],1)}`));
add("garage",c=>{let u=U(c.uid);c.reply(`🚗 GARAGE ${u.cars.length}/${u.garage}\n${LIST(u.cars.map(x=>`${x.name} ❤️${x.hp}% ⛽${x.fuel}%`),1)||"Empty."}`)});
add("vehicles",c=>{let u=U(c.uid);c.reply(`🚘 VEHICLES\n${LIST(CARS.map(x=>`${x} — ${money(250000+CARS.indexOf(x)*100000)}`),1)}\n🚗 Owned: ${u.cars.length}/${u.garage}`)});
add("vehicle",c=>{let u=U(c.uid),car=u.cars.find(x=>N(x.name)===N(c.args.join(" ")));if(!car)return c.reply("❌ Vehicle not found.");c.reply(`🚘 ${car.name}\n❤️ Condition: ${car.hp}%\n⛽ Fuel: ${car.fuel}%\n🏎️ Engine: ${car.engine||1}`)});
add("buycar",c=>{let u=U(c.uid),n=N(c.args.join(" ")),i=CARS.findIndex(x=>N(x)===n);if(i<0)return c.reply("❌ Car not found.\n💡 !vehicles");if(u.cars.length>=u.garage)return c.reply("🏠 Garage full.");let cost=250000+i*100000;if(u.cash<cost)return c.reply(`❌ Need ${money(cost)}.`);u.cash-=cost;u.cars.push({name:CARS[i],hp:100,fuel:100,engine:1,tires:1,paint:"Stock"});c.reply(`🚗 CAR PURCHASED\n🏎️ ${CARS[i]}\n💰 -${money(cost)}`)});
add("sellcar",c=>{let u=U(c.uid),n=N(c.args.join(" ")),i=u.cars.findIndex(x=>N(x.name)===n);if(i<0)return c.reply("❌ Car not found.");let car=u.cars.splice(i,1)[0],v=150000+(car.engine||1)*50000;u.cash+=v;c.reply(`💰 ${car.name} sold for ${money(v)}.`)});
add("drive",c=>{let u=U(c.uid),car=u.cars.find(x=>N(x.name)===N(c.args.join(" ")))||u.cars[0];if(!car)return c.reply("🚗 Buy a car first.");if(car.fuel<10)return c.reply("⛽ Refuel first.");car.fuel-=10;u.respect+=2;c.reply(`🏎️ ${car.name} driven!\n⛽ Fuel: ${car.fuel}%\n💪 Respect +2`)});
add("park",c=>c.reply("🅿️ Vehicle parked safely."));
add("repaircar",c=>{let u=U(c.uid),car=u.cars[0];if(!car)return c.reply("🚗 No vehicle.");let a=(100-car.hp)*2000;if(u.cash<a)return c.reply(`❌ Repair costs ${money(a)}.`);u.cash-=a;car.hp=100;c.reply(`🔧 Repaired ${car.name}.\n💰 -${money(a)}`)});
add("fuel|refuel",c=>{let u=U(c.uid),car=u.cars[0];if(!car)return c.reply("🚗 No vehicle.");let a=(100-car.fuel)*1000;if(u.cash<a)return c.reply(`❌ Fuel costs ${money(a)}.`);u.cash-=a;car.fuel=100;c.reply(`⛽ ${car.name} refueled.`)});
add("carwash",c=>{let u=U(c.uid);if(u.cash<10000)return c.reply("❌ Car wash costs $10K.");u.cash-=10000;c.reply("🧼 Vehicle cleaned.")});
add("car_upgrade",c=>{let u=U(c.uid),car=u.cars[0];if(!car)return c.reply("🚗 No vehicle.");let a=100000*car.engine;if(u.cash<a)return c.reply(`❌ Upgrade costs ${money(a)}.`);u.cash-=a;car.engine++;c.reply(`🔧 ${car.name} engine upgraded to ${car.engine}.`)});
add("engine|tires|paint|license",c=>{let u=U(c.uid),car=u.cars[0];if(!car)return c.reply("🚗 No vehicle.");if(c.args.length){car[N(c.event.body.split(/\s+/)[0].slice(1))]=c.args.join(" ")}else car[N(c.event.body.split(/\s+/)[0].slice(1))]=(car[N(c.event.body.split(/\s+/)[0].slice(1))]||0)+1;c.reply(`🚘 ${c.event.body.split(/\s+/)[0].slice(1)} updated for ${car.name}.`)});
add("vehicle_trade|vehicle_market",c=>c.reply(`🚘 VEHICLE MARKET\n${LIST(CARS.map((x,i)=>`${x} — ${money(250000+i*100000)}`),1)}`));
add("race|race_join|race_create|race_lb|street_race",c=>{let u=U(c.uid),r=CD(u,"race",120);if(r)return c.reply(`⏳ Race cooldown: ${r}s`);let win=Math.random()<.55;u.respect+=win?10:2;if(win)c.reply(`🏁 RACE WON!\n💰 +$100K\n💪 +10 Respect\n${XP(c,150)}`);else c.reply(`🏁 RACE FINISHED\n💪 +2 Respect`)});
add("motorcycle|boat|plane",c=>{let u=U(c.uid),n=N(c.event.body.split(/\s+/)[0].slice(1));let a=n==="motorcycle"?200000:n==="boat"?1000000:5000000;if(u.cash<a)return c.reply(`❌ ${n} costs ${money(a)}.`);u.cash-=a;D(u,"🚘 "+n);c.reply(`🚘 ${n.toUpperCase()} acquired for ${money(a)}.`)});

add("garage_upgrade",c=>{let u=U(c.uid),a=u.garage*250000;if(u.cash<a)return c.reply(`❌ Need ${money(a)}.`);u.cash-=a;u.garage++;c.reply(`🏠 Garage capacity increased to ${u.garage}.`)});
add("modcar",c=>{let u=U(c.uid),car=u.cars[0];if(!car)return c.reply("🚗 No vehicle.");car.engine++;car.hp=100;c.reply(`🔧 ${car.name} modified!\n⚙️ Engine Lv.${car.engine}\n❤️ 100%`)});
add("chop_shop",c=>{let u=U(c.uid),car=u.cars.shift();if(!car)return c.reply("❌ No car to chop.");let a=75000;u.cash+=a;u.wanted=Math.min(5,u.wanted+2);c.reply(`🔧 CHOP SHOP\n💰 +${money(a)}\n⭐ Wanted +2`)});
add("warehouse|safehouse|syndicate_hq",c=>{let u=U(c.uid),a=500000;if(u.cash<a)return c.reply(`❌ Property costs ${money(a)}.`);u.cash-=a;u.turf++;c.reply(`🏢 ${c.event.body.split(/\s+/)[0].slice(1).toUpperCase()} secured!\n💪 Turf: ${u.turf}`)});
add("turf_claim|turf_war|rank_respect|gang_upgrade|smuggle_sea|smuggle_air|hit_list|money_laund|bribe_cop|jail_break|street_race",c=>{let u=U(c.uid),n=N(c.event.body.split(/\s+/)[0].slice(1)),a=50000+Math.floor(Math.random()*250000);u.cash+=a;u.respect+=10;u.wanted=Math.min(5,u.wanted+1);c.reply(`🏴 ${n.toUpperCase()}\n💰 +${money(a)}\n💪 Respect +10\n⭐ Wanted ${u.wanted}/5\n${XP(c,100)}`)});
add("jail_break",c=>{let u=U(c.uid);if(!u.jail)return c.reply("😎 You're already free.");if(Math.random()<.65){u.jail=0;u.wanted=Math.min(5,u.wanted+1);c.reply("💥 JAILBREAK SUCCESS!\n🏃 You're free!\n⭐ Wanted +1")}else{u.jail+=10;c.reply("🚔 Jailbreak failed. +10 minutes.")}});
add("jail",c=>{let u=U(c.uid);u.jail=10;c.reply("🚔 You are now in jail for 10 minutes.")});
add("underworld",c=>c.reply(`🌑 UNDERWORLD\n${LIST(["Street Dealers","Fixers","Hackers","Smugglers","Car Thieves","Bounty Hunters","Mercenaries","Crime Bosses","Syndicates","Shadow Market"],1)}`));

MISSIONS.forEach((m,i)=>add(`gta_mission_${i+1}`,c=>{let u=U(c.uid),k=`gta_mission_${i+1}`,r=CD(u,k,1800);if(r)return c.reply(`⏳ Mission cooldown: ${Math.ceil(r/60)}m`);if(u.gtaMissions[k])return c.reply("✅ Mission already completed.");u.gtaMissions[k]=true;u.missionsDone++;u.respect+=15;let cash=100000+i*75000;u.cash+=cash;["🎁 Mission Crate","💎 GTA Gem","🪙 Crew Token"].forEach(x=>D(u,x));let x=200+i*25;c.reply(`🎯 GTA MISSION ${i+1}/20\n📜 ${m}\n✅ COMPLETED\n💰 +${money(cash)}\n🎁 🎁 Mission Crate • 💎 GTA Gem • 🪙 Crew Token\n💪 Respect +15\n✨ +${x} XP${XP(c,x)}`)}));

add("missions",c=>c.reply(`🎯 GTA MISSIONS\n${LIST(MISSIONS.map((x,i)=>`${i+1}. ${x}${U(c.uid).gtaMissions["gta_mission_"+(i+1)]?" ✅":""}`),1)}\n💡 !gta_mission_1 through !gta_mission_20`));
add("gta_mission",c=>{let n=num(c.args[0]);if(n<1||n>20)return c.reply("💡 Missions are !gta_mission_1 through !gta_mission_20");let f=C[`gta_mission_${n}`];f?.execute(c)});
add("gta_jobs",c=>c.reply(`💼 GTA JOBS\n${LIST(["Driver","Getaway Driver","Hacker","Lookout","Muscle","Smuggler","Mechanic","Dealer","Fixer","Enforcer"],1)}\n${REWARD(c,150,75000,["💼 Job Token","🎁 Job Crate","💎 Job Gem"])}`));
add("rank_respect",c=>{let u=U(c.uid);c.reply(`💪 RESPECT ${u.respect}\n${BAR(Math.min(u.respect,100),100)}\n🏆 Rank: ${u.respect>=100?"Legend":u.respect>=50?"Boss":"Street Rookie"}`)});
add("blacklist",c=>c.reply("🚫 GTA blacklist checked."));
add("police_heat",c=>{let u=U(c.uid);c.reply(`👮 POLICE HEAT\n⭐ ${u.wanted}/5\n${BAR(u.wanted,5)}`)});
add("bail",c=>{let u=U(c.uid),a=Math.max(25000,u.jail*10000);if(!u.jail)return c.reply("😎 You're free.");if(u.cash<a)return c.reply(`❌ Bail is ${money(a)}.`);u.cash-=a;u.jail=0;c.reply(`⚖️ BAIL PAID\n💰 -${money(a)}\n🚪 Released.`)});

module.exports=Object.values(C);
