// commands/cmds_10.js // 👤 SOCIAL + 🤖 AI + ⚽ SPORTS + ADMIN — iKON-BOT
module.exports=({api,event,user,reply,users,profile,fun})=>{
const r=t=>api.sendMessage(t,event.threadID,()=>{},event.messageID);
user.crime=user.crime||{rep:0,heat:0,success:0,fail:0,heists:0,crew:[],rank:1};
user.heists=user.heists||[];
user.safehouse=user.safehouse||{level:1};
user.blackmarket=user.blackmarket||{};
user.inventory=user.inventory||{};
user.social=user.social||{marry:null,partner:null,crush:null};
user.wallet=user.wallet||0;
const jobs={social:[100,1000,5],ai:[200,2000,10],sports:[100,1500,5],admin:[0,0,0]};
const crime=(id)=>jobs[String(id||"").toLowerCase()];
const cmds=[
{name:"marry",run:async({args})=>{let t=args[0]||"someone";if(user.social.marry)return r(`💍 Already married to ${user.social.marry}`);user.social.marry=t;r(`💍 You proposed to ${t}!\n💑 Married! ${fun()}`)}},
{name:"divorce",run:async()=>{if(!user.social.marry)return r("💔 Not married.");let ex=user.social.marry;user.social.marry=null;r(`💔 Divorced ${ex}.`)}},
{name:"partner",run:async({args})=>{if(args[0]){user.social.partner=args[0];r(`💑 Partner set: ${args[0]}`)}else{r(`💑 Partner: ${user.social.partner||"None"}`)}}},
{name:"couple",aliases:["couples"],run:async({args})=>{let a=args[0]||event.senderID,b=args[1]||event.senderID;let pa=await profile(api,a),pb=await profile(api,b);r(`💑 COUPLE\n${pa.name} + ${pb.name}\n❤️ Match: ${Math.floor(Math.random()*100)}%`)}},
{name:"pair",run:async({args})=>{let a=args[0]||"User1",b=args[1]||"User2";r(`💞 PAIRED\n${a} + ${b} = ${Math.floor(Math.random()*100)}% Love`)}},
{name:"crush",run:async({args})=>{let t=args[0]||"secret";user.social.crush=t;r(`💘 Your crush is ${t}! Shhh...`)}},
{name:"slap",run:async({args})=>{let t=args[0]||"someone";r(`👋 ${user.firstName||"You"} slapped ${t}! 💥`)}},
{name:"kiss",run:async({args})=>{let t=args[0]||"someone";r(`😘 ${user.firstName||"You"} kissed ${t}! ❤️`)}},
{name:"hug",run:async({args})=>{let t=args[0]||"someone";r(`🤗 ${user.firstName||"You"} hugged ${t}!`)}},
{name:"poke",run:async({args})=>{let t=args[0]||"someone";r(`👉 Poked ${t}!`)}},
{name:"gift",run:async({args})=>{let t=args[0]||"someone";let g=args.slice(1).join(" ")||"🎁";r(`🎁 You gifted ${g} to ${t}!`)}},
{name:"spy",run:async({args})=>{let t=args[0]||"someone";let p=await profile(api,t).catch(()=>({name:t}));r(`🕵️ SPY\n👤 ${p.name}\n🆔 ${t}\n💰 $${(users.get(t)?.wallet||0).toLocaleString()}`)}},
{name:"roast",run:async({args})=>{let t=args[0]||"someone";r(`🔥 Roast for ${t}:\n${fun()} - You're so broke your wallet has cobwebs!`)}},
{name:"compliment",aliases:["comp"],run:async({args})=>{let t=args[0]||"you";r(`💖 ${t} you are amazing, smart and unstoppable! ✨`)}},
{name:"ship",run:async({args})=>{let a=args[0]||"Me",b=args[1]||"You";r(`🚢 SHIP\n${a} + ${b}\nLove: ${Math.floor(Math.random()*100)}% ${fun()}`)}},
{name:"ai",run:async({args})=>{let q=args.join(" ")||"Hello";r(`🤖 AI\nQ: ${q}\nA: I'm iKON-BOT AI, how can I help with "${q}"?`)}},
{name:"ask",run:async({args})=>{let q=args.join(" ")||"Hi";r(`🤖 ASK: ${q}\n💡 Answer: This is a simulated AI response for "${q}"`)}},
{name:"chat",run:async({args})=>r(`💬 CHAT\n${args.join(" ")||"Hello there!"} - Let's chat!`)},
{name:"imagine",aliases:["gen"],run:async({args})=>{let p=args.join(" ")||"a cat";r(`🎨 IMAGINE\nPrompt: ${p}\n🖼️ Image generated (simulated).`)}},
{name:"image",run:async({args})=>r(`🖼️ IMAGE\nSearching image for: ${args.join(" ")||"random"}`)},
{name:"translate",aliases:["trans"],run:async({args})=>{let t=args.join(" ");if(!t)return r("🌐 Use!translate <text>");r(`🌐 TRANSLATE\n${t}\n-> [Translated] ${t}`)}},
{name:"summarize",run:async({args})=>r(`📝 SUMMARY\n${args.join(" ").slice(0,100)}... -> Summarized.`)},
{name:"define",run:async({args})=>{let w=args[0]||"word";r(`📖 DEFINE: ${w}\nMeaning: A simulated definition of ${w}.`)}},
{name:"search",run:async({args})=>r(`🔍 SEARCH\nQuery: ${args.join(" ")||"nothing"}\nResults: (simulated)`)},
{name:"weather",run:async({args})=>{let c=args.join(" ")||"Amman";r(`🌤️ WEATHER ${c}\n☀️ 28°C Sunny, 20% rain.`)}},
{name:"calc",run:async({args})=>{try{let e=args.join(" ");let res=eval(e);r(`🧮 ${e} = ${res}`)}catch(e){r("❌ Invalid calculation.")}}},
{name:"convert",run:async({args})=>r(`🔄 CONVERT\n${args.join(" ")}\nResult: (simulated conversion)`)},
{name:"qrcode",aliases:["qr"],run:async({args})=>{let t=args.join(" ")||"https://example.com";r(`🔳 QR CODE\nText: ${t}\n[QR Generated]`)}},
{name:"youtube",aliases:["yt"],run:async({args})=>r(`▶️ YOUTUBE\nSearch: ${args.join(" ")||"music"}\nLink: https://youtu.be/simulated`)},
{name:"music",run:async({args})=>r(`🎵 MUSIC\nPlaying: ${args.join(" ")||"random song"} 🎶`)},
{name:"video",run:async({args})=>r(`🎬 VIDEO\nFetching: ${args.join(" ")||"random video"}`)},
{name:"sticker",run:async()=>r("🖼️ STICKER\nSend an image with!sticker")},
{name:"gif",run:async({args})=>r(`🎞️ GIF\nSearch: ${args.join(" ")||"funny"}`)},
{name:"meme",run:async(()=>{const m=["😂 Meme 1","🤣 Meme 2","💀 Meme 3"];r(`🤣 MEME\n${m[Math.floor(Math.random()*m.length)]} ${fun()}`)})},
{name:"caption",run:async({args})=>r(`✍️ CAPTION\n"${args.join(" ")||"My photo"}" - Nice caption!`)},
{name:"rewrite",run:async({args})=>r(`🔄 REWRITE\nOriginal: ${args.join(" ")}\nNew: ${args.join(" ").split("").reverse().join("")} (rewritten)`)},
{name:"prompt",run:async({args})=>r(`💡 PROMPT\n${args.join(" ")||"Give me a prompt idea"}`)},
{name:"explain",run:async({args})=>r(`📚 EXPLAIN\nTopic: ${args.join(" ")||"something"}\nExplanation: (simulated explanation)`)},
{name:"football",aliases:["futbol"],run:async()=>r("⚽ FOOTBALL\n!live!livescore!fixtures!results!standings")},
{name:"live",aliases:["livescore"],run:async()=>r("⚽ LIVE SCORES\nReal Madrid 2-1 Barca (78')\nMan City 0-0 Arsenal (45')")},
{name:"fixtures",run:async()=>r("📅 FIXTURES\nToday: Real vs Barca 21:00\nTomorrow: City vs Arsenal")},
{name:"results",run:async()=>r("📊 RESULTS\nYesterday: Chelsea 3-0 Liverpool")},
{name:"match",run:async({args})=>r(`⚽ MATCH\nInfo for: ${args.join(" ")||"Real Madrid"}`)},
{name:"team",run:async({args})=>r(`👕 TEAM\nInfo: ${args.join(" ")||"Real Madrid"}`)},
{name:"teams",run:async()=>r("👕 TEAMS\nReal Madrid, Barcelona, Man City, Arsenal...")},
{name:"league",run:async({args})=>r(`🏆 LEAGUE\n${args.join(" ")||"La Liga"}`)},
{name:"leagues",run:async()=>r("🏆 LEAGUES\nLa Liga, Premier League, Serie A...")},
{name:"standings",aliases:["table"],run:async({args})=>r(`📊 STANDINGS ${args.join(" ")||"La Liga"}\n1. Real Madrid - 75 pts\n2. Barca - 70 pts`)},
{name:"footballnews",run:async()=>r("📰 FOOTBALL NEWS\nMessi scores hat-trick! (simulated)")},
{name:"wrestling",aliases:["wwe"],run:async()=>r("🤼 WRESTLING\n!wrestlingnews!wwe!ufc")},
{name:"wrestlingnews",run:async()=>r("📰 WRESTLING NEWS\nRoman Reigns retains title!")},
{name:"ufc",run:async()=>r("🥊 UFC\nNext fight: McGregor vs Chandler")},
{name:"sports",aliases:["score"],run:async()=>r("🏅 SPORTS\n!football!wrestling!ufc")},
{name:"player",run:async({args})=>r(`👤 PLAYER\n${args.join(" ")||"Ronaldo"} - Stats: 850 goals`)},
{name:"menu",run:async()=>r("📜 MENU\n!menu1 - Casino & Games\n!menu2 - Social AI Sports Admin")},
{name:"menu1",run:async()=>r("📜 MENU 1 (70)\n!casino!gamble!coinflip!dice!slots!roulette!blackjack!poker!baccarat!rps!guess!lottery!jackpot!crash!games!profile!friends!...")},
{name:"menu2",run:async()=>r("📜 MENU 2 (70)\n!marry!slap!kiss!ship!ai!imagine!translate!football!live!fixtures!menu!botinfo!admin!...")},
{name:"commands",aliases:["cmd"],run:async()=>r("📜 COMMANDS\n350 total commands\n!menu1!menu2")},
{name:"botinfo",aliases:["bot"],run:async()=>r(`🤖 iKON-BOT\nPrefix:!\nUsers: ${users.size}\nUptime: ${Math.floor(process.uptime()/60)}m`)},
{name:"ping",run:async()=>{let s=Date.now();r(`🏓 PING\n${Date.now()-s}ms`)}},
{name:"uptime",run:async()=>r(`⏱️ UPTIME\n${Math.floor(process.uptime()/3600)}h ${Math.floor(process.uptime()%3600/60)}m`)},
{name:"groupinfo",aliases:["gcinfo"],run:async()=>r(`👥 GROUP\nID: ${event.threadID}\nMembers: ${event.participantIDs?.length||"Unknown"}`)},
{name:"members",run:async()=>r(`👥 Members: ${event.participantIDs?.length||0}`)},
{name:"admins",run:async()=>{let a=event.adminIDs?.length||0;r(`👑 Admins: ${a}`)}},
{name:"rules",run:async()=>r("📜 RULES\nNo spam, no abuse, respect all.")},
{name:"status",run:async()=>r("🟢 Bot is online and active!")},
{name:"report",run:async({args})=>r(`🚩 REPORTED: ${args.join(" ")||"Issue"}\nSent to admins.`)},
{name:"suggest",run:async({args})=>r(`💡 SUGGESTION: ${args.join(" ")}\nThanks!`)},
{name:"feedback",run:async({args})=>r(`📝 FEEDBACK: ${args.join(" ")}\nReceived!`)},
{name:"support",run:async()=>r("🆘 SUPPORT\nContact admin or!report")},
{name:"prefix",run:async({args})=>{if(args[0]){r(`🔧 Prefix set to ${args[0]} (simulated)`)}else{r("🔧 Current prefix:!")}}},
{name:"slowmode",run:async({args})=>r(`🐢 SLOWMODE ${args[0]||"off"} - Set.`)},
{name:"antispam",run:async()=>r("🛡️ ANTISPAM Enabled.")},
{name:"announce",run:async({args})=>r(`📢 ANNOUNCE: ${args.join(" ")||"Hello @everyone"}`)},
{name:"admin",run:async()=>r("🛠️ ADMIN\n!settings!enable!disable!maintenance!broadcast!logs!warn!ban")},
{name:"settings",run:async()=>r("⚙️ SETTINGS\n!enable!disable!prefix!slowmode")},
{name:"enable",run:async({args})=>r(`✅ Enabled: ${args[0]||"feature"}`)},
{name:"disable",run:async({args})=>r(`❌ Disabled: ${args[0]||"feature"}`)},
{name:"maintenance",run:async({args})=>r(`🔧 MAINTENANCE ${args[0]||"off"}`)},
{name:"broadcast",aliases:["bc"],run:async({args})=>{let m=args.join(" ")||"Broadcast";let c=0;for(let id of users.keys()){c++}r(`📢 Broadcast sent to ${c} users:\n${m}`)}},
{name:"reload",run:async()=>r("♻️ Reloaded all commands.")},
{name:"logs",run:async()=>r("📋 LOGS\n[Simulated logs...]")},
{name:"stats",run:async()=>r(`📊 STATS\nUsers: ${users.size}\nWallet total: $${[...users.values()].reduce((a,b)=>a+(b.wallet||0),0).toLocaleString()}`)},
{name:"pending",run:async()=>r("⏳ PENDING\nNo pending approvals.")},
{name:"approve",run:async({args})=>r(`✅ Approved ${args[0]||"user"}`)},
{name:"reject",run:async({args})=>r(`❌ Rejected ${args[0]||"user"}`)},
{name:"pendinggc",run:async()=>r("⏳ PENDING GC: 0 groups")},
{name:"approvegc",run:async({args})=>r(`✅ GC Approved: ${args[0]||"id"}`)},
{name:"rejectgc",run:async({args})=>r(`❌ GC Rejected: ${args[0]||"id"}`)},
{name:"warn",run:async({args})=>{let uid=args[0];if(!uid)return r("❌ Use!warn <uid>");let u=users.get(uid);if(!u)return r("❌ User not found");u.warnings=(u.warnings||0)+1;r(`⚠️ Warned ${uid} - Total: ${u.warnings}`)}},
{name:"warnings",run:async({args})=>{let uid=args[0]||event.senderID;let u=users.get(uid);r(`⚠️ Warnings for ${uid}: ${u?.warnings||0}`)}},
{name:"kick",run:async({args})=>r(`👢 Kicked ${args[0]||"user"} from group.`)},
{name:"ban",run:async({args})=>{let uid=args[0];if(!uid)return r("❌ Use!ban <uid>");let u=users.get(uid);if(u)u.banned=true;r(`🔨 Banned ${uid}`)}},
{name:"unban",run:async({args})=>{let uid=args[0];if(!uid)return r("❌ Use!unban <uid>");let u=users.get(uid);if(u)u.banned=false;r(`♻️ Unbanned ${uid}`)}},
]; async function doCrime(id){let j=crime(id);if(!j)return r("❌ Service unavailable.");let cash=Math.floor(Math.random()*(j[1]-j[0]+1))+j[0];user.wallet+=cash;user.crime.rep+=j[2];r(`💀 ${id.toUpperCase()} DONE!\n💰 +$${cash.toLocaleString()}\n⭐ Rep +${j[2]}`)} return cmds; };
