// commands/cmds_5.js
// ⛏️ FRONTIER — iKON-BOT
module.exports=({api,event,user,reply,users,profile,fun})=>{
const replyx=t=>api.sendMessage(t,event.threadID,()=>{},event.messageID);
const xp=(u,n=5)=>{u.xp=(u.xp||0)+n;};
const ensure=u=>{u.inventory=u.inventory||{};u.mining=u.mining||{level:1,xp:0,ore:0};u.fishing=u.fishing||{level:1,xp:0};u.hunting=u.hunting||{level:1,xp:0};u.resources=u.resources||{};};
const add=(u,id,n=1)=>{u.inventory[id]=(u.inventory[id]||0)+n};
const rem=(u,id,n=1)=>{if((u.inventory[id]||0)<n)return false;u.inventory[id]-=n;if(u.inventory[id]<=0)delete u.inventory[id];return true};
const fmt=n=>Number(n||0).toLocaleString();
const ores={coal:{name:"Coal",value:500,rarity:"Common"},iron:{name:"Iron Ore",value:800,rarity:"Common"},copper:{name:"Copper Ore",value:1200,rarity:"Common"},silver:{name:"Silver Ore",value:2500,rarity:"Rare"},gold:{name:"Gold Ore",value:3500,rarity:"Rare"},platinum:{name:"Platinum",value:8000,rarity:"Epic"},ruby:{name:"Ruby",value:10000,rarity:"Epic"},emerald:{name:"Emerald",value:9000,rarity:"Epic"},diamond:{name:"Diamond",value:12000,rarity:"Legendary"},obsidian:{name:"Obsidian",value:25000,rarity:"Mythic"}};
const fish={trout:{name:"Trout",value:700,rarity:"Common"},salmon:{name:"Salmon",value:1200,rarity:"Common"},tuna:{name:"Tuna",value:2500,rarity:"Rare"},shark:{name:"Shark",value:7000,rarity:"Epic"},swordfish:{name:"Swordfish",value:10000,rarity:"Epic"},goldfish:{name:"Golden Fish",value:25000,rarity:"Legendary"},krakenfish:{name:"Kraken Fish",value:100000,rarity:"Mythic"}};
const animals={rabbit:{name:"Rabbit",value:500},deer:{name:"Deer",value:1500},boar:{name:"Boar",value:2500},wolf:{name:"Wolf",value:5000},bear:{name:"Bear",value:8000},lion:{name:"Lion",value:15000},tiger:{name:"Tiger",value:25000},elephant:{name:"Elephant",value:50000},dragon:{name:"Dragon",value:250000}};
const rand=o=>{let k=Object.keys(o);return k[Math.floor(Math.random()*k.length)]};
const cmds=[
{name:"mine",aliases:["mining"],description:"Mine random ores",run:async()=>{ensure(user);let n=1+Math.floor(Math.random()*3),found=[];for(let i=0;i<n;i++){let id=rand(ores);add(user,id,1);found.push(ores[id].name)}user.mining.xp+=20;xp(user,10);replyx(`⛏️ MINING RUN\n${found.map(x=>`• ${x}`).join("\n")}\n⭐ Mining XP +20`)}},
{name:"ores",aliases:["orelist"],description:"List mineable ores",run:async()=>replyx(`⛏️ ORES\n${Object.values(ores).map(x=>`${x.name} • ${x.rarity} • $${fmt(x.value)}`).join("\n")}`)},
{name:"oreinfo",aliases:["ore"],description:"View ore information",run:async({args})=>{let q=args.join(" ").toLowerCase(),id=Object.keys(ores).find(k=>k===q||ores[k].name.toLowerCase()===q||k.includes(q));if(!id)return replyx("❌ Ore not found.");let x=ores[id];replyx(`⛏️ ${x.name}\nRarity: ${x.rarity}\nValue: $${fmt(x.value)}`)}},
{name:"dig",aliases:["digging"],description:"Dig for treasure",run:async()=>{ensure(user);let roll=Math.random();if(roll<.1){let reward=25000+Math.floor(Math.random()*50000);user.wallet=(user.wallet||0)+reward;replyx(`💎 TREASURE FOUND!\n💰 +$${fmt(reward)}`)}else{let id=rand(ores);add(user,id,1);replyx(`⛏️ You dug up ${ores[id].name}!`)}}},
{name:"excavate",aliases:["excavation"],description:"Excavate a deep site",run:async()=>{ensure(user);let id=rand(ores);let qty=2+Math.floor(Math.random()*4);add(user,id,qty);user.mining.xp+=50;replyx(`🏔️ EXCAVATION\n${ores[id].name} ×${qty}\n⭐ +50 Mining XP`)}},
{name:"prospect",aliases:["prospecting"],description:"Search for valuable resources",run:async()=>{ensure(user);let id=rand(ores),chance=Math.random();if(chance>.7)id=rand(ores);replyx(`🔎 PROSPECTING\nPotential deposit: ${ores[id].name}\nRarity: ${ores[id].rarity}`)}},
{name:"smelt",aliases:["smelting"],description:"Smelt ore",run:async({args})=>{ensure(user);let q=args.join(" ").toLowerCase(),id=Object.keys(ores).find(k=>k===q||ores[k].name.toLowerCase()===q);if(!id)return replyx("Usage: !smelt <ore>");if(!rem(user,id,2))return replyx("❌ Need 2 ores.");let bar=id+"_bar";add(user,bar,1);replyx(`🔥 Smelted 2 ${ores[id].name} into 1 ${bar}.`)}},
{name:"forge",aliases:["forging"],description:"Forge equipment",run:async({args})=>{ensure(user);let q=args.join(" ").toLowerCase();if(q.includes("iron sword")){if(!rem(user,"iron_bar",3))return replyx("❌ Need 3 Iron Bars.");add(user,"iron_sword");replyx("⚔️ Forged Iron Sword.")}else if(q.includes("steel")){if(!rem(user,"iron_bar",5)||!rem(user,"coal",2))return replyx("❌ Need 5 Iron Bars + 2 Coal.");add(user,"steel_armor");replyx("🛡️ Forged Steel Armor.")}else replyx("🔨 Available: Iron Sword, Steel Armor.")}},
{name:"fish",aliases:["fishing"],description:"Go fishing",run:async()=>{ensure(user);let id=rand(fish),qty=1+Math.floor(Math.random()*2);add(user,id,qty);user.fishing.xp+=20;xp(user,8);replyx(`🎣 FISHING\n🐟 ${fish[id].name} ×${qty}\n⭐ Fishing XP +20`)}},
{name:"bait",aliases:["fishbait"],description:"View fishing bait",run:async()=>replyx("🎣 BAIT\n• Worm Bait — Common\n• Shrimp Bait — Rare\n• Golden Bait — Legendary\nBetter bait improves rare catch chances.")},
{name:"fishingrod",aliases:["rod"],description:"Check fishing rod",run:async()=>{ensure(user);replyx(`🎣 FISHING ROD\nLevel: ${user.fishing.level}\nXP: ${user.fishing.xp}\n🎯 Rare chance: ${Math.min(50,user.fishing.level*5)}%`)}},
{name:"fishinfo",aliases:["fishdetails"],description:"View fish information",run:async({args})=>{let q=args.join(" ").toLowerCase(),id=Object.keys(fish).find(k=>k===q||fish[k].name.toLowerCase()===q);if(!id)return replyx("❌ Fish not found.");let x=fish[id];replyx(`🐟 ${x.name}\nRarity: ${x.rarity}\nValue: $${fmt(x.value)}`)}},
{name:"fishinglevel",aliases:["fishlevel"],description:"View fishing level",run:async()=>{ensure(user);replyx(`🎣 FISHING LEVEL ${user.fishing.level}\nXP: ${user.fishing.xp}/${user.fishing.level*500}`)}},
{name:"fishquest",aliases:["fishingquest"],description:"Complete fishing quest",run:async()=>{ensure(user);let reward=5000+user.fishing.level*1000;user.wallet=(user.wallet||0)+reward;user.fishing.xp+=50;replyx(`🎣 FISHING QUEST COMPLETE!\n💰 +$${fmt(reward)}\n⭐ +50 Fishing XP`)}},
{name:"hunt",aliases:["hunting"],description:"Hunt an animal",run:async()=>{ensure(user);let id=rand(animals),a=animals[id];add(user,"raw_"+id,1);user.hunting.xp+=20;xp(user,10);replyx(`🏹 HUNT COMPLETE\n🦌 ${a.name}\n💰 Value: $${fmt(a.value)}\n⭐ Hunting XP +20`)}},
{name:"animals",aliases:["animalist"],description:"View huntable animals",run:async()=>replyx(`🦌 ANIMALS\n${Object.values(animals).map(x=>`${x.name} — $${fmt(x.value)}`).join("\n")}`)},
{name:"tracking",aliases:["track"],description:"Track an animal",run:async()=>{ensure(user);let id=rand(animals);replyx(`👣 TRACKING\nTarget found: ${animals[id].name}\n🎯 Hunting opportunity detected.`)}},
{name:"trap",aliases:["trapping"],description:"Set an animal trap",run:async()=>{ensure(user);let id=rand(animals);add(user,"raw_"+id,1);user.hunting.xp+=15;replyx(`🪤 TRAP SUCCESS\nCaught: ${animals[id].name}\n⭐ +15 Hunting XP`)}},
{name:"catch",aliases:["catchanimal"],description:"Catch a tracked animal",run:async()=>{ensure(user);let id=rand(animals);add(user,"raw_"+id,1);replyx(`🪤 Caught ${animals[id].name}!`) }},
{name:"cook",aliases:["cooking"],description:"Cook a hunted or caught item",run:async({args})=>{let q=args.join(" ").toLowerCase().replace(/ /g,"_");if(!q)return replyx("Usage: !cook <animal/fish>");let id=q.startsWith("raw_")?q:"raw_"+q;if((user.inventory[id]||0)<1)return replyx("❌ You don't have that ingredient.");rem(user,id,1);let food="cooked_"+q.replace(/^raw_/,"");add(user,food,1);replyx(`🍖 Cooked ${q.replace(/^raw_/,"")}.`)}},
{name:"camp",aliases:["camping"],description:"Set up a camp",run:async()=>{ensure(user);user.camp={level:user.camp?.level||1,active:true};replyx(`🏕️ CAMP SET\nLevel: ${user.camp.level}\n❤️ Rest and recover before another expedition.`)}},
{name:"explore",aliases:["exploration"],description:"Explore the frontier",run:async()=>{ensure(user);let events=["ore","fish","animal","treasure"];let e=rand(events);if(e==="ore"){let id=rand(ores);add(user,id,1);replyx(`🗺️ EXPEDITION\nYou discovered ${ores[id].name}!`)}else if(e==="fish"){let id=rand(fish);add(user,id,1);replyx(`🗺️ EXPEDITION\nYou found ${fish[id].name}!`)}else if(e==="animal"){let id=rand(animals);add(user,"raw_"+id,1);replyx(`🗺️ EXPEDITION\nYou encountered a ${animals[id].name}!`)}else{let r=10000+Math.floor(Math.random()*90000);user.wallet=(user.wallet||0)+r;replyx(`🗺️ TREASURE CHEST!\n💰 +$${fmt(r)}`)}}},
{name:"gather",aliases:["gathering"],description:"Gather wild resources",run:async()=>{ensure(user);let drops=["wood","herb","stone","fiber","mushroom"],id=rand(drops),qty=2+Math.floor(Math.random()*4);add(user,id,qty);replyx(`🌲 GATHERING\n${id} ×${qty}`)}},
{name:"resources",aliases:["resource"],description:"View gathered resources",run:async()=>{ensure(user);let ids=["wood","herb","stone","fiber","mushroom"];replyx(`🌿 RESOURCES\n${ids.map(x=>`${x}: ${user.inventory[x]||0}`).join("\n")}`)}},
{name:"miningrank",aliases:["minelb"],description:"Mining leaderboard",run:async()=>{let list=[...users.values()].map(u=>{ensure(u);return{name:u.name||u.uid,p:u.mining.level*100+u.mining.xp}}).sort((a,b)=>b.p-a.p).slice(0,10);replyx(`⛏️ MINING LEADERBOARD\n${list.map((x,i)=>`${i+1}. ${x.name} — ${fmt(x.p)}`).join("\n")}`)}},
{name:"huntingrank",aliases:["huntlb"],description:"Hunting leaderboard",run:async()=>{let list=[...users.values()].map(u=>{ensure(u);return{name:u.name||u.uid,p:u.hunting.level*100+u.hunting.xp}}).sort((a,b)=>b.p-a.p).slice(0,10);replyx(`🏹 HUNTING LEADERBOARD\n${list.map((x,i)=>`${i+1}. ${x.name} — ${fmt(x.p)}`).join("\n")}`)}},
{name:"frontier",aliases:["frontierinfo"],description:"View frontier stats",run:async()=>{ensure(user);replyx(`🌲 FRONTIER\n⛏️ Mining Lv.${user.mining.level} • ${user.mining.xp} XP\n🎣 Fishing Lv.${user.fishing.level} • ${user.fishing.xp} XP\n🏹 Hunting Lv.${user.hunting.level} • ${user.hunting.xp} XP`)}},
{name:"map",aliases:["frontiermap"],description:"View exploration map",run:async()=>replyx("🗺️ FRONTIER MAP\n⛏️ Crystal Mines\n🌲 Wild Forest\n🎣 Bluewater Lake\n🏔️ Dragon Peaks\n💎 Ancient Ruins")},
{name:"cave",aliases:["caves"],description:"Explore a dangerous cave",run:async()=>{ensure(user);let id=rand(ores),qty=2+Math.floor(Math.random()*5);add(user,id,qty);let danger=Math.random()<.2;if(danger)user.health=Math.max(1,(user.health||100)-15);replyx(`🕳️ CAVE EXPEDITION\n⛏️ ${ores[id].name} ×${qty}\n${danger?"⚠️ You were injured for 15 HP.":"✅ Safe expedition."}`)}},
{name:"resourcevalue",aliases:["resvalue"],description:"Calculate resource value",run:async()=>{ensure(user);let total=0;for(let [id,n] of Object.entries(user.inventory)){if(ores[id])total+=ores[id].value*n;if(fish[id])total+=fish[id].value*n;if(animals[id])total+=animals[id].value*n}replyx(`📊 FRONTIER RESOURCE VALUE\n💰 $${fmt(total)}`)}},
{name:"frontierquest",aliases:["frontierquests"],description:"Complete frontier quest",run:async()=>{ensure(user);let reward=10000+Math.floor(Math.random()*15000);user.wallet=(user.wallet||0)+reward;xp(user,50);replyx(`🗺️ FRONTIER QUEST COMPLETE!\n💰 +$${fmt(reward)}\n⭐ +50 XP`)}},
{name:"frontierlevel",aliases:["flevel"],description:"View frontier progression",run:async()=>{ensure(user);let total=user.mining.level+user.fishing.level+user.hunting.level;replyx(`🌲 FRONTIER LEVEL\nCombined Skill Level: ${total}\n⛏️ ${user.mining.level}\n🎣 ${user.fishing.level}\n🏹 ${user.hunting.level}`)}},
{name:"frontiergear",aliases:["gear"],description:"View frontier gear",run:async()=>replyx("🎒 FRONTIER GEAR\n⛏️ Pickaxe — Mining\n🎣 Fishing Rod — Fishing\n🏹 Hunting Bow — Hunting\n🥾 Explorer Boots — Exploration")},
{name:"frontierhelp",aliases:["frontiercommands"],description:"Frontier command help",run:async()=>replyx("⛏️ FRONTIER\n!mine • !ores • !dig • !excavate • !prospect • !smelt • !forge • !fish • !bait • !hunt • !tracking • !trap • !cook • !camp • !explore • !gather • !cave")}
];
return cmds;
};
