// commands/cmds_6.js
// ⚔️ BATTLECORE — iKON-BOT
module.exports=({api,event,user,reply,users,profile,fun})=>{
const replyx=t=>api.sendMessage(t,event.threadID,()=>{},event.messageID);
const xp=(u,n=5)=>{u.xp=(u.xp||0)+n;};
const ensure=u=>{u.skills=u.skills||{};u.inventory=u.inventory||{};u.battle=u.battle||{wins:0,losses:0,kills:0,damage:0,streak:0};u.stats=u.stats||{};u.equipment=u.equipment||{weapon:null,armor:null};u.energy=u.energy??100;u.maxEnergy=u.maxEnergy||100;u.health=u.health??100;u.maxHealth=u.maxHealth||100;u.level=u.level||1;u.prestige=u.prestige||0};
const fmt=n=>Number(n||0).toLocaleString();
const power=u=>{ensure(u);let w=u.equipment.weapon?100:0,a=u.equipment.armor?80:0;return Math.floor((u.level||1)*25+(u.xp||0)/20+(u.prestige||0)*250+w+a)};
const dmg=u=>Math.floor(20+(u.level||1)*4+(u.stats.strength||0)*3+(u.equipment.weapon?50:0)+Math.random()*25);
const target=uid=>users.get(uid);
const cmds=[
{name:"stats",aliases:["stat"],description:"View battle stats",run:async()=>{ensure(user);replyx(`⚔️ BATTLE STATS\n⭐ Level: ${user.level}\n🔥 Prestige: ${user.prestige}\n⚔️ Power: ${fmt(power(user))}\n❤️ HP: ${user.health}/${user.maxHealth}\n⚡ Energy: ${user.energy}/${user.maxEnergy}\n🏆 Wins: ${user.battle.wins}\n💀 Losses: ${user.battle.losses}`)}},
{name:"level",aliases:["lvl"],description:"View player level",run:async()=>{ensure(user);let need=user.level*500;replyx(`⭐ LEVEL ${user.level}\nXP: ${fmt(user.xp||0)}/${fmt(need)}\n⚔️ Power: ${fmt(power(user))}`)}},
{name:"xp",aliases:["experience"],description:"View experience",run:async()=>{ensure(user);replyx(`⭐ XP: ${fmt(user.xp||0)}\nNext Level: ${fmt(user.level*500)}`)}},
{name:"skills",aliases:["skill"],description:"View skills",run:async()=>{ensure(user);let s={strength:user.skills.strength||0,defense:user.skills.defense||0,speed:user.skills.speed||0,critical:user.skills.critical||0};replyx(`🧬 SKILLS\n💪 Strength: ${s.strength}\n🛡️ Defense: ${s.defense}\n⚡ Speed: ${s.speed}\n🎯 Critical: ${s.critical}`)}},
{name:"skilltree",aliases:["tree"],description:"View skill tree",run:async()=>replyx("🌳 SKILL TREE\n💪 Strength → Damage\n🛡️ Defense → Damage Reduction\n⚡ Speed → Dodge\n🎯 Critical → Critical Hit Chance\nUpgrade with !upgrade <skill>.")},
{name:"upgrade",aliases:["skillup"],description:"Upgrade a battle skill",run:async({args})=>{ensure(user);let s=String(args[0]||"").toLowerCase();if(!["strength","defense","speed","critical"].includes(s))return replyx("Usage: !upgrade strength|defense|speed|critical");let cost=5000+((user.skills[s]||0)*2500);if((user.wallet||0)<cost)return replyx(`💸 Need $${fmt(cost)}.`);user.wallet-=cost;user.skills[s]=(user.skills[s]||0)+1;replyx(`⬆️ ${s} upgraded to ${user.skills[s]}.\n💸 -$${fmt(cost)}`)}},
{name:"prestige",aliases:["prestigeup"],description:"Prestige after reaching level 100",run:async()=>{ensure(user);if(user.level<100)return replyx("🔒 Reach level 100 first.");user.prestige++;user.level=1;user.xp=0;user.maxHealth+=50;user.health=user.maxHealth;replyx(`🔥 PRESTIGE ${user.prestige}!\n❤️ Max HP increased.\n⭐ Level reset to 1.`)}},
{name:"rebirth",aliases:["reborn"],description:"Rebirth for permanent bonus",run:async()=>{ensure(user);if(user.level<50)return replyx("🔒 Reach level 50 first.");user.level=1;user.xp=0;user.battle.streak=0;user.skills.strength=(user.skills.strength||0)+5;replyx("♻️ REBIRTH COMPLETE!\n💪 Permanent Strength +5.")}},
{name:"battle",aliases:["fight"],description:"Battle a tagged opponent",run:async({args})=>{ensure(user);let uid=event.mentions&&Object.keys(event.mentions)[0];if(!uid)return replyx("⚔️ Tag an opponent.");let o=target(uid);if(!o)return replyx("❌ Opponent not found.");ensure(o);if(o.uid===user.uid)return replyx("❌ You cannot battle yourself.");if(user.energy<20)return replyx("⚡ Need 20 energy.");user.energy-=20;let a=power(user)+Math.floor(Math.random()*100),b=power(o)+Math.floor(Math.random()*100);if(a>=b){user.battle.wins++;user.battle.streak++;user.battle.kills++;user.battle.damage+=dmg(user);let reward=5000+Math.floor(b/2);user.wallet=(user.wallet||0)+reward;xp(user,50);replyx(`⚔️ BATTLE WON!\n🏆 ${user.name||"You"} defeated ${o.name||"Opponent"}.\n💰 +$${fmt(reward)}\n⭐ +50 XP\n🔥 Streak: ${user.battle.streak}`)}else{user.battle.losses++;user.battle.streak=0;o.battle.wins++;user.health=Math.max(1,user.health-20);replyx(`💀 BATTLE LOST!\n🏆 ${o.name||"Opponent"} won.\n❤️ -20 HP`)}}},
{name:"attack",aliases:["atk"],description:"Perform a basic attack",run:async({args})=>{ensure(user);let uid=event.mentions&&Object.keys(event.mentions)[0],o=uid&&target(uid);if(!o)return replyx("⚔️ Tag a target.");ensure(o);if(user.energy<10)return replyx("⚡ Need 10 energy.");user.energy-=10;let d=dmg(user);o.health=Math.max(0,o.health-d);replyx(`⚔️ ATTACK!\n💥 Damage: ${d}\n❤️ Target HP: ${o.health}/${o.maxHealth}`)}},
{name:"defend",aliases:["guard"],description:"Defend against attacks",run:async()=>{ensure(user);user.defending=true;user.energy=Math.min(user.maxEnergy,user.energy+5);replyx("🛡️ DEFENSE MODE ACTIVE!\nIncoming damage will be reduced.")}},
{name:"ultimate",aliases:["ult"],description:"Use ultimate attack",run:async({args})=>{ensure(user);let uid=event.mentions&&Object.keys(event.mentions)[0],o=uid&&target(uid);if(!o)return replyx("🔥 Tag a target.");ensure(o);if(user.energy<50)return replyx("⚡ Need 50 energy.");user.energy-=50;let d=Math.floor(dmg(user)*2.5);o.health=Math.max(0,o.health-d);replyx(`🔥 ULTIMATE!\n💥 ${d} damage dealt!\n❤️ Target HP: ${o.health}/${o.maxHealth}`)}},
{name:"pvp",aliases:["duel"],description:"Start a PvP fight",run:async({args})=>{ensure(user);let uid=event.mentions&&Object.keys(event.mentions)[0],o=uid&&target(uid);if(!o)return replyx("⚔️ Tag a PvP opponent.");ensure(o);let a=power(user)+Math.floor(Math.random()*50),b=power(o)+Math.floor(Math.random()*50);if(a>=b){user.battle.wins++;let r=10000;user.wallet=(user.wallet||0)+r;xp(user,75);replyx(`🏆 PVP VICTORY!\n⚔️ ${a} vs ${b}\n💰 +$${fmt(r)}\n⭐ +75 XP`)}else{o.battle.wins++;user.battle.losses++;replyx(`💀 PVP DEFEAT!\n⚔️ ${a} vs ${b}`)}}},
{name:"arena",aliases:["arena360"],description:"Enter the battle arena",run:async()=>{ensure(user);if(user.energy<25)return replyx("⚡ Need 25 energy.");user.energy-=25;let enemy=50+Math.floor(Math.random()*500),p=power(user);if(p>=enemy){let r=5000+enemy*10;user.wallet=(user.wallet||0)+r;user.battle.wins++;xp(user,60);replyx(`🏟️ ARENA VICTORY!\n⚔️ Your Power: ${p}\n👹 Enemy: ${enemy}\n💰 +$${fmt(r)}\n⭐ +60 XP`)}else{user.battle.losses++;replyx(`🏟️ ARENA DEFEAT!\n⚔️ Your Power: ${p}\n👹 Enemy: ${enemy}`)}}},
{name:"dungeon",aliases:["dungeons"],description:"Enter a dungeon",run:async()=>{ensure(user);if(user.energy<30)return replyx("⚡ Need 30 energy.");user.energy-=30;let floor=1+Math.floor(Math.random()*10),enemy=floor*150+Math.floor(Math.random()*300),p=power(user);if(p>=enemy){let r=floor*10000;user.wallet=(user.wallet||0)+r;xp(user,floor*30);replyx(`🏰 DUNGEON CLEARED!\nFloor: ${floor}\n⚔️ Power: ${p}\n💰 +$${fmt(r)}\n⭐ +${floor*30} XP`)}else{user.health=Math.max(1,user.health-15);replyx(`💀 DUNGEON FAILED!\nFloor: ${floor}\n❤️ -15 HP`)}}},
{name:"raid",aliases:["raids"],description:"Join a raid encounter",run:async()=>{ensure(user);if(user.energy<40)return replyx("⚡ Need 40 energy.");user.energy-=40;let boss=1000+Math.floor(Math.random()*3000),d=dmg(user)*3;user.battle.damage+=d;if(d>=boss){let r=25000+Math.floor(Math.random()*50000);user.wallet=(user.wallet||0)+r;xp(user,100);replyx(`⚔️ RAID CLEARED!\n💥 Damage: ${d}\n💰 +$${fmt(r)}\n⭐ +100 XP`)}else replyx(`⚔️ RAID ATTACK!\n💥 Damage: ${d}\n👹 Boss remaining: ${boss-d}`)}},
{name:"boss",aliases:["bossfight"],description:"Fight a world boss",run:async()=>{ensure(user);if(user.energy<50)return replyx("⚡ Need 50 energy.");user.energy-=50;let hp=5000+Math.floor(Math.random()*5000),d=dmg(user)*5;user.battle.damage+=d;if(d>=hp){let r=100000;user.wallet=(user.wallet||0)+r;user.battle.wins++;xp(user,200);replyx(`👑 WORLD BOSS DEFEATED!\n💥 ${d} damage\n💰 +$${fmt(r)}\n⭐ +200 XP`)}else replyx(`👹 BOSS HIT!\n💥 ${d} damage\n❤️ Boss HP: ${hp-d}`)}},
{name:"adventure",aliases:["adventuremode"],description:"Go on an adventure",run:async()=>{ensure(user);if(user.energy<20)return replyx("⚡ Need 20 energy.");user.energy-=20;let events=["treasure","enemy","merchant","nothing"],e=events[Math.floor(Math.random()*events.length)];if(e==="treasure"){let r=10000+Math.floor(Math.random()*40000);user.wallet=(user.wallet||0)+r;replyx(`🗺️ ADVENTURE!\n💎 Treasure found!\n💰 +$${fmt(r)}`)}else if(e==="enemy"){let d=dmg(user);user.battle.damage+=d;replyx(`👹 AMBUSH!\n💥 You dealt ${d} damage and escaped.`)}else if(e==="merchant")replyx("🧙 A mysterious merchant offered rare equipment.");else replyx("🌲 The adventure was quiet... for now.")}},
{name:"quest",aliases:["quests"],description:"View battle quests",run:async()=>{user.battleQuest=user.battleQuest||0;replyx(`📜 BATTLE QUEST\nProgress: ${user.battleQuest}\nComplete battles to earn rewards.`)}},
{name:"mission",aliases:["missions"],description:"Complete a combat mission",run:async()=>{ensure(user);let r=15000+user.level*500;user.wallet=(user.wallet||0)+r;user.battleQuest=(user.battleQuest||0)+1;xp(user,75);replyx(`⚔️ COMBAT MISSION COMPLETE!\n💰 +$${fmt(r)}\n⭐ +75 XP`)}},
{name:"equipment",aliases:["equip"],description:"View equipment",run:async()=>{ensure(user);replyx(`🎒 EQUIPMENT\n⚔️ Weapon: ${user.equipment.weapon||"None"}\n🛡️ Armor: ${user.equipment.armor||"None"}\n⚔️ Power: ${fmt(power(user))}`)}},
{name:"loadout",aliases:["setup"],description:"View battle loadout",run:async()=>{ensure(user);replyx(`⚔️ LOADOUT\nWeapon: ${user.equipment.weapon||"None"}\nArmor: ${user.equipment.armor||"None"}\nSkills: ${Object.keys(user.skills).length}\nPower: ${fmt(power(user))}`)}},
{name:"equipweapon",aliases:["weapon"],description:"Equip a weapon",run:async({args})=>{ensure(user);let q=args.join(" ").toLowerCase();let id=q.includes("iron")?"iron_sword":q.includes("steel")?"steel_sword":null;if(!id)return replyx("Usage: !equipweapon iron sword");if((user.inventory[id]||0)<1)return replyx("❌ You don't own that weapon.");user.equipment.weapon=id;replyx(`⚔️ Equipped ${id}.`)}},
{name:"equiparmor",aliases:["armor"],description:"Equip armor",run:async({args})=>{ensure(user);let q=args.join(" ").toLowerCase();let id=q.includes("steel")?"steel_armor":null;if(!id)return replyx("Usage: !equiparmor steel armor");if((user.inventory[id]||0)<1)return replyx("❌ You don't own that armor.");user.equipment.armor=id;replyx(`🛡️ Equipped ${id}.`)}},
{name:"heal",aliases:["battleheal"],description:"Restore battle health",run:async()=>{ensure(user);let amount=Math.floor(user.maxHealth*.4);user.health=Math.min(user.maxHealth,user.health+amount);replyx(`❤️ HEALED!\n+${amount} HP\n❤️ ${user.health}/${user.maxHealth}`)}},
{name:"energy",aliases:["stamina"],description:"Restore energy",run:async()=>{ensure(user);user.energy=Math.min(user.maxEnergy,user.energy+30);replyx(`⚡ Energy restored.\n⚡ ${user.energy}/${user.maxEnergy}`)}},
{name:"defense",aliases:["def"],description:"View defense rating",run:async()=>{ensure(user);let d=(user.skills.defense||0)*5+(user.equipment.armor?80:0);replyx(`🛡️ DEFENSE: ${d}`)}},
{name:"power",aliases:["battlepower"],description:"View combat power",run:async()=>replyx(`⚔️ COMBAT POWER: ${fmt(power(user))}`)},
{name:"critical",aliases:["crit"],description:"View critical chance",run:async()=>{ensure(user);let c=Math.min(75,5+(user.skills.critical||0)*3);replyx(`🎯 Critical Chance: ${c}%`)}},
{name:"combo",aliases:["combos"],description:"Build a combat combo",run:async()=>{ensure(user);user.combo=(user.combo||0)+1;let bonus=Math.min(100,user.combo*5);replyx(`🔥 COMBO x${user.combo}\n⚔️ Damage Bonus: +${bonus}%`) }},
{name:"rage",aliases:["fury"],description:"Activate rage mode",run:async()=>{ensure(user);user.rage=Date.now()+60000;replyx("😡 RAGE MODE ACTIVATED!\n⚔️ Damage increased for 60 seconds.")}},
{name:"mana",aliases:["magic"],description:"View magic energy",run:async()=>{ensure(user);user.mana=user.mana??100;replyx(`🔮 MANA: ${user.mana}/100`) }},
{name:"weaponrank",aliases:["weaponlb"],description:"Weapon combat ranking",run:async()=>{let list=[...users.values()].map(u=>({name:u.name||u.uid,p:power(u)})).sort((a,b)=>b.p-a.p).slice(0,10);replyx(`⚔️ COMBAT RANKING\n${list.map((x,i)=>`${i+1}. ${x.name} — ${fmt(x.p)}`).join("\n")}`)}},
{name:"bossrank",aliases:["bosslb"],description:"Boss damage leaderboard",run:async()=>{let list=[...users.values()].map(u=>{ensure(u);return{name:u.name||u.uid,d:u.battle.damage}}).sort((a,b)=>b.d-a.d).slice(0,10);replyx(`👹 BOSS DAMAGE LB\n${list.map((x,i)=>`${i+1}. ${x.name} — ${fmt(x.d)}`).join("\n")}`)}},
{name:"raidrank",aliases:["raidlb"],description:"Raid leaderboard",run:async()=>{let list=[...users.values()].map(u=>{ensure(u);return{name:u.name||u.uid,w:u.battle.wins}}).sort((a,b)=>b.w-a.w).slice(0,10);replyx(`⚔️ RAID RANKING\n${list.map((x,i)=>`${i+1}. ${x.name} — ${x.w} wins`).join("\n")}`)}},
{name:"arenaRank",aliases:["arenalb"],description:"Arena leaderboard",run:async()=>{let list=[...users.values()].map(u=>{ensure(u);return{name:u.name||u.uid,w:u.battle.wins}}).sort((a,b)=>b.w-a.w).slice(0,10);replyx(`🏟️ ARENA RANKING\n${list.map((x,i)=>`${i+1}. ${x.name} — ${x.w} wins`).join("\n")}`)}},
{name:"battlepass",aliases:["bpass"],description:"View battle pass",run:async()=>{ensure(user);let n=(user.battle.wins||0)+(user.battle.kills||0);replyx(`🎫 BATTLE PASS\nTier: ${Math.floor(n/10)+1}\nProgress: ${n%10}/10\n🏆 Wins: ${user.battle.wins}`)}},
{name:"bountyxp",aliases:["combatxp"],description:"View combat XP rewards",run:async()=>{ensure(user);let reward=500+(user.level*25);replyx(`🎯 COMBAT XP VALUE\nNext combat reward: ${fmt(reward)} XP`) }},
{name:"combat",aliases:["combatinfo"],description:"View complete combat profile",run:async()=>{ensure(user);replyx(`⚔️ COMBAT PROFILE\n⭐ Lv.${user.level} • 🔥 P${user.prestige}\n⚔️ Power: ${fmt(power(user))}\n❤️ HP: ${user.health}/${user.maxHealth}\n⚡ Energy: ${user.energy}/${user.maxEnergy}\n🏆 W:${user.battle.wins} • 💀 L:${user.battle.losses}\n🔥 Streak: ${user.battle.streak}`)}},
{name:"battlehelp",aliases:["battlecommands"],description:"Battle command help",run:async()=>replyx("⚔️ BATTLECORE\n!stats • !level • !skills • !upgrade • !prestige • !rebirth • !battle • !attack • !defend • !ultimate • !pvp • !arena • !dungeon • !raid • !boss • !adventure • !quest • !mission • !equipment • !loadout")}
];
return cmds;
};
