// commands/cmds_5.js
const C="cmds_5";
const c=(name,aliases,description,usage,hint,execute,permission="everyone",cooldown=0)=>({name,aliases,category:C,description,usage,hint,permission,cooldown,execute});
const r=(reply,msg)=>reply(`🌿 WILDCORE\n━━━━━━━━━━━━━━━━\n${msg}\n━━━━━━━━━━━━━━━━\n🌾 FARM • ⛏️ MINE • 🎣 FISH • 🏹 HUNT`);
const E=(title,msg)=>async({reply,args})=>r(reply,`${title}\n${msg.replace(/\{a\}/g,args.join(" ")||"Target")}`);

module.exports=[
c("farm",["farming"],"Farm crops","!farm","Plant and harvest crops",E("🌾 FARM","🌱 Your farm is ready!\n🌽 Crops: Wheat • Corn • Tomato\n💰 Harvest value calculated by farming engine.")),
c("plant",["plantseed"],"Plant seeds","!plant Wheat 5","Requires seeds + farm plot",async({reply,args})=>r(reply,`🌱 PLANTING\n🌾 Seed: ${args[0]||"Wheat"}\n🔢 Amount: ${args[1]||"1"}\n⏳ Growth timer started.`)),
c("harvest",["harvestfarm"],"Harvest crops","!harvest","Requires mature crops",E("🌾 HARVEST TIME","🌱 Mature crops collected!\n💰 Crop value + XP calculated.")),
c("watercrop",["waterfarm"],"Water crops","!watercrop","Improves growth",E("💧 FARM IRRIGATION","🌱 Crops watered!\n📈 Growth progress increased.")),
c("fertilize",["fertilizer"],"Fertilize crops","!fertilize","Improves yield",E("🧪 FERTILIZER APPLIED","🌱 Soil quality increased!\n🌾 Future yield boosted.")),
c("farmstatus",["farminfo"],"View farm status","!farmstatus","Shows plots and crops",E("📊 FARM STATUS","🌱 Plots: 8\n🌾 Growing: 5\n✅ Ready: 3\n💰 Estimated yield calculated.")),
c("farmupgrade",["upgradefarm"],"Upgrade farm","!farmupgrade","Unlocks more plots",E("🏡 FARM UPGRADE","🔨 Expansion requirements checked.\n🌾 More plots and higher yields can unlock.")),
c("greenhouse",["green"],"Manage greenhouse","!greenhouse","Protected crop farming",E("🏠 GREENHOUSE","🌱 Controlled farming active!\n☀️ Weather penalties reduced.\n💰 Premium crops unlocked by progression.")),
c("cropmarket",["farmmarket"],"View crop prices","!cropmarket","Market prices",E("📈 CROP MARKET","🌾 Wheat — $20K\n🌽 Corn — $35K\n🍅 Tomato — $50K\n🍓 Strawberry — $100K")),
c("sellcrop",["sellcrops"],"Sell harvested crops","!sellcrop Wheat 10","Requires inventory crops",async({reply,args})=>r(reply,`💰 CROP SALE\n🌾 ${args[0]||"Crop"}\n🔢 Amount: ${args[1]||"1"}\n🏦 Sale processed through economy engine.`)),
c("mine",["mining"],"Mine resources","!mine","Start mining",E("⛏️ MINING RUN","🪨 Mine shaft opened!\n⛏️ Possible ores: Stone • Copper • Iron • Gold • Diamond\n⭐ Rare drops depend on depth.")),
c("mine_deep",["deepmine"],"Mine deeper","!mine_deep","Higher risk/reward",E("⛏️ DEEP MINE","🌑 Depth increased!\n💎 Rare ore chance increased.\n⚠️ Energy and durability consumed.")),
c("mine_status",["minestatus"],"View mining status","!mine_status","Shows mining progress",E("📊 MINING STATUS","⛏️ Depth: 12\n⚡ Energy: 76%\n🔨 Tool durability: 84%\n💎 Rare-ore chance active.")),
c("mine_upgrade",["upgrademine"],"Upgrade mining gear","!mine_upgrade","Better tools unlock deeper zones",E("🔨 MINING UPGRADE","⛏️ Tool upgrade requirements checked.\n💎 Better tools improve yield and depth.")),
c("ore_sell",[],"Sell ores","!ore_sell Gold 5","Requires ores",async({reply,args})=>r(reply,`💰 ORE SALE\n💎 ${args[0]||"Ore"} × ${args[1]||"1"}\n📈 Market value calculated.`)),
c("ore_market",["oremarket"],"View ore prices","!ore_market","Mining market",E("💎 ORE MARKET","🪨 Stone — $1K\n🔩 Copper — $5K\n⚙️ Iron — $10K\n🥈 Silver — $25K\n🥇 Gold — $75K\n💎 Diamond — $500K")),
c("fish",["fishing"],"Go fishing","!fish","Catch random fish",E("🎣 FISHING TIME","🌊 Line cast!\n🐟 Sardine • Tropical Fish • Shark • Octopus • Whale\n🎁 Rare fish depend on fishing level.")),
c("fish_cast",["cast"],"Cast fishing line","!fish_cast","Start fishing attempt",E("🎣 CAST!\n🌊 Bobber is floating...\n⏳ Wait for the bite!")),
c("fish_catch",["catchfish"],"Catch hooked fish","!fish_catch","Requires active cast",E("🐟 HOOKED!\n🎣 Catch calculation activated.\n💰 Fish value + XP awarded.")),
c("fish_status",["fishstats"],"Fishing status","!fish_status","View fishing stats",E("📊 FISHING STATUS","🎣 Level: 18\n🐟 Catches: 248\n⭐ Rare chance: 12%\n🔥 Streak: 7")),
c("fish_market",["fishmarket"],"View fish prices","!fish_market","Fish market",E("🐟 FISH MARKET","🐟 Sardine — $8K\n🐠 Tropical Fish — $20K\n🐡 Pufferfish — $35K\n🦈 Shark — $250K\n🐋 Whale — $2M")),
c("sellfish",["fishsell"],"Sell fish","!sellfish Shark 2","Requires fish",async({reply,args})=>r(reply,`💰 FISH SALE\n🐟 ${args[0]||"Fish"} × ${args[1]||"1"}\n🏦 Value calculated by market engine.`)),
c("hunt",["hunting"],"Go hunting","!hunt","Track game animals",E("🏹 HUNTING RUN","🌲 Tracks detected!\n🐺 Wolf • 🦁 Lion • 🐯 Tiger • 🐻 Bear • 🦏 Rhino\n🎯 Success depends on hunting skill.")),
c("hunt_track",["track"],"Track animal","!hunt_track","Find animal tracks",E("🔎 TRACKING","🐾 Fresh tracks found!\n🎯 Target: {a}\n🏹 Prepare your next move.")),
c("hunt_capture",["capture"],"Capture/hunt game animal","!hunt_capture","Requires active hunt",E("🏹 HUNT ATTEMPT","🎯 Target: {a}\n🎲 Success calculated from hunting stats.")),
c("hunt_status",["huntstats"],"View hunting stats","!hunt_status","Hunting profile",E("📊 HUNTING STATUS","🏹 Level: 15\n🎯 Accuracy: 82%\n🐾 Animals tracked: 194\n🔥 Hunt streak: 6")),
c("hunt_market",["animalmarket"],"View animal values","!hunt_market","Game animal values",E("🐾 ANIMAL MARKET","🦌 Deer — $40K\n🐗 Boar — $60K\n🐺 Wolf — $120K\n🦊 Fox — $90K\n🦁 Lion — $500K")),
c("sellhunt",["sellanimal"],"Sell hunting loot","!sellhunt Wolf 1","Requires hunting loot",async({reply,args})=>r(reply,`💰 HUNT LOOT SALE\n🐾 ${args[0]||"Animal"} × ${args[1]||"1"}\n🏦 Market value calculated.`)),
c("wildstatus",["wildcore"],"View Wildcore stats","!wildstatus","All gathering stats",E("🌿 WILDCORE STATUS","🌾 Farming Lv.18\n⛏️ Mining Lv.16\n🎣 Fishing Lv.20\n🏹 Hunting Lv.15\n⭐ Total gathering XP loaded.")),
c("gather",["collect"],"Gather random resources","!gather","General resource collection",E("🌿 RESOURCE GATHERING","🌲 Exploring...\n🌾 Seeds\n🪨 Ores\n🍓 Food\n🐟 Fish\n🎁 Random resource roll activated.")),
c("forage",["foraging"],"Forage in wilderness","!forage","Find wild resources",E("🌲 FORAGING","🍓 Berries found!\n🌿 Herbs collected!\n🍄 Rare resource chance active.")),
c("woodcut",["chopwood"],"Gather wood","!woodcut","Collect crafting material",E("🪓 WOODCUTTING","🌲 Timber collected!\n📦 Wood added to inventory.\n⭐ +XP awarded.")),
c("herb",["herbs"],"Gather herbs","!herb","Alchemy resources",E("🌿 HERB RUN","🌱 Medicinal herbs collected!\n🧪 Useful for potions and crafting.")),
c("explore_wild",["explorewild"],"Explore wilderness","!explore_wild","Random encounters",E("🗺️ WILDERNESS EXPEDITION","🌲 Area explored!\n🎁 Possible finds: animals • seeds • ores • treasure.")),
c("weather",["wildweather"],"Check farming weather","!weather","Weather affects crops",E("🌦️ WILDCORE WEATHER","☀️ Sunny\n🌡️ Growth bonus active\n🌧️ Rain chance: 24%\n🌪️ Storm warning: low")),
c("season",["seasoninfo"],"View current season","!season","Seasonal modifiers",E("🍂 SEASON STATUS","🌾 Current season: Harvest\n📈 Crop yield bonus active.\n🐟 Fish tables updated.")),
c("farm_quest",["farmquest"],"Start farming quest","!farm_quest","Earn XP and rewards",E("📜 FARM QUEST","🌾 Objective: Harvest 20 crops\n⭐ Reward: XP + coins + seeds\n⏳ Quest progress started.")),
c("mine_quest",["minequest"],"Start mining quest","!mine_quest","Earn mining rewards",E("📜 MINING QUEST","⛏️ Objective: Collect 10 ores\n💎 Bonus reward for rare ore.")),
c("fish_quest",["fishquest"],"Start fishing quest","!fish_quest","Earn fishing rewards",E("📜 FISHING QUEST","🎣 Objective: Catch 10 fish\n⭐ Rare fish grant bonus XP.")),
c("hunt_quest",["huntquest"],"Start hunting quest","!hunt_quest","Earn hunting rewards",E("📜 HUNTING QUEST","🏹 Objective: Track 5 animals\n🎁 Complete for XP + loot.")),
c("gather_quest",["gatherquest"],"Gathering challenge","!gather_quest","Multi-resource quest",E("📜 GATHERING QUEST","🌿 Collect:\n🌾 5 Seeds\n🪨 5 Ores\n🍓 5 Wild Items\n⭐ Bonus XP on completion.")),
c("farm_streak",["farmstreak"],"View farming streak","!farm_streak","Streak rewards",E("🔥 FARM STREAK","🌾 Current streak: 8 days\n⭐ Bonus yield activated.")),
c("mine_streak",["minestreak"],"View mining streak","!mine_streak","Mining streak",E("🔥 MINING STREAK","⛏️ Current streak: 6 days\n💎 Rare-ore bonus active.")),
c("fish_streak",["fishstreak"],"View fishing streak","!fish_streak","Fishing streak",E("🔥 FISHING STREAK","🎣 Current streak: 7 days\n🐟 Rare catch bonus active.")),
c("hunt_streak",["huntstreak"],"View hunting streak","!hunt_streak","Hunting streak",E("🔥 HUNTING STREAK","🏹 Current streak: 5 days\n🎯 Accuracy bonus active.")),
c("seedshop",["seeds"],"View seed shop","!seedshop","Buy seeds",E("🌱 SEED SHOP","🌾 Wheat\n🌽 Corn\n🍅 Tomato\n🥕 Carrot\n🍓 Strawberry\n🍇 Grape\n🌻 Sunflower\n🌙 Moonflower\n✨ Divine Seed")),
c("buyseed",["buy_seed"],"Buy seeds","!buyseed Wheat 10","Requires money",async({reply,args})=>r(reply,`🌱 SEED PURCHASE\n🌾 ${args[0]||"Wheat"} × ${args[1]||"1"}\n💰 Price calculated by seed shop.`)),
c("resourcebox",["wildbox"],"Open resource box","!resourcebox","Random Wildcore loot",E("📦 RESOURCE BOX","🌾 Seeds\n🪨 Ores\n🐟 Fish\n🍓 Wild items\n🎁 One random reward selected.")),
c("gather_upgrade",["upgradegather"],"Upgrade gathering skill","!gather_upgrade","Improve all gathering",E("⬆️ GATHERING UPGRADE","🌿 Farming\n⛏️ Mining\n🎣 Fishing\n🏹 Hunting\n⭐ Upgrade requirements checked.")),
c("wildrank",["gatherrank"],"View Wildcore rank","!wildrank","Gathering leaderboard",E("🏆 WILDCORE RANK","🥇 Master Gatherer\n🥈 Wilderness King\n🥉 Resource Hunter\n📊 Ranking loaded from progression engine.")),
c("wild_event",["gatherevent"],"Join Wildcore event","!wild_event","Limited-time event",E("🌿 WILDCORE EVENT","🔥 Resource Rush activated!\n⏱️ Collect as much as possible before time expires.")),
c("discovery",["discover"],"Discover rare resource","!discovery","Exploration mechanic",E("🔮 DISCOVERY","🌌 Rare resource signal detected!\n🎁 Discovery roll activated.")),
c("treasure_hunt",["treasure"],"Search wilderness treasure","!treasure_hunt","Random treasure hunt",E("🗺️ TREASURE HUNT","❌ Empty spot...\n🔎 Searching deeper...\n💎 Treasure chance active.")),
c("camp",["wildcamp"],"Set wilderness camp","!camp","Rest during expeditions",E("🏕️ CAMP SET","🔥 Campfire lit!\n❤️ HP and ⚡ energy recovery enabled.")),
c("survival",["wildsurvival"],"Survive wilderness","!survival","Resource survival mode",E("🌲 WILDERNESS SURVIVAL","🏕️ Supplies checked.\n🍖 Food: ready\n💧 Water: ready\n🔥 Camp: active")),
c("resource_trade",["tradewild"],"Trade resources","!resource_trade @user","Reply/mention target",E("🔄 RESOURCE TRADE","👤 Target: {a}\n📦 Select seeds, ores, fish or loot to trade.")),
c("resource_convert",["convertresource"],"Convert resources","!resource_convert","Crafting conversion",E("⚙️ RESOURCE CONVERTER","🪨 Low-tier resources → higher-tier materials\n📦 Conversion rates loaded.")),
c("wildshop",["gatheringshop"],"Open Wildcore shop","!wildshop","Buy gathering supplies",E("🛒 WILDCORE SHOP","⛏️ Tools\n🎣 Fishing Gear\n🏹 Hunting Gear\n🌱 Seeds\n🧪 Fertilizers")),
c("toolrepair",["repairtool"],"Repair gathering tools","!toolrepair","Restore durability",E("🔧 TOOL REPAIR","⛏️ Pickaxe\n🪓 Axe\n🎣 Rod\n🏹 Bow\n🛠️ Durability restored after payment.")),
c("toolupgrade",["upgradetool"],"Upgrade gathering tool","!toolupgrade","Improves yield",E("🔨 TOOL UPGRADE","⛏️ Pickaxe\n🎣 Rod\n🏹 Bow\n🪓 Axe\n⭐ Upgrade level checked.")),
c("resource_inventory",["resources"],"View resources","!resource_inventory","Shows gathering inventory",E("🎒 RESOURCE BAG","🌾 Seeds: 42\n🪨 Ores: 31\n🐟 Fish: 18\n🌿 Herbs: 25\n🪵 Wood: 60")),
c("wildlog",["gatherlog"],"View gathering history","!wildlog","Recent activities",E("📜 WILDCORE LOG","🌾 Last: Harvest\n⛏️ Last mine: Gold\n🎣 Last catch: Shark\n🏹 Last hunt: Wolf")),
c("wildhelp",["wildcorehelp"],"Wildcore help","!wildhelp","Shows category commands",E("📖 WILDCORE HELP","🌾 !farm\n⛏️ !mine\n🎣 !fish\n🏹 !hunt\n🌿 !gather\n🛒 !wildshop\n📊 !wildstatus"))
];
