// commands/cmds_3.js
const C="cmds_3";
const c=(name,aliases,description,usage,hint,execute,permission="everyone",cooldown=0)=>({name,aliases,category:C,description,usage,hint,permission,cooldown,execute});
const r=(reply,msg)=>reply(`🐉 BEASTREALM\n━━━━━━━━━━━━━━━━\n${msg}\n━━━━━━━━━━━━━━━━\n🐾 Train smart. Feed hard. Evolve stronger.`);
const E=(title,msg)=>async({reply,args})=>r(reply,`${title}\n${msg.replace(/\{a\}/g,args.join(" ")||"Pet")}`);
module.exports=[
c("pets",["petlist","mypets"],"View your pets","!pets","Try !petinfo Dragon",E("🐾 YOUR PET KINGDOM","🐉 Dragon • Lv.18\n🦊 Fox • Lv.12\n🦁 Lion • Lv.9\n⭐ Use !petinfo <pet>")),
c("pet",["mypet"],"View equipped pet","!pet","Equip one with !equip <pet>",E("🐾 ACTIVE PET","🐉 Dragon\n❤️ HP: 920/1000\n⚡ Energy: 78/100\n⭐ Lv.18\n🔥 Legendary")),
c("petshop",["pet_shop"],"Open pet shop","!petshop","Browse before buying",E("🛒 PET SHOP","🐺 Wolf — $500K\n🦊 Fox — $750K\n🦁 Lion — $2M\n🐯 Tiger — $3M\n🐉 Dragon — $25M\n🦄 Unicorn — $50M\n💡 !buypet <name>")),
c("buypet",["buy_pet"],"Buy a pet","!buypet Dragon","Requires enough wallet money",E("🥚 PET PURCHASE","🐾 Requested: {a}\n💰 Price checked by shared economy/pet engine.")),
c("sellpet",["sell_pet"],"Sell a pet","!sellpet Dragon","Selling is permanent",E("💰 PET SALE","🐾 {a}\n⚠️ Permanent action; ownership checked.")),
c("rename",["renamepet"],"Rename a pet","!rename Dragon Blaze","Use pet + new name",async({reply,args})=>r(reply,`✏️ PET RENAMED\n🐾 ${args[0]||"Pet"} → ${args.slice(1).join(" ")||"New Name"}`)),
c("release",["releasepet"],"Release a pet","!release Dragon","Cannot be undone",E("🕊️ RELEASE REQUEST","🐾 {a}\n⚠️ Confirmation/ownership handled by pet engine.")),
c("equip",["equip_pet"],"Equip a pet","!equip Dragon","Only owned pets",E("⚔️ PET EQUIPPED","🐉 {a} is now active!\n🔥 Ready for battle.")),
c("unequip",["unequip_pet"],"Unequip active pet","!unequip","Pet remains owned",E("🐾 PET UNEQUIPPED","Your beast is resting safely.")),
c("favorite",["favpet"],"Favorite a pet","!favorite Dragon","Favorites appear first",E("❤️ FAVORITED","🐾 {a} added to favorites.")),
c("giftpet",["gift_pet"],"Gift a pet","!giftpet @user Dragon","Mention/reply target",async({reply,args})=>r(reply,`🎁 PET GIFT\n👤 Target: ${args[0]||"reply/mention"}\n🐾 Pet: ${args[1]||"unknown"}\n💌 Gift request created.`)),
c("inspect",["petinspect","petinfo"],"Inspect pet stats","!inspect Dragon","Full pet card",E("🔬 PET INSPECTION","🐾 {a}\n❤️ HP: 920\n⚔️ ATK: 180\n🛡️ DEF: 155\n💨 SPD: 130\n🧠 INT: 95\n⭐ XP: 4,820")),
c("petstats",["stats_pet"],"Show pet stats","!petstats Dragon","Battle stats",E("📊 PET STATS","🐾 {a}\n⚔️ Attack: 180\n🛡️ Defense: 155\n💨 Speed: 130\n🧠 Intelligence: 95\n❤️ Health: 920")),
c("insurance",["petinsurance"],"Insure pet","!insurance Dragon","Protect against loss",E("🛡️ PET INSURANCE","🐾 {a}\n💰 Premium scales with rarity + level.")),
c("salvage",["petsalvage"],"Salvage pet gear","!salvage <item>","Returns materials",E("♻️ SALVAGE","🔧 {a}\n📦 Materials returned by item engine.")),
c("feed",["petfeed"],"Feed pet","!feed Dragon Meat 2","Food affects vitals",async({reply,args})=>r(reply,`🍖 FEEDING TIME!\n🐾 ${args[0]||"Dragon"}\n🍗 ${args.slice(1).join(" ")||"Meat"}\n❤️ Hunger/health updated.`)),
c("water",["petwater"],"Give water","!water Dragon","Hydrate pet",E("💧 HYDRATION","🐾 {a}\n💧 Thirst restored.")),
c("heal",["petheal"],"Heal pet","!heal Dragon","Medicine may be required",E("💊 PET HEAL","🐾 {a}\n❤️ HP restored according to medicine.")),
c("revive",["petrevive"],"Revive fallen pet","!revive Dragon","Cost scales with rarity",E("💀➡️❤️ REVIVAL","🐾 {a}\n💰 Revival cost calculated from rarity + level + evolution.")),
c("sleep",["petsleep"],"Rest pet","!sleep Dragon","Rest restores energy",E("😴 PET REST","🐾 {a} is sleeping.\n⚡ Energy regeneration started.")),
c("wake",["petwake"],"Wake pet","!wake Dragon","Ends rest",E("☀️ GOOD MORNING!","🐾 {a} is awake and ready.")),
c("clean",["petclean"],"Clean pet","!clean Dragon","Improves happiness",E("🧼 PET SPA!","🐾 {a} is sparkling ✨\n❤️ Happiness increased.")),
c("pet_doctor",["petdoctor"],"Treat illness","!pet_doctor Dragon","Doctor cures status",E("🩺 PET DOCTOR","🐾 {a} examined.\n🧪 Treatment calculated by pet engine.")),
c("vitamin",["petvitamin"],"Give vitamins","!vitamin Dragon","Boosts stats",E("💊 VITAMIN BOOST","🐾 {a} received vitamins.\n⭐ Stats updated.")),
c("steroid",["petsteroid"],"Temporary power boost","!steroid Dragon","Battle-limited",E("💉 POWER BOOST","🐾 {a} received a temporary boost.\n⚠️ Battle rules apply.")),
c("diet",["petdiet"],"Change diet","!diet Dragon Meat","Changes growth modifiers",async({reply,args})=>r(reply,`🥩 DIET UPDATED\n🐾 ${args[0]||"Pet"}\n🍖 ${args.slice(1).join(" ")||"Balanced"} diet selected.`)),
c("vaccine",["petvaccine"],"Vaccinate pet","!vaccine Dragon","Prevents illness",E("💉 VACCINATION","🐾 {a} protected.")),
c("petbattle",["petduel"],"Battle another player","!petbattle @user","Mention/reply target",E("⚔️ PET BATTLE REQUEST","👤 Target: {a}\n🐾 Equipped pet enters combat.\n⏳ Target must ACCEPT.")),
c("pve_hunt",["petpve"],"Hunt NPC beasts","!pve_hunt","Earn XP and loot",E("🏹 PVE HUNT","🐾 Wild enemy detected!\n⚔️ Enemy stats generated.\n🎁 Victory grants XP/money/loot.")),
c("arena_rank",["petarena"],"Pet arena ranking","!arena_rank","View rating",E("🏆 PET ARENA","🥇 Legendary Beast\n🥈 Dragon Master\n🥉 Beast Hunter\n📈 Rating loaded from battle database.")),
c("skills",["petskills"],"View pet skills","!skills Dragon","Shows abilities",E("✨ PET SKILLS","🐾 {a}\n🔥 Inferno\n🛡️ Iron Hide\n💨 Shadow Dash\n💥 Dragon Rage")),
c("upgrade_skill",["skillupgrade"],"Upgrade skill","!upgrade_skill Dragon Inferno","Requires XP/items",async({reply,args})=>r(reply,`⬆️ SKILL UPGRADE\n🐾 ${args[0]||"Dragon"}\n✨ ${args.slice(1).join(" ")||"Skill"}\n📈 Requirements checked.`)),
c("defend",["petdefend"],"Defend in battle","!defend","Reduces damage",E("🛡️ DEFEND!","Your pet raises its guard.\n🛡️ Incoming damage reduced.")),
c("flee",["petflee"],"Flee battle","!flee","Speed-based chance",E("💨 FLEE ATTEMPT!","🏃 Escape calculation activated.")),
c("spectate",["petspectate"],"Watch battle","!spectate <battle>","No control",E("👀 SPECTATOR MODE","⚔️ Battle: {a}\n🍿 Sit back and watch!")),
c("challenge_bot",["petbot"],"Challenge NPC pet","!challenge_bot","Fight AI beast",E("🤖 PET BATTLE AI","👹 Enemy generated!\n⚔️ Difficulty selected from your level.")),
c("bet_battle",["petbet"],"Bet on battle","!bet_battle @user 100000","Explicit amount required",async({reply,args})=>r(reply,`💰 BATTLE BET\n👤 Target: ${args[0]||"target"}\n💵 Stake: ${args[1]||"amount"}\n🎲 Economy validation active.`)),
c("damage_matrix",["damagematrix"],"Damage chart","!damage_matrix","View strengths",E("📊 DAMAGE MATRIX","🔥 Fire > Nature\n❄️ Frost > Fire\n⚡ Thunder > Water\n🌿 Nature > Ocean\n🌑 Cosmic > common types")),
c("rage",["petrage"],"Activate rage","!rage","Requires rage meter",E("😡 RAGE MODE!","🔥 Rage activated.\n⚔️ Attack increased temporarily.")),
c("pet_breed",["petbreed","breed"],"Breed pets","!pet_breed Dragon Wolf","Compatible parents required",async({reply,args})=>r(reply,`🧬 BREEDING LAB\n🐾 Parent A: ${args[0]||"Pet"}\n🐾 Parent B: ${args[1]||"Pet"}\n🥚 Compatibility + genetics checked.`)),
c("pet_fusion",["fusion"],"Fuse pets","!pet_fusion Dragon Wolf","May consume both",E("🧬 FUSION CORE","🐉 {a}\n⚡ Fusion stats calculated from rarity + genes.")),
c("evolve",["petevolve"],"Evolve pet","!evolve Dragon","Level + stone may be required",E("✨ EVOLUTION","🐉 {a}\n⭐ Level, money and stone requirements checked.")),
c("mutate",["petmutate"],"Mutate traits","!mutate Dragon","Chance-based",E("🧪 MUTATION LAB","🐾 {a}\n🧬 Trait roll generated.")),
c("incubate",["petincubate"],"Incubate egg","!incubate Egg","Timed",E("🥚 INCUBATION","🥚 {a}\n⏳ Hatch timer started.")),
c("hatch",["pethatch"],"Hatch egg","!hatch","Ready egg required",E("🥚✨ HATCHING!","🐣 Shell cracking...\n🧬 Species + rarity determined by egg engine.")),
c("clone",["clonepet"],"Clone pet","!clone Dragon","Requires resources",E("🧬 CLONING","🐾 Source: {a}\n⚗️ DNA compatibility checked.")),
c("gene_splice",["genes"],"Splice genes","!gene_splice Dragon Wolf","Requires DNA",E("🧬 GENE SPLICE","🐾 {a}\n🔬 Trait compatibility scanning...")),
c("dna_bank",["dnabank"],"View DNA","!dna_bank","Manage samples",E("🧬 DNA BANK","🐉 Dragon DNA ×3\n🐺 Wolf DNA ×5\n🦄 Unicorn DNA ×1")),
c("de_evolve",["deevolve"],"Reverse evolution","!de_evolve Dragon","Rare item required",E("↩️ DE-EVOLUTION","🐾 {a}\n⚠️ Rare materials may be required.")),
c("ascend",["petascend"],"Ascend pet","!ascend Dragon","Endgame progression",E("🌌 ASCENSION","🐉 {a}\n⭐ Endgame requirements checked.")),
c("sterilize",["petsterilize"],"Sterilize pet","!sterilize Dragon","Stops breeding",E("🧬 STERILIZATION","🐾 {a}\n⚠️ Breeding capability affected.")),
c("buy_toy",["buytoy"],"Buy pet toy","!buy_toy Ball","Adds happiness",E("🧸 TOY PURCHASE","🎁 {a} added to inventory.")),
c("play",["petplay"],"Play with pet","!play Dragon","Raises happiness",E("🎾 PLAYTIME!","🐾 {a} had fun!\n❤️ Happiness increased.")),
c("buy_potion",["buypotion"],"Buy potion","!buy_potion Heal","Shop purchase",E("🧪 POTION SHOP","🧴 {a}\n💰 Price checked by item engine.")),
c("use_potion",["usepotion"],"Use potion","!use_potion Dragon Super Potion","Consumes item",async({reply,args})=>r(reply,`🧪 POTION USED\n🐾 ${args[0]||"Pet"}\n🧴 ${args.slice(1).join(" ")||"Potion"}\n✨ Effects applied.`)),
c("craft_item",["petcraft"],"Craft pet equipment","!craft_item <recipe>","Requires materials",E("🔨 PET CRAFTING","📜 Recipe: {a}\n📦 Materials checked.")),
c("item_vault",["petvault"],"View pet vault","!item_vault","Protected storage",E("📦 PET ITEM VAULT","🧪 Potions: 12\n🍖 Food: 28\n💎 Stones: 4\n🛡️ Gear: 7")),
c("collar",["petcollar"],"Equip collar","!collar Dragon Lucky Charm","Adds modifiers",async({reply,args})=>r(reply,`🔗 COLLAR SYSTEM\n🐾 ${args[0]||"Pet"}\n💎 ${args.slice(1).join(" ")||"Collar"} equipped.`)),
c("leash",["petleash"],"Equip leash","!leash Dragon","Pet utility",E("🦮 LEASH","🐾 {a} leash state updated.")),
c("market_list",["petlistmarket"],"List pet market","!market_list Dragon 5000000","Explicit price",async({reply,args})=>r(reply,`🏪 PET MARKET\n🐾 ${args[0]||"Pet"}\n💰 Price: ${args[1]||"amount"}\n📋 Listing validated.`)),
c("market_buy",["petmarketbuy"],"Buy market pet","!market_buy <listing>","Uses economy",E("🛒 MARKET PURCHASE","📋 Listing: {a}\n💰 Transaction checked.")),
c("cosmetics",["petcosmetics"],"View cosmetics","!cosmetics","Cosmetic items",E("✨ PET COSMETICS","👑 Crown\n🎀 Starlight Bow\n🎩 Circus Hat\n🏅 Victory Medal\n💎 Power Ring")),
c("scrap",["petscrap"],"Scrap equipment","!scrap <item>","Returns materials",E("♻️ SCRAP","🔧 {a}\n📦 Materials returned.")),
c("scavenge",["petscavenge"],"Send pet scavenging","!scavenge Dragon","Random resources",E("🔎 SCAVENGE MISSION","🐾 {a} sent out.\n🎁 Possible loot: food • ore • coins • items.")),
c("pet_job",["petjob"],"Assign pet job","!pet_job Dragon Guard","Generates rewards",async({reply,args})=>r(reply,`💼 PET JOB\n🐾 ${args[0]||"Pet"}\n💼 Job: ${args.slice(1).join(" ")||"Guard"}\n⭐ Reward calculated.`)),
c("guard_home",["petguard"],"Guard home","!guard_home Dragon","Property defense",E("🏠 GUARD DUTY","🐾 {a} assigned to home defense.")),
c("patrol",["petpatrol"],"Patrol territory","!patrol Dragon","Discover events",E("🚨 PATROL STARTED","🐾 {a} is patrolling.\n🔎 Random encounters enabled.")),
c("track_user",["pettrack"],"Track game target","!track_user @user","Game-only data",E("🐾 TRACKING QUEST","🎯 Target: {a}\n🔎 Only legitimate game-visible data.")),
c("smuggle_pet",["petsmuggle"],"Fictional pet mission","!smuggle_pet","Game-only mechanic",E("🚨 UNDERWORLD PET RUN","🐾 Fictional mission activated.\n💰 Reward/wanted changes calculated.")),
c("pet_expo",["petexpo"],"Enter pet exhibition","!pet_expo","Show collection",E("🏆 PET EXPO","✨ Collection displayed.\n📊 Rarity, level and cosmetics judged.")),
c("mine_crypto",["petcrypto"],"Pet mining event","!mine_crypto","Fictional currency",E("⛏️ PET CRYPTO MINE","🐾 Pet joined mining event.\n💎 Fictional rewards generated.")),
c("tax_collector",["pettax"],"Collect pet business tax","!tax_collector","Requires business",E("💰 PET TAX OFFICE","📋 Eligible businesses checked.\n🏦 Revenue routed to game balance.")),
c("spy",["petspy"],"Inspect game/group metadata","!spy","No private data",E("🕵️ PET INTEL","👥 Legitimate game/group metadata only.\n🔒 Private data never exposed.")),
c("rescue",["petrescue"],"Rescue lost pet","!rescue","Rescue mission",E("🚑 PET RESCUE","🐾 Lost-beast signal detected!\n🗺️ Rescue mission started.")),
c("safari",["petsafari"],"Go safari","!safari","Discover creatures",E("🌴 SAFARI!","🐾 Wild creatures detected.\n🎁 Rare encounters possible.")),
c("cyber_enhance",["cyberenhance"],"Cyber-enhance pet","!cyber_enhance Dragon","Tech resources",E("🤖 CYBER ENHANCEMENT","🐾 {a}\n⚙️ Technology requirements checked.")),
c("dna_sequence",["dnasequence"],"Analyze DNA","!dna_sequence Dragon","Genetic data",E("🔬 DNA SEQUENCE","🐾 {a}\n🧬 Trait map generated.")),
c("clone_vats",["clonevats"],"Manage clone vats","!clone_vats","Lab unlock required",E("🧪 CLONE VATS","🧬 Active vats: 2\n🥚 Incubating: 1\n🔒 Advanced vats require progression.")),
c("graft_trait",["grafttrait"],"Graft trait","!graft_trait Dragon Speed","Compatible DNA",async({reply,args})=>r(reply,`🧬 TRAIT GRAFT\n🐾 ${args[0]||"Pet"}\n✨ Trait: ${args.slice(1).join(" ")||"trait"}\n⚠️ Compatibility check.`)),
c("cryo_freeze",["cryofreeze"],"Freeze pet","!cryo_freeze Dragon","Pauses pet state",E("❄️ CRYO CHAMBER","🐾 {a} frozen.\n⏸️ Growth/decay paused.")),
c("bio_waste",["biowaste"],"Process lab waste","!bio_waste","Lab utility",E("☣️ BIO-WASTE CONTROL","🧪 Waste processed.\n♻️ Laboratory reputation maintained.")),
c("nano_heal",["nanoheal"],"Nano-heal pet","!nano_heal Dragon","Advanced healing",E("🤖 NANO-HEAL","🐾 {a}\n❤️ Advanced regeneration activated.")),
c("guild_register",["petguild"],"Register pet guild","!guild_register <name>","Guild system",E("🏰 PET GUILD REGISTER","👑 {a}\n📜 Guild requirements checked.")),
c("guild_raid",["petguildraid"],"Launch guild raid","!guild_raid","Requires guild",E("🏰⚔️ GUILD RAID","🐾 Squad assembled.\n🔥 Raid matchmaking started.")),
c("pet_pageant",["pageant"],"Enter pet pageant","!pet_pageant Dragon","Stats/cosmetics judged",E("👑 PET PAGEANT","🐾 {a} entered.\n✨ Rarity, cosmetics and stats judged.")),
c("trick_show",["trickshow"],"Perform tricks","!trick_show Dragon","Raises happiness",E("🎪 TRICK SHOW","🐾 {a} performs!\n😂 Crowd went CRAZY!\n❤️ Happiness increased.")),
c("licensing",["petlicense"],"Manage pet license","!licensing Dragon","Restricted pets",E("📜 PET LICENSE","🐾 {a}\n🪪 License requirements checked.")),
c("bounty_hound",["bountyhound"],"Send hound on bounty","!bounty_hound","Fictional bounty",E("🐕 BOUNTY HOUND","🎯 Game bounty selected.\n💰 Reward calculated after hunt.")),
c("smell_contraband",["smell"],"Detect game contraband","!smell_contraband","Uses detection stat",E("👃 CONTRABAND SCAN","🐕 Sniffing...\n🔎 Detection result generated.")),
c("pet_psych",["petpsych"],"Check temperament","!pet_psych Dragon","Behavior stats",E("🧠 PET PSYCHOLOGY","🐾 {a}\n❤️ Loyalty: 82%\n😈 Aggression: 41%\n😊 Happiness: 76%")),
c("loyalty_oath",["loyalty"],"Build loyalty","!loyalty_oath Dragon","Affects battle",E("🤝 LOYALTY OATH","🐾 {a}\n❤️ Loyalty increased.\n🛡️ High loyalty can unlock skills.")),
c("jealousy",["petjealousy"],"Check jealousy","!jealousy","Mood mechanic",E("😤 JEALOUSY CHECK","🐾 Your pets are watching...\n😂 Somebody wants more attention!")),
c("pack_order",["packorder"],"Manage pack","!pack_order","Assign positions",E("🐺 PACK ORDER","👑 Alpha: Dragon\n⚔️ Guardian: Wolf\n🦊 Scout: Fox")),
c("temperament",["pettemperament"],"View temperament","!temperament Dragon","Behavior modifier",E("🧠 TEMPERAMENT","🐾 {a}\n🔥 Aggressive\n💪 Brave\n❤️ Loyal")),
c("comfort",["petcomfort"],"Comfort pet","!comfort Dragon","Reduces sadness",E("❤️ COMFORT","🐾 {a}\n😊 Mood restored.\n🔥 Loyalty increased.")),
c("hibernation",["pethibernate"],"Hibernate pet","!hibernation Dragon","Preserves resources",E("❄️ HIBERNATION","🐾 {a} entered hibernation.\n⏸️ Resource drain reduced.")),
c("blackmarket_pet",["petblackmarket"],"Open fictional pet market","!blackmarket_pet","Rare game items",E("🕶️ BLACK MARKET","🐾 Rare pets\n🧬 Mutations\n💎 Evolution stones\n⚠️ Fictional in-game mechanics.")),
c("pet_ransom",["petransom"],"Pet ransom quest","!pet_ransom","Quest mechanic",E("🚨 PET RANSOM QUEST","🐾 Missing pet detected!\n🗺️ Quest objectives generated.")),
c("poach",["petpoach"],"Rare creature hunt","!poach","Fictional game mechanic",E("🏹 RARE CREATURE HUNT","🐾 Fictional game hunt started.\n⭐ Rarity controls encounters.")),
c("tax_evasion_pet",["petevasion"],"Fictional tax quest","!tax_evasion_pet","Game economy",E("💼 UNDERWORLD TAX QUEST","🎮 Fictional economy mission activated.\n💰 Outcome calculated by game rules.")),
c("scrap_gear",["scrapgear"],"Scrap pet gear","!scrap_gear <item>","Returns materials",E("🔧 GEAR SCRAP","📦 {a}\n♻️ Materials returned.")),
c("pet_loan",["petloan"],"Pet-care loan","!pet_loan 500000","Requires eligibility",E("🏦 PET CARE LOAN","💰 Requested: {a}\n📊 Credit + repayment rules checked."))
];
