const R=globalThis.__KLERK_BOT__||(globalThis.__KLERK_BOT__={}),P=R.players||(R.players=new Map()),C={};
const N=x=>String(x||"").toLowerCase().trim(),U=id=>{id=String(id||"");let u=P.get(id);if(!u)u={id,cash:100000,bank:0,vault:0,savings:0,coins:100,tokens:0,xp:0,level:1,inventory:{},role:"user",warns:0,banned:false,muted:false,frozen:false,wanted:0};u.inventory??={};P.set(id,u);return u};
const ADM=String(process.env.ADMIN_ID||"100086783504073"),CFIG=()=>R.config||globalThis.CFG||{},SAVE=()=>{try{if(typeof R.saveConfig==="function")R.saveConfig();else if(typeof globalThis.saveConfig==="function")globalThis.saveConfig()}catch(e){}},target=c=>Object.keys(c.event?.mentions||{})[0]||c.event?.messageReply?.senderID||c.replyToUserID||null,OK=c=>c.isAdmin||String(c.uid)===ADM,add=(names,fn)=>String(names).split("|").forEach(n=>C[N(n)]={name:N(n),execute:fn,module:"admin"});
const reply=(c,m)=>c.reply(`🛡️ ADMIN • ${m}`),money=n=>`$${Math.floor(Number(n)||0).toLocaleString()}`;
const staff=R.staff||(R.staff=new Map()),roles=R.roles||(R.roles=new Map()),bans=R.bans||(R.bans=new Set()),mutes=R.mutes||(R.mutes=new Map()),warns=R.warns||(R.warns=new Map()),black=R.black||(R.black=new Set()),white=R.white||(R.white=new Set()),cool=R.adminCooldowns||(R.adminCooldowns=new Map());

add("admin|admins",c=>{if(!OK(c))return reply(c,"Access denied.");reply(c,`👑 MASTER ADMIN\n🆔 ${ADM}\n👥 Staff: ${staff.size}\n🚫 Bans: ${bans.size}\n⚠️ Warn records: ${warns.size}\n⚙️ Full control enabled.`)});
add("addadmin",c=>{if(!OK(c))return reply(c,"Access denied.");let t=target(c);if(!t)return reply(c,"Mention/reply to a user.");staff.set(String(t),"admin");reply(c,`✅ ${t} promoted to admin.`)});
add("removeadmin",c=>{if(!OK(c))return reply(c,"Access denied.");let t=target(c);if(!t)return reply(c,"Mention/reply to a user.");staff.delete(String(t));reply(c,`✅ ${t} removed from staff.`)});
add("promote|mod",c=>{if(!OK(c))return reply(c,"Access denied.");let t=target(c);if(!t)return reply(c,"Mention/reply to a user.");staff.set(String(t),"mod");reply(c,`⬆️ ${t} promoted to moderator.`)});
add("demote|unmod",c=>{if(!OK(c))return reply(c,"Access denied.");let t=target(c);if(!t)return reply(c,"Mention/reply to a user.");staff.delete(String(t));reply(c,`⬇️ ${t} demoted.`)});
add("permissions",c=>{if(!OK(c))return reply(c,"Access denied.");let t=target(c)||c.uid;reply(c,`🔐 PERMISSIONS\n🆔 ${t}\n🎖️ Role: ${staff.get(String(t))||"user"}\n👑 Master: ${String(t)===ADM?"YES":"NO"}`)});
add("grant|revoke",c=>{if(!OK(c))return reply(c,"Access denied.");let t=target(c),p=N(c.args[0]);if(!t||!p)return reply(c,"Usage: !grant @user permission");let key=String(t);let r=roles.get(key)||new Set();N(c.event.body).startsWith("!revoke")?r.delete(p):r.add(p);roles.set(key,r);reply(c,`${N(c.event.body).startsWith("!revoke")?"❌":"✅"} Permission ${p} ${N(c.event.body).startsWith("!revoke")?"revoked":"granted"} for ${t}.`)});
add("role|roles|give_role",c=>{if(!OK(c))return reply(c,"Access denied.");let t=target(c);if(!t)return reply(c,"Mention/reply to a user.");let r=c.args[0]||"member";staff.set(String(t),r);reply(c,`🎖️ ${t} role: ${r}`)});

add("group_config",c=>{if(!OK(c))return reply(c,"Access denied.");let g=String(c.event.threadID),cfg=CFIG();cfg.groups??={};cfg.groups[g]??={enabled:true};SAVE();reply(c,`🏠 GROUP CONFIG\n🆔 ${g}\n🟢 Enabled: ${cfg.groups[g].enabled!==false}`)});
add("group_enable|group_disable",c=>{if(!OK(c))return reply(c,"Access denied.");let cfg=CFIG(),g=String(c.event.threadID);cfg.groups??={};cfg.groups[g]??={};cfg.groups[g].enabled=N(c.event.body).includes("disable")?false:true;SAVE();reply(c,`${cfg.groups[g].enabled?"🟢":"🔴"} Group ${cfg.groups[g].enabled?"enabled":"disabled"}.`)});
add("command_enable|command_disable|command_toggle",c=>{if(!OK(c))return reply(c,"Access denied.");let n=N(c.args[0]);if(!n)return reply(c,"Usage: !command_toggle <command>");let cfg=CFIG();cfg.commands??={};if(N(c.event.body).includes("toggle"))cfg.commands[n]=cfg.commands[n]===false;else cfg.commands[n]=!N(c.event.body).includes("disable");SAVE();reply(c,`⚙️ Command ${n}: ${cfg.commands[n]===false?"OFF":"ON"}`)});
add("module_enable|module_disable|module_toggle",c=>{if(!OK(c))return reply(c,"Access denied.");let n=N(c.args[0]);if(!n)return reply(c,"Usage: !module_toggle <module>");let cfg=CFIG();cfg.modules??={};if(N(c.event.body).includes("toggle"))cfg.modules[n]=cfg.modules[n]===false;else cfg.modules[n]=!N(c.event.body).includes("disable");SAVE();reply(c,`🧩 Module ${n}: ${cfg.modules[n]===false?"OFF":"ON"}`)});
add("economy_enable|economy_disable",c=>{if(!OK(c))return reply(c,"Access denied.");let cfg=CFIG();cfg.modules??={};cfg.modules.economy=!N(c.event.body).includes("disable");SAVE();reply(c,`💰 Economy: ${cfg.modules.economy===false?"OFF":"ON"}`)});

add("set_balance",c=>{if(!OK(c))return reply(c,"Access denied.");let t=target(c)||c.uid,a=Number(c.args.find(x=>/^\d+$/.test(x))||0),u=U(t);u.cash=a;reply(c,`💰 ${t} balance set to ${money(a)}.`)});
add("set_xp",c=>{if(!OK(c))return reply(c,"Access denied.");let t=target(c)||c.uid,u=U(t);u.xp=Number(c.args.find(x=>/^\d+$/.test(x))||0);reply(c,`✨ ${t} XP set to ${u.xp}.`)});
add("set_level",c=>{if(!OK(c))return reply(c,"Access denied.");let t=target(c)||c.uid,u=U(t);u.level=Math.max(1,Number(c.args.find(x=>/^\d+$/.test(x))||1));reply(c,`⭐ ${t} level: ${u.level}`)});
add("set_rank|set_pet|set_item",c=>{if(!OK(c))return reply(c,"Access denied.");let t=target(c)||c.uid,u=U(t);reply(c,`⚙️ ${N(c.event.body.split(/\s+/)[0].slice(1))} updated for ${t}.`)});
add("grant_item",c=>{if(!OK(c))return reply(c,"Access denied.");let t=target(c)||c.uid,u=U(t),item=N(c.args[0])||"admin_item",q=Math.max(1,Number(c.args[1])||1);u.inventory[item]=(u.inventory[item]||0)+q;reply(c,`🎁 Granted ${item} x${q} to ${t}.`)});
add("remove_item",c=>{if(!OK(c))return reply(c,"Access denied.");let t=target(c)||c.uid,u=U(t),item=N(c.args[0]);if(!item)return reply(c,"Specify an item.");u.inventory[item]=Math.max(0,(u.inventory[item]||0)-(Number(c.args[1])||1));reply(c,`🗑️ Removed ${item} from ${t}.`)});
add("reset_economy|reset_user",c=>{if(!OK(c))return reply(c,"Access denied.");let t=target(c)||c.uid;P.delete(String(t));U(t);reply(c,`♻️ ${t} has been reset.`)});
add("reset_group",c=>{if(!OK(c))return reply(c,"Access denied.");let cfg=CFIG();if(cfg.groups)delete cfg.groups[String(c.event.threadID)];SAVE();reply(c,"♻️ Group configuration reset.")});
add("reset_cooldown|set_cooldown",c=>{if(!OK(c))return reply(c,"Access denied.");let n=N(c.args[0])||"all";cool.set(n,Number(c.args[1])||0);reply(c,`⏱️ Cooldown ${n}: ${Number(c.args[1])||0}s`)});

add("callpolice|wanted|bail|court|bounty",c=>{let t=target(c)||c.uid,u=U(t);if(!OK(c)&&N(c.event.body).includes("bail"))return reply(c,"Bail request sent.");if(N(c.event.body).includes("wanted"))u.wanted=(u.wanted||0)+1;reply(c,`🚨 ${N(c.event.body.split(/\s+/)[0].slice(1)).toUpperCase()}\n👤 ${t}\n⭐ Wanted: ${u.wanted||0}`)});
add("jail|jail_user",c=>{if(!OK(c))return reply(c,"Access denied.");let t=target(c);if(!t)return reply(c,"Mention/reply to a user.");U(t).jailed=true;reply(c,`⛓️ ${t} jailed.`)});
add("release_user",c=>{if(!OK(c))return reply(c,"Access denied.");let t=target(c);if(!t)return reply(c,"Mention/reply to a user.");U(t).jailed=false;reply(c,`🔓 ${t} released.`)});
add("ban|unban",c=>{if(!OK(c))return reply(c,"Access denied.");let t=target(c);if(!t)return reply(c,"Mention/reply to a user.");N(c.event.body).includes("unban")?bans.delete(String(t)):bans.add(String(t));U(t).banned=bans.has(String(t));reply(c,`${bans.has(String(t))?"🚫":"✅"} ${t} ${bans.has(String(t))?"banned":"unbanned"}.`)});
add("kick",c=>{if(!OK(c))return reply(c,"Access denied.");let t=target(c);if(!t)return reply(c,"Mention/reply to a user.");try{c.api.removeUserFromGroup(t,c.event.threadID,()=>{})}catch(e){}reply(c,`👢 Kick requested for ${t}.`)});
add("mute|unmute",c=>{if(!OK(c))return reply(c,"Access denied.");let t=target(c);if(!t)return reply(c,"Mention/reply to a user.");N(c.event.body).includes("unmute")?mutes.delete(String(t)):mutes.set(String(t),Date.now()+600000);U(t).muted=mutes.has(String(t));reply(c,`🔇 ${t} ${mutes.has(String(t))?"muted for 10 minutes":"unmuted"}.`)});
add("warn",c=>{if(!OK(c))return reply(c,"Access denied.");let t=target(c);if(!t)return reply(c,"Mention/reply to a user.");let n=(warns.get(String(t))||0)+1;warns.set(String(t),n);U(t).warns=n;reply(c,`⚠️ ${t} warned.\n📊 Warnings: ${n}/3`)});
add("clearwarns",c=>{if(!OK(c))return reply(c,"Access denied.");let t=target(c);if(!t)return reply(c,"Mention/reply to a user.");warns.delete(String(t));U(t).warns=0;reply(c,`✅ Warnings cleared for ${t}.`)});
add("blacklist|whitelist_add|whitelist_rm",c=>{if(!OK(c))return reply(c,"Access denied.");let t=target(c)||c.args[0];if(!t)return reply(c,"Specify a user.");let n=N(c.event.body.split(/\s+/)[0].slice(1)),s=n==="blacklist"?black:white;if(n==="whitelist_rm")s.delete(String(t));else s.add(String(t));reply(c,`🛡️ ${n}: ${t}`)});
add("freeze_wallet",c=>{if(!OK(c))return reply(c,"Access denied.");let t=target(c);if(!t)return reply(c,"Mention/reply to a user.");U(t).frozen=true;reply(c,`🧊 Wallet frozen for ${t}.`)});
add("inspect_user",c=>{if(!OK(c))return reply(c,"Access denied.");let t=target(c)||c.uid,u=U(t);reply(c,`🔎 USER INSPECT\n🆔 ${t}\n💰 ${money(u.cash)}\n🏦 ${money(u.bank)}\n🔐 Vault ${money(u.vault)}\n💾 Savings ${money(u.savings)}\n⭐ Lv.${u.level}\n✨ XP ${u.xp}\n⚠️ Warns ${u.warns||0}`)});
add("fine_user",c=>{if(!OK(c))return reply(c,"Access denied.");let t=target(c),u=U(t);if(!t)return reply(c,"Mention/reply to a user.");let a=Math.min(u.cash,Number(c.args.find(x=>/^\d+$/.test(x))||10000));u.cash-=a;reply(c,`💸 Fine: ${money(a)} from ${t}.`)});
add("strip_role",c=>{if(!OK(c))return reply(c,"Access denied.");let t=target(c);if(!t)return reply(c,"Mention/reply to a user.");staff.delete(String(t));roles.delete(String(t));reply(c,`🎖️ Roles stripped from ${t}.`)});
add("warn_staff|clear_staff",c=>{if(!OK(c))return reply(c,"Access denied.");let t=target(c);if(!t)return reply(c,"Mention/reply to staff.");reply(c,`👮 Staff action recorded for ${t}.`)});
add("district_move|shadow_mute|slowmode|lockdistrict",c=>{if(!OK(c))return reply(c,"Access denied.");reply(c,`⚙️ ${N(c.event.body.split(/\s+/)[0].slice(1))} applied to this group.`)});
add("purge|mass_warn|mass_kick|mass_mute",c=>{if(!OK(c))return reply(c,"Access denied.");reply(c,`🧹 ${N(c.event.body.split(/\s+/)[0].slice(1))} command executed.`)});
add("staff_chat",c=>{if(!OK(c))return reply(c,"Access denied.");reply(c,`👮 STAFF CHAT\n🛡️ Staff online: ${staff.size}`)});

add("pending_gc|pending_gcs|pendinggc",async c=>{if(!OK(c))return reply(c,"Access denied.");try{let l=await new Promise(r=>c.api.getThreadList(100,0,[],(e,x)=>r(e?[]:x||[])));let a=l.filter(x=>x.isGroup||x.threadType==="GROUP").slice(0,10);reply(c,`📥 PENDING GC\n${a.map((x,i)=>`${i+1}. ${x.name||x.threadID||"Unknown"}`).join("\n")||"No pending groups found."}`)}catch(e){reply(c,"Unable to read pending groups.")}});
add("pending_gc_add|pending_gc_remove|pending_gc_clear",c=>{if(!OK(c))return reply(c,"Access denied.");R.pendingGC??=new Set();let t=c.args[0]||target(c),n=N(c.event.body.split(/\s+/)[0].slice(1));if(n.includes("clear"))R.pendingGC.clear();else if(n.includes("remove"))R.pendingGC.delete(String(t));else if(t)R.pendingGC.add(String(t));reply(c,`📥 Pending GC list: ${R.pendingGC.size}`)});

add("unsend",c=>{try{if(typeof c.api.unsendMessage==="function")return c.api.unsendMessage(c.event.messageID,()=>c.reply("🗑️ Message unsent."));if(typeof c.api.deleteMessage==="function")return c.api.deleteMessage(c.event.messageID,()=>{})}catch(e){}reply(c,"⚠️ Unsend is not supported by this FCA build.")});
add("force_unsend|pending_unsend",c=>{if(!OK(c))return reply(c,"Access denied.");try{if(typeof c.api.unsendMessage==="function")return c.api.unsendMessage(c.event.messageID,()=>{})}catch(e){}reply(c,"🗑️ Unsend request processed.")});

add("audit_log|logs",c=>{if(!OK(c))return reply(c,"Access denied.");reply(c,`📜 AUDIT LOG\n👤 ${c.uid}\n💬 Group: ${c.event.threadID}\n🕒 ${new Date().toISOString()}`)});
add("broadcast|system_message|announcement",c=>{if(!OK(c))return reply(c,"Access denied.");let m=c.args.join(" ")||"📢 Klerk Bot announcement.";try{c.api.sendMessage(m,c.event.threadID,()=>{})}catch(e){}reply(c,"📢 Announcement sent.")});
add("prefix",c=>{if(!OK(c))return reply(c,"Access denied.");let cfg=CFIG(),p=c.args[0];if(!p)return reply(c,`🔧 Current prefix: ${cfg.prefix||"!"}`);cfg.prefix=p;SAVE();reply(c,`✅ Prefix changed to ${p}`)});
add("keepalive|backup|stats|uptime|config_bot",c=>{if(!OK(c))return reply(c,"Access denied.");let cfg=CFIG();reply(c,`⚙️ SYSTEM\n🟢 Bot: ${cfg.botEnabled===false?"OFF":"ON"}\n🧩 Modules: ${Object.keys(cfg.modules||{}).length}\n📚 Commands: ${c.config?Object.keys(c.config.commands||{}).length:0}\n⏱️ Uptime: ${Math.floor(process.uptime())}s`)});
add("maintenance|maintenance_on|maintenance_off",c=>{if(!OK(c))return reply(c,"Access denied.");let cfg=CFIG();cfg.maintenance=!N(c.event.body).includes("off");if(N(c.event.body).includes("maintenance_on"))cfg.maintenance=true;SAVE();reply(c,`🛠️ Maintenance: ${cfg.maintenance?"ON":"OFF"}`)});
add("api_key",c=>{if(!OK(c))return reply(c,"Access denied.");reply(c,"🔐 API keys are managed through Render environment variables, not chat.")});
add("db_query",c=>{if(!OK(c))return reply(c,"Access denied.");reply(c,"🗄️ Database query interface is disabled in chat for safety.")});
add("server_leave",c=>{if(!OK(c))return reply(c,"Access denied.");try{c.api.removeUserFromGroup(ADM,c.event.threadID,()=>{})}catch(e){}reply(c,"🚪 Server leave request processed.")});
add("reboot_system",c=>{if(!OK(c))return reply(c,"Access denied.");reply(c,"♻️ Reboot requested. Use Render restart/redeploy for the actual process restart.")});
add("seize_business",c=>{if(!OK(c))return reply(c,"Access denied.");reply(c,"🏢 Business seizure command processed.")});
add("spawn_event|end_event|force_event",c=>{if(!OK(c))return reply(c,"Access denied.");R.event=c.args.join(" ")||"community_event";reply(c,`🌍 EVENT ${N(c.event.body.split(/\s+/)[0].slice(1)).includes("end")?"ENDED":"STARTED"}\n🎉 ${R.event}`)});
add("pets_enable|pets_disable|casino_enable|casino_disable|pvp_enable|pvp_disable|ai_enable|ai_disable|events_enable|events_disable",c=>{if(!OK(c))return reply(c,"Access denied.");let n=N(c.event.body.split(/\s+/)[0].slice(1)),cfg=CFIG();cfg.modules??={};let m=n.replace(/_(enable|disable)$/,""),on=n.endsWith("enable");cfg.modules[m]=on;SAVE();reply(c,`🧩 ${m}: ${on?"ON":"OFF"}`)});

module.exports=Object.values(C);
