// commands/cmds_12.js
// 👑 KLERKCORE + 🛠️ SYSTEMHUB — iKON-BOT
module.exports=({api,event,user,reply,users,profile,fun})=>{
const r=t=>api.sendMessage(t,event.threadID,()=>{},event.messageID),uid=String(event.senderID||user.uid),admins=String(process.env.ADMIN_UIDS||"").split(",").map(x=>x.trim()).filter(Boolean),isAdmin=admins.includes(uid)||user.admin===true;
const deny=()=>r("⛔ Admin permission required.");
const cmds=[
{name:"admin",aliases:["owner","sudo"],run:async()=>isAdmin?r("👑 KLERKCORE\nAccess: GLOBAL ADMIN\n🛡️ Full bot controls enabled."):deny()},
{name:"settings",aliases:["config"],run:async()=>isAdmin?r(`⚙️ BOT SETTINGS\nPrefix: ${process.env.PREFIX||"!"}\nReplies: ON\nAutoReact: ON\nCooldown: ON\nAntiSpam: ON\nModules: ACTIVE`):deny()},
{name:"enable",aliases:["on"],run:async({args})=>{if(!isAdmin)return deny();let x=args[0]||"bot";r(`🟢 ENABLED: ${x}`)}},
{name:"disable",aliases:["off"],run:async({args})=>{if(!isAdmin)return deny();let x=args[0]||"bot";r(`🔴 DISABLED: ${x}`)}},
{name:"maintenance",aliases:["maint"],run:async({args})=>{if(!isAdmin)return deny();let s=(args[0]||"on").toLowerCase();r(s==="off"?"🟢 Maintenance disabled.":"🔧 Maintenance mode enabled.")}},
{name:"broadcast",aliases:["bc"],run:async({args})=>{if(!isAdmin)return deny();let msg=args.join(" ");if(!msg)return r("📢 Use !broadcast <message>.");let n=0;for(const [tid,g] of (global.groups||new Map())){try{api.sendMessage(`📢 iKON-BOT BROADCAST\n\n${msg}`,tid,()=>{});n++}catch{}}r(`📢 Broadcast sent to ${n} groups.`)}},
{name:"reload",aliases:["restartcmds"],run:async()=>isAdmin?r("🔄 Command reload requested. The central engine will reload command modules."):deny()},
{name:"logs",aliases:["log"],run:async()=>isAdmin?r("📜 SYSTEM LOGS\nUse the Render/server console for full runtime logs.\n🟢 Command engine active."):deny()},
{name:"stats",aliases:["botstats"],run:async()=>r(`📊 iKON-BOT STATS\n👥 Users: ${users.size}\n👑 Admin: ${isAdmin?"YES":"NO"}\n⚡ Prefix: ${process.env.PREFIX||"!"}\n🟢 Engine: ONLINE`)},
{name:"pending",aliases:["pendinggc"],run:async()=>isAdmin?r("📥 PENDING GROUPS\nPending group approval is controlled by the central group registry."):deny()},
{name:"approve",aliases:["approvegc"],run:async({args})=>{if(!isAdmin)return deny();r(`✅ Group approval requested${args[0]?` for ${args[0]}`:""}.`)}},
{name:"reject",aliases:["rejectgc"],run:async({args})=>{if(!isAdmin)return deny();r(`❌ Group rejection requested${args[0]?` for ${args[0]}`:""}.`)}},
{name:"warn",aliases:["warning"],run:async({args})=>{if(!isAdmin)return deny();let u=users.get(String(args[0]||""));if(!u)return r("❌ User not found.");u.warnings=(u.warnings||0)+1;r(`⚠️ ${u.name||u.uid} warned.\nWarnings: ${u.warnings}`)}},
{name:"warnings",aliases:["warns"],run:async({args})=>{let u=users.get(String(args[0]||uid))||user;r(`⚠️ ${u.name||u.uid}\nWarnings: ${u.warnings||0}`)}},
{name:"kick",aliases:["remove"],run:async({args})=>{if(!isAdmin)return deny();let id=String(args[0]||"");if(!id)return r("❌ Use !kick <uid>.");try{api.removeUserFromGroup(id,event.threadID,()=>{});r(`👢 User ${id} removed from the group.`)}catch{r("❌ Kick failed. Bot may not have admin permission.")}}},
{name:"ban",aliases:["blacklist"],run:async({args})=>{if(!isAdmin)return deny();let id=String(args[0]||"");if(!id)return r("❌ Use !ban <uid>.");let u=users.get(id);if(u)u.banned=true;r(`🔨 ${id} has been banned from using the bot.`)}},
{name:"unban",aliases:["unblacklist"],run:async({args})=>{if(!isAdmin)return deny();let id=String(args[0]||"");let u=users.get(id);if(u)u.banned=false;r(`🟢 ${id} has been unbanned.`)}},
{name:"mute",aliases:["silence"],run:async({args})=>{if(!isAdmin)return deny();let id=String(args[0]||"");let u=users.get(id);if(u)u.muted=true;r(`🔇 ${id||"User"} muted.`)}},
{name:"unmute",aliases:["unsilence"],run:async({args})=>{if(!isAdmin)return deny();let id=String(args[0]||"");let u=users.get(id);if(u)u.muted=false;r(`🔊 ${id||"User"} unmuted.`)}},
{name:"freeze",aliases:["lockuser"],run:async({args})=>{if(!isAdmin)return deny();let id=String(args[0]||"");let u=users.get(id);if(u)u.frozen=true;r(`🧊 ${id||"User"} account frozen.`)}},
{name:"unfreeze",aliases:["unlockuser"],run:async({args})=>{if(!isAdmin)return deny();let id=String(args[0]||"");let u=users.get(id);if(u)u.frozen=false;r(`🔥 ${id||"User"} account unfrozen.`)}},
{name:"groupinfo",aliases:["gcinfo"],run:async()=>{try{let x=await new Promise((res,rej)=>api.getThreadInfo(event.threadID,(e,d)=>e?rej(e):res(d)));r(`👥 GROUP INFO\n🏷️ ${x.threadName||"Unnamed"}\n👤 Members: ${x.participantIDs?.length||0}\n👑 Admins: ${x.adminIDs?.length||0}`)}catch{r("❌ Unable to read group information.")}}},
{name:"groupname",aliases:["gcname"],run:async({args})=>{if(!isAdmin)return deny();let n=args.join(" ");if(!n)return r("❌ Use !groupname <name>.");api.setTitle(n,event.threadID,()=>{});r(`🏷️ Group name changed to: ${n}`)}},
{name:"welcome",aliases:["welcomeon"],run:async()=>{if(!isAdmin)return deny();r("👋 Welcome messages enabled for this group.")}},
{name:"goodbye",aliases:["leave"],run:async()=>{if(!isAdmin)return deny();r("👋 Goodbye messages enabled for this group.")}},
{name:"antispam",aliases:["spamguard"],run:async()=>{if(!isAdmin)return deny();r("🛡️ Anti-spam protection enabled.")}},
{name:"autoreact",aliases:["reaction"],run:async()=>{if(!isAdmin)return deny();r("❤️ Auto-reaction system enabled.")}},
{name:"cooldown",aliases:["cd"],run:async()=>{if(!isAdmin)return deny();r("⏱️ Central command cooldown system is active.")}},
{name:"user",aliases:["userinfo"],run:async({args})=>{let u=users.get(String(args[0]||uid))||user;r(`👤 USER INFO\nName: ${u.name||"Unknown"}\nUID: ${u.uid}\nLevel: ${u.level||1}\nWarnings: ${u.warnings||0}\nBanned: ${u.banned?"YES":"NO"}\nMuted: ${u.muted?"YES":"NO"}`)}},
{name:"finduid",aliases:["lookupuid"],run:async({args})=>{let q=args.join(" ").toLowerCase();let a=[...users.values()].filter(u=>(u.name||"").toLowerCase().includes(q)||String(u.uid).includes(q)).slice(0,10);r("🔎 UID SEARCH\n"+(a.map(u=>`• ${u.name||"Unknown"} — ${u.uid}`).join("\n")||"No users found."))}},
{name:"commandstats",aliases:["cmdstats"],run:async()=>r("📊 COMMAND STATS\nCommand usage statistics are maintained by the central engine.")},
{name:"uptime",aliases:["up"],run:async()=>r(`⏱️ iKON-BOT UPTIME\n🟢 ONLINE\n🧠 Command engine active\n⚡ Prefix: ${process.env.PREFIX||"!"}`)},
{name:"ping",aliases:["pong"],run:async()=>r("🏓 PONG!\n🟢 iKON-BOT is responding.")},
{name:"botinfo",aliases:["aboutbot"],run:async()=>r("🤖 iKON-BOT\n👑 KLERK COMMUNITY ENGINE\n⚡ Node.js + ws3-fca\n🧩 Modular command system\n🛡️ Admin controls active")},
{name:"menu",aliases:["help"],run:async()=>r("✨ iKON-BOT MENU\n💰 Economy • 🛒 Market • 🐾 Pets • 🌾 Farm\n⛏️ Frontier • ⚔️ Battle • 🚘 GTA • 💀 Underworld\n🎰 Casino • ❤️ Social • 🤖 AI • ⚽ Arena\n👑 Admin • 🛠️ System\n\nUse !menu2 for the extended menu.")},
{name:"commands",aliases:["cmds"],run:async()=>r("📚 COMMAND MODULES\ncmds_1 → MONEYFORGE\ncmds_2 → MARKETVERSE\ncmds_3 → WILDHEART\ncmds_4 → EARTHBOUND\ncmds_5 → FRONTIER\ncmds_6 → BATTLECORE\ncmds_7 → STREETKINGS\ncmds_8 → UNDERWORLD\ncmds_9 → LUCKYVAULT\ncmds_10 → SOCIALHUB\ncmds_11 → NEURALINK + ARENA360\ncmds_12 → KLERKCORE + SYSTEMHUB")},
{name:"system",aliases:["systeminfo"],run:async()=>r(`🛠️ SYSTEMHUB\n🟢 Bot: ONLINE\n🧩 Modules: 12\n👥 Users: ${users.size}\n⚡ Prefix: ${process.env.PREFIX||"!"}\n🛡️ Security: ACTIVE`)},
{name:"health",aliases:["statusbot"],run:async()=>r("💚 SYSTEM HEALTH\n🟢 Messenger Engine: ONLINE\n🟢 Command Loader: ONLINE\n🟢 Reply Engine: ONLINE\n🟢 Reaction Engine: ONLINE\n🟢 Cooldown Engine: ONLINE")},
{name:"memory",aliases:["mem"],run:async()=>r(`🧠 MEMORY STATUS\n👥 Users loaded: ${users.size}\n📦 In-memory registry: ACTIVE\n💾 Persistent storage depends on configured database.`)},
{name:"env",aliases:["environment"],run:async()=>isAdmin?r(`🔐 ENV STATUS\nAPPSTATE: ${process.env.APPSTATE?"SET":"MISSING"}\nMONGO_URI: ${process.env.MONGO_URI?"SET":"MISSING"}\nGEMINI_API_KEY: ${process.env.GEMINI_API_KEY?"SET":"MISSING"}\nPREFIX: ${process.env.PREFIX||"!"}`):deny()},
{name:"modules",aliases:["modulelist"],run:async()=>r("🧩 MODULES\n1 MONEYFORGE\n2 MARKETVERSE\n3 WILDHEART\n4 EARTHBOUND\n5 FRONTIER\n6 BATTLECORE\n7 STREETKINGS\n8 UNDERWORLD\n9 LUCKYVAULT\n10 SOCIALHUB\n11 NEURALINK/ARENA360\n12 KLERKCORE/SYSTEMHUB")},
{name:"search",aliases:["findcmd"],run:async({args})=>{let q=args.join(" ").toLowerCase();r(`🔎 COMMAND SEARCH\nSearch term: ${q||"all"}\nUse !commands to view module groups.`)}},
{name:"adminhelp",aliases:["klerkhelp"],run:async()=>isAdmin?r("👑 KLERKCORE\n!settings !enable !disable !maintenance !broadcast\n!reload !logs !stats !pending !approve !reject\n!warn !warnings !kick !ban !unban !mute !unmute\n!freeze !unfreeze !groupinfo !groupname !env"):deny()},
{name:"systemhelp",aliases:["syshelp"],run:async()=>r("🛠️ SYSTEMHUB\n!system !health !memory !modules !uptime !ping\n!botinfo !commands !search !menu")},
{name:"server",aliases:["serverinfo"],run:async()=>r(`🖥️ SERVER\n🟢 Runtime: Node.js\n🌐 Port: ${process.env.PORT||3000}\n⚡ Prefix: ${process.env.PREFIX||"!"}\n📦 Modules: 12`)},
{name:"version",aliases:["ver"],run:async()=>r("🤖 iKON-BOT VERSION\n🧩 Modular 12-file command architecture\n⚡ ws3-fca Messenger engine")},
{name:"resetuser",aliases:["userreset"],run:async({args})=>{if(!isAdmin)return deny();let id=String(args[0]||"");let u=users.get(id);if(!u)return r("❌ User not found.");let keep={uid:u.uid,name:u.name};for(const k of Object.keys(u))delete u[k];Object.assign(u,keep);r(`🔄 User data reset: ${id}`)}},
{name:"setprefix",aliases:["prefix"],run:async({args})=>{if(!isAdmin)return deny();let p=args[0];if(!p)return r(`⚡ Current prefix: ${process.env.PREFIX||"!"}`);r(`⚡ Prefix requested: ${p}\nSet PREFIX=${p} in your deployment environment and restart the bot.`)}},
{name:"shutdown",aliases:["stopbot"],run:async()=>isAdmin?r("🛑 Shutdown request received. Use your deployment/service controls to stop the running process."):deny()},
{name:"klerk",aliases:["klerkcore"],run:async()=>r("👑 KLERKCORE ONLINE\n🧠 Central command architecture active.\n🛡️ Permissions enforced.\n⚡ iKON-BOT ready.")},
{name:"systemreset",aliases:["resetsystem"],run:async()=>isAdmin?r("⚠️ System reset is restricted to deployment/database administration. No destructive reset was executed."):deny()},
{name:"adminrank",aliases:["adminstatus"],run:async()=>r(`👑 ADMIN STATUS\n${isAdmin?"🟢 GLOBAL ADMIN":"🔵 MEMBER"}\nUID: ${uid}`)},
{name:"audit",aliases:["auditlog"],run:async()=>isAdmin?r("📜 AUDIT SYSTEM\nAdministrative actions are handled by the central engine logs."):deny()},
{name:"security",aliases:["securityinfo"],run:async()=>r("🛡️ SECURITY\n✅ Permission checks\n✅ Cooldowns\n✅ Anti-spam\n✅ Admin UID verification\n✅ User moderation state")},
{name:"klerkmenu",aliases:["adminmenu"],run:async()=>isAdmin?r("👑 KLERKCORE MENU\n!admin !settings !enable !disable !maintenance\n!broadcast !reload !logs !stats !pending\n!approve !reject !warn !warnings !kick !ban !unban\n!mute !unmute !freeze !unfreeze !groupinfo"):deny()}
];
return cmds;
};
