const WORLD=["Starter Town","Capital City","Dark District","Royal District","Industrial Zone","Forest","Jungle","Mountain","Desert","Swamp","Island","Ocean","Village","Harbor","Underground","Ruins","Lost Temple","Secret Area","Cyber City","Space Station"],LOCATIONS=["town","city","district","forest","jungle","mountain","desert","swamp","island","ocean","village","harbor","ruins","cave","temple","secret_area","cyber_city","space_station"],NPCS=["mayor","police","doctor","merchant","blacksmith","farmer","fisherman","miner","hunter","mechanic","bartender","citizen","engineer","scientist","detective","journalist","captain","pilot","developer","executive"],JOBS=["farmer","miner","fisherman","hunter","mechanic","driver","chef","police_officer","merchant","engineer","doctor","cyber_specialist","construction_worker","pilot","captain","journalist","detective","corporate_executive","scientist","software_developer"],MISSIONS=[["First Steps",1,1000,500],["Lost Wallet",3,2500,1200],["Farm Rescue",5,5000,2500],["Deep Mine",10,10000,5000],["Ocean Expedition",15,18000,8000],["Forest Hunt",20,25000,12000],["Stolen Vehicle",30,40000,18000],["Warehouse Raid",40,65000,25000],["Casino Job",50,100000,40000],["Bank Heist",75,250000,75000],["Dragon Hunt",100,500000,150000],["Dungeon Expedition",125,750000,200000],["Guild War",175,1200000,350000],["Treasure Island",225,2000000,500000],["Crypto Crash",275,3500000,750000],["Corporate Takeover",325,5000000,1000000],["Legendary Pet Hunt",400,8000000,2000000],["Boss Invasion",450,12000000,3000000],["City Under Siege",500,25000000,5000000],["World Eater",600,50000000,10000000]],GUILDS=["Adventurers","Hunters","Merchants","Warriors","Scientists","Explorers","Royal Guard","Underworld"],QUESTS=["daily","weekly","main","side","faction","guild","bounty","exploration","treasure","survival"],FARM_CROPS=["wheat","corn","rice","potato","tomato","carrot","cabbage","pumpkin","cotton","sugarcane"],MATERIALS=["wood","stone","iron","coal","copper","silver","gold","diamond","crystal","mythril"],TREASURES=["coin_chest","gold_chest","rare_chest","legendary_chest","ancient_relic","divine_relic"],const=[];

const commands=[
{name:"world",aliases:["worldlist"],category:"World",featured:true,purpose:"Show the world map and available locations",run:async c=>({text:`🌍 WORLD\n\n${WORLD.map((x,i)=>`${i+1}. ${x}`).join("\n")}`,gameplay:false})},
{name:"map",aliases:["locations"],category:"World",featured:true,purpose:"Show discoverable locations",run:async c=>({text:`🗺️ LOCATIONS\n\n${LOCATIONS.map((x,i)=>`${i+1}. ${x}`).join("\n")}`,gameplay:false})},
{name:"explore",aliases:["discover"],category:"World",featured:true,cooldown:30,purpose:"Explore the world and discover locations",xp:40,money:2500,run:async c=>{const x=LOCATIONS[Math.floor(Math.random()*LOCATIONS.length)];return{text:`🧭 Exploration complete!\n📍 You discovered: ${x}\n💰 +$2,500\n⭐ +40 XP\n🎁 Reward: Explorer Token, Map Fragment, Supply Pack`,money:2500,xp:40,rewards:[{id:"explorer_token"},{id:"map_fragment"},{id:"supply_pack"}]}}},

{name:"location",aliases:["loc"],category:"World",purpose:"Show your current location",run:async c=>({text:`📍 Current Location\n🏙️ ${c.user.location||"Starter Town"}`,gameplay:false})},
{name:"travel",aliases:["move"],category:"World",cooldown:10,purpose:"Travel to another unlocked location",run:async c=>{const x=c.args[0]?.toLowerCase();if(!x)return{text:`🧭 Usage: ${c.prefix}travel <location>`};if(!LOCATIONS.includes(x))return{text:`❌ Unknown location.\nUse ${c.prefix}map.`};c.user.location=x;return{text:`🚶 Travel complete!\n📍 ${x}\n🎫 Travel Pass\n⭐ +20 XP\n🎁 Map Stamp + Travel Token`,xp:20,rewards:[{id:"map_stamp"},{id:"travel_token"},{id:"travel_pass"}]}}},

{name:"mission",aliases:["missions","quest"],category:"Progression",featured:true,purpose:"Show or start missions",run:async c=>{if(!c.args.length)return{text:`📜 MISSIONS\n\n${MISSIONS.map((m,i)=>`${i+1}. ${m[0]} | Lv.${m[1]} | $${m[2].toLocaleString()} | +${m[3]} XP`).join("\n")}`,gameplay:false});const q=c.args.join(" ").toLowerCase(),m=MISSIONS.find(x=>x[0].toLowerCase()===q||x[0].toLowerCase().includes(q));if(!m)return{text:"❌ Mission not found."};if(c.user.level<m[1])return{text:`🔒 Level ${m[1]} required.`};return{text:`🎯 Mission accepted: ${m[0]}\n📈 Requirement: Level ${m[1]}\n💰 Reward: $${m[2].toLocaleString()}\n⭐ XP: ${m[3].toLocaleString()}`,gameplay:false})}},

{name:"mission_complete",aliases:["complete_mission"],category:"Progression",cooldown:30,purpose:"Complete an active mission",run:async c=>({text:"🎯 Mission completed!\n💰 Mission Cash\n⭐ Mission XP\n🎁 Mission Token, Supply Crate, Achievement Point",money:5000,xp:500,rewards:[{id:"mission_token"},{id:"supply_crate"},{id:"achievement_point"}]})},
{name:"mission_history",aliases:["missions_history"],category:"Progression",purpose:"Show completed missions",run:async c=>({text:"📜 Mission history\nYour completed missions will appear here.",gameplay:false})},

{name:"job",aliases:["jobs","career"],category:"Progression",featured:true,purpose:"Show available careers",run:async c=>({text:`💼 JOBS\n\n${JOBS.map((x,i)=>`${i+1}. ${x}`).join("\n")}`,gameplay:false})},
{name:"work",aliases:["workjob"],category:"Progression",cooldown:60,purpose:"Work your current job",money:5000,xp:60,run:async c=>({text:`💼 Work completed!\n💰 +$5,000\n⭐ +60 XP\n🎁 Pay Slip, Job Token, Energy Pack`,money:5000,xp:60,rewards:[{id:"pay_slip"},{id:"job_token"},{id:"energy_pack"}]})},
{name:"job_info",aliases:["career_info"],category:"Progression",purpose:"Show career information",run:async c=>({text:`💼 Career\nCurrent Job: ${c.user.job||"Unemployed"}\nJob Level: ${c.user.jobLevel||1}\nUse ${c.prefix}job to view careers.`,gameplay:false})},
{name:"promote",aliases:["promotion"],category:"Progression",cooldown:60,purpose:"Promote your career level",run:async c=>{const l=c.user.jobLevel||1;c.user.jobLevel=l+1;return{text:`🎖️ Promotion successful!\n📈 Job Level: ${l+1}\n💰 Bonus Pay\n⭐ +100 XP\n🎁 Promotion Badge`,xp:100,rewards:[{id:"promotion_badge"},{id:"career_token"},{id:"salary_bonus"}]}}},

{name:"level",aliases:["level_xp","lvl"],category:"Progression",featured:true,purpose:"Show your level and XP",run:async c=>({text:`⭐ LEVEL ${c.user.level}\n✨ XP: ${c.user.xp}/${c.user.level*1000}\n🏆 Prestige: ${c.user.prestige||0}`,gameplay:false})},
{name:"xp",aliases:["experience"],category:"Progression",purpose:"Show XP progress",run:async c=>({text:`✨ XP: ${c.user.xp}\n⭐ Level: ${c.user.level}\n📈 Next Level: ${c.user.level*1000} XP`,gameplay:false})},
{name:"rank",aliases:["ranking"],category:"Progression",featured:true,purpose:"Show player rank",run:async c=>({text:`🏆 RANK\n⭐ Level: ${c.user.level}\n👑 Prestige: ${c.user.prestige||0}\n🏅 Rank: ${c.user.rank||"Rookie"}`,gameplay:false})},
{name:"prestige",aliases:["prestige_up"],category:"Progression",purpose:"Reset level progression for prestige",run:async c=>{if(c.user.level<100)return{text:"🔒 Level 100 required for Prestige."};c.user.level=1;c.user.xp=0;c.user.prestige=(c.user.prestige||0)+1;return{text:`👑 PRESTIGE ${c.user.prestige}\n📈 Progression reset\n🎁 Prestige Badge, Legacy Token, Prestige Chest`,rewards:[{id:"prestige_badge"},{id:"legacy_token"},{id:"prestige_chest"}]}}},

{name:"achievement",aliases:["achievements","achieve"],category:"Progression",featured:true,purpose:"Show achievements",run:async c=>({text:"🏆 ACHIEVEMENTS\n\n🥇 First Steps\n💰 Millionaire\n⚔️ Warrior\n🐾 Pet Master\n🌍 Explorer\n👑 Prestige Legend",gameplay:false})},
{name:"milestones",aliases:["milestone"],category:"Progression",purpose:"Show progression milestones",run:async c=>({text:"🏁 MILESTONES\n\n⭐ Level 10\n⭐ Level 25\n⭐ Level 50\n⭐ Level 100\n⭐ Level 250\n⭐ Level 500",gameplay:false})},
{name:"passport",aliases:["idcard"],category:"Progression",purpose:"Show your world passport",run:async c=>({text:`🛂 PASSPORT\n👤 ${c.user.name}\n🪪 ${c.uid}\n📍 ${c.user.location||"Starter Town"}\n⭐ Level ${c.user.level}`,gameplay:false})},
{name:"stats",aliases:["statistics"],category:"Progression",purpose:"Show player statistics",run:async c=>({text:`📊 STATS\n⭐ Level: ${c.user.level}\n✨ XP: ${c.user.xp}\n💰 Money: $${c.user.money.toLocaleString()}\n⚔️ Wins: ${c.user.stats?.wins||0}\n💀 Losses: ${c.user.stats?.losses||0}\n🎮 Commands: ${c.user.stats?.commands||0}`,gameplay:false})},

{name:"guild",aliases:["guilds"],category:"Progression",featured:true,purpose:"Show guilds and guild information",run:async c=>({text:`🏰 GUILDS\n\n${GUILDS.map((x,i)=>`${i+1}. ${x}`).join("\n")}`,gameplay:false})},
{name:"guild_create",aliases:["createguild"],category:"Progression",purpose:"Create a guild",money:100000,cooldown:60,run:async c=>{if((c.user.money||0)<100000)return{text:"❌ You need $100,000."};c.user.money-=100000;c.user.guild=c.user.name+"'s Guild";return{text:`🏰 Guild created!\n👑 ${c.user.guild}\n💰 -$100,000\n⭐ +100 XP\n🎁 Guild Charter, Guild Banner, Guild Token`,xp:100,rewards:[{id:"guild_charter"},{id:"guild_banner"},{id:"guild_token"}]}}},

{name:"guild_join",aliases:["joinguild"],category:"Progression",purpose:"Join a guild",run:async c=>{const x=c.args.join(" ");if(!x)return{text:`Usage: ${c.prefix}guild_join <guild>`};if(!GUILDS.some(g=>g.toLowerCase()===x.toLowerCase()))return{text:"❌ Guild not found."};c.user.guild=x;return{text:`🏰 Joined ${x}!\n⭐ +50 XP\n🎁 Guild Badge, Guild Token, Welcome Pack`,xp:50,rewards:[{id:"guild_badge"},{id:"guild_token"},{id:"welcome_pack"}]}}},

{name:"gather",aliases:["forage"],category:"World",cooldown:30,purpose:"Gather world materials",run:async c=>{const x=MATERIALS[Math.floor(Math.random()*MATERIALS.length)];return{text:`⛏️ Gathering complete!\n📦 ${x} x3\n⭐ +30 XP\n🎁 Supply Pack, Material Token, Explorer Badge`,xp:30,rewards:[{id:x,qty:3},{id:"supply_pack"},{id:"material_token"}]}}},
{name:"treasure",aliases:["treasure_hunt"],category:"World",cooldown:60,purpose:"Search for treasure",money:10000,xp:100,run:async c=>{const x=TREASURES[Math.floor(Math.random()*TREASURES.length)];return{text:`💎 TREASURE FOUND!\n📦 ${x}\n💰 +$10,000\n⭐ +100 XP\n🎁 Treasure Map, Explorer Token, Relic Fragment`,money:10000,xp:100,rewards:[{id:x},{id:"treasure_map"},{id:"relic_fragment"}]}}},

{name:"npc",aliases:["npc_list"],category:"World",purpose:"Show available NPCs",run:async c=>({text:`🧑‍🤝‍🧑 NPCS\n\n${NPCS.map((x,i)=>`${i+1}. ${x}`).join("\n")}`,gameplay:false})},
{name:"npc_chat",aliases:["talk"],category:"World",purpose:"Talk to a world NPC",run:async c=>({text:`💬 NPC CHAT\nChoose an NPC:\n${NPCS.slice(0,10).map(x=>`• ${x}`).join("\n")}`,gameplay:false})},
{name:"npc_job",aliases:["npcwork"],category:"World",cooldown:60,purpose:"Take temporary NPC work",money:3000,xp:35,run:async c=>({text:"🧑‍💼 NPC job completed!\n💰 +$3,000\n⭐ +35 XP\n🎁 Job Token, Supply Pack, Reputation Point",money:3000,xp:35,rewards:[{id:"job_token"},{id:"supply_pack"},{id:"reputation_point"}]})},

{name:"daily",aliases:["daily_activity"],category:"Progression",featured:true,cooldown:86400,purpose:"Claim daily progression rewards",money:10000,xp:100,run:async c=>({text:"🎁 DAILY CLAIMED!\n💰 +$10,000\n⭐ +100 XP\n🎁 Daily Token, Energy Pack, Lucky Ticket",money:10000,xp:100,rewards:[{id:"daily_token"},{id:"energy_pack"},{id:"lucky_ticket"}]})},
{name:"weekly",aliases:["weekly_challenge"],category:"Progression",cooldown:604800,purpose:"Claim weekly challenge rewards",money:50000,xp:500,run:async c=>({text:"📅 WEEKLY COMPLETE!\n💰 +$50,000\n⭐ +500 XP\n🎁 Weekly Chest, Rare Token, Bonus Ticket",money:50000,xp:500,rewards:[{id:"weekly_chest"},{id:"rare_token"},{id:"bonus_ticket"}]})},
{name:"streak",aliases:["streak_check"],category:"Progression",purpose:"Show activity streak",run:async c=>({text:`🔥 STREAK\nCurrent: ${c.user.streak||0} days\n🏆 Keep playing daily to increase it.`,gameplay:false})},
{name:"rewards",aliases:["rank_rewards"],category:"Progression",purpose:"Show progression rewards",run:async c=>({text:"🎁 REWARDS\n\n⭐ Level Rewards\n👑 Prestige Rewards\n🏆 Achievement Rewards\n🔥 Streak Rewards\n🎯 Mission Rewards",gameplay:false})}
];

module.exports=commands;
