// commands/cmds_8.js
const C="cmds_8";

const c=(name,aliases,description,usage,hint,execute,permission="everyone",cooldown=0)=>({
  name,aliases,category:C,description,usage,hint,permission,cooldown,execute
});

const r=(reply,msg)=>reply(
`🎭 NEXUS
━━━━━━━━━━━━━━━━
${msg}
━━━━━━━━━━━━━━━━
🎰 CASINO • 🧠 AI • ⚡ SOCIAL • 🟡 POKÉMON`
);

const E=(title,msg)=>async({reply,args})=>
  r(reply,`${title}\n${msg.replace(/\{a\}/g,args.join(" ")||"Target")}`);

const G=(title,msg)=>async({reply})=>
  r(reply,`${title}\n${msg}`);

module.exports=[

c("casino",["games","arcade"],"Open casino","!casino","Choose a game",
  G("🎰 NEXUS CASINO","🎰 Slots\n🃏 Blackjack\n🎡 Roulette\n🎲 Dice\n🪙 Coinflip\n📈 Crash\n💣 Mines\n🏆 Jackpot")),

c("slots",["slot"],"Play slots","!slots 10000","Explicit bet required",
  E("🎰 SLOT MACHINE","💰 Bet: {a}\n🍒 🎰 🍋\n🎲 Result calculated by game engine."),"everyone",5000),

c("blackjack",["bj"],"Play blackjack","!blackjack 10000","Explicit bet required",
  E("🃏 BLACKJACK","💰 Bet: {a}\n🃏 Cards dealt by casino engine.\n🎯 !hit / !stand")),

c("roulette",["wheel"],"Play roulette","!roulette red 10000","Explicit bet required",
  E("🎡 ROULETTE","🎯 Bet: {a}\n🎡 Wheel spinning...\n💰 Result calculated by casino engine.")),

c("dice",["diceroll"],"Roll betting dice","!dice 10000","Explicit bet required",
  E("🎲 DICE","💰 Bet: {a}\n🎲 Roll generated by game engine.")),

c("coinflip",["coin","toss"],"Flip a coin","!coinflip heads 10000","Explicit bet required",
  E("🪙 COINFLIP","🎯 {a}\n🪙 Flipping...\n💰 Result calculated.")),

c("higherlower",["highlow"],"Higher/lower game","!higherlower 10000","Explicit bet required",
  E("📈 HIGHER / LOWER","💰 Bet: {a}\n🎯 Guess the next value.")),

c("poker",["pokergame"],"Play poker","!poker 10000","Explicit bet required",
  E("♠️ POKER","💰 Bet: {a}\n🃏 Table created.\n🎯 Hand resolved by game engine.")),

c("baccarat",["bacc"],"Play baccarat","!baccarat 10000","Explicit bet required",
  E("♦️ BACCARAT","💰 Bet: {a}\n🃏 Table ready.")),

c("crash",["crashgame"],"Play crash","!crash 10000","Explicit bet required",
  E("📈 CRASH","💰 Bet: {a}\n🚀 Multiplier generated by game engine.\n⚠️ Cash out before the crash.")),

c("mines",["minesgame"],"Play mines","!mines 10000","Explicit bet required",
  E("💣 MINES","💰 Bet: {a}\n💣 Board generated.\n🎯 Choose tiles carefully.")),

c("plinko",["plinkogame"],"Play plinko","!plinko 10000","Explicit bet required",
  E("🔴 PLINKO","💰 Bet: {a}\n🎯 Ball dropped.\n🏆 Multiplier calculated.")),

c("jackpot",["jackpotgame"],"View jackpot","!jackpot","Casino jackpot",
  G("💎 NEXUS JACKPOT","💰 Current jackpot pool loaded.\n🏆 Jackpot rules available through the game engine.")),

c("rps",["rockpaperscissors"],"Rock paper scissors","!rps rock","No money required",
  E("✊ RPS","🎯 You: {a}\n🤖 NEXUS is choosing...")),

c("trivia",["quiz"],"Play trivia","!trivia","Earn XP",
  G("🧠 TRIVIA","❓ Question generated!\n⭐ Correct answers reward XP.")),

c("mathgame",["math"],"Math challenge","!math","Solve for XP",
  G("➗ MATH CHALLENGE","🧮 Solve the generated equation.\n⏱️ Speed matters.")),

c("scramble",["wordscramble"],"Word scramble","!scramble","Solve for XP",
  G("🔤 WORD SCRAMBLE","🧩 Letters scrambled!\n🏆 Solve it for XP.")),

c("hangman",["hang"],"Play hangman","!hangman","Word game",
  G("🎯 HANGMAN","🔤 Guess the hidden word.\n❤️ Attempts are limited.")),

c("memory",["memorygame"],"Memory game","!memory","Match symbols",
  G("🧠 MEMORY","🃏 Match the hidden symbols.\n⭐ XP awarded for success.")),

c("tictactoe",["ttt"],"Tic tac toe","!tictactoe @user","Challenge player",
  E("⭕ TIC TAC TOE","👤 Target: {a}\n🎮 Match request created.")),

c("connect4",["connect"],"Connect four","!connect4 @user","Challenge player",
  E("🔴 CONNECT FOUR","👤 Target: {a}\n🎮 Challenge request created.")),

c("ai",["ask","chat"],"Talk to AI","!ai <message>","Gemini/AI backend",
  E("🧠 NEXUS AI","💬 {a}\n🤖 AI request routed through configured provider."),
  "everyone",3000),

// GEMINI KEPT HERE AS THE MAIN USER AI COMMAND.
// cmds_7 admin control should be renamed gemini_admin.
c("gemini",["gem"],"Use Gemini AI","!gemini <message>","Requires configured API key",
  E("♊ GEMINI","💬 {a}\n🧠 Gemini request routed through the AI engine."),
  "everyone",5000),

c("gpt",["gptchat"],"AI conversation","!gpt <message>","Configured AI provider",
  E("🤖 GPT MODE","💬 {a}\n🧠 AI response requested."),
  "everyone",5000),

c("translate",["trans"],"Translate text","!translate en Hello","Language + text",
  E("🌐 TRANSLATOR","📝 {a}\n🔄 Translation engine processing.")),

c("summarize",["summary"],"Summarize text","!summarize <text>","AI summary",
  E("📝 SUMMARY","📚 {a}\n✨ Concise summary requested.")),

c("rewrite",["rephrase"],"Rewrite text","!rewrite <text>","AI rewrite",
  E("✍️ REWRITE","📝 {a}\n✨ Improved version requested.")),

c("grammar",["grammarcheck"],"Check grammar","!grammar <text>","AI grammar check",
  E("📚 GRAMMAR","📝 {a}\n🔎 Grammar analysis requested.")),

c("explain",["explainai"],"Explain a topic","!explain <topic>","AI explanation",
  E("💡 EXPLAINER","📖 {a}\n🧠 Explanation requested.")),

c("code",["codeai"],"Generate code help","!code <request>","AI coding assistant",
  E("💻 CODE AI","🧠 Request: {a}\n⚙️ Coding assistance requested.")),

c("debug",["debugai"],"Debug code","!debug <code>","AI debugging",
  E("🐞 DEBUG AI","🔎 {a}\n🧠 Debug analysis requested.")),

c("imagine",["generate"],"Generate creative prompt","!imagine <idea>","AI creative mode",
  E("🌌 IMAGINE","✨ {a}\n🎨 Creative generation requested.")),

c("caption",["captionai"],"Generate caption","!caption <topic>","AI caption",
  E("📸 CAPTION AI","📝 {a}\n✨ Caption generation requested.")),

c("story",["storyai"],"Generate story","!story <idea>","AI story",
  E("📖 STORY AI","🌌 {a}\n✍️ Story generation requested.")),

c("poem",["poetry"],"Generate poem","!poem <topic>","AI poetry",
  E("📝 POETRY AI","🌹 {a}\n✨ Poem generation requested.")),

c("fact",["facts"],"Get a fact","!fact","Random fact",
  G("🧠 NEXUS FACT","💡 Fact engine requested.")),

c("quote",["quotes"],"Get a quote","!quote","Random quote",
  G("💬 QUOTE DROP","✨ Quote engine requested.")),

c("pokemon",["poke"],"Open Pokémon system","!pokemon","View Pokémon",
  G("🟡 POKÉMON NEXUS","⚡ 50 Pokémon available\n🌟 Random group spawns every 20 minutes.\n⏳ Active spawn expires after 20 minutes.\n🎯 !spawn to check the current spawn.")),

c("spawn",["pokespawn"],"Check Pokémon spawn","!spawn","Group spawn",
  G("🌟 WILD POKÉMON","🔎 Checking current group spawn...\n⏳ Spawn window: 20 minutes.")),

c("pokebattle",["pokefight"],"Battle Pokémon","!pokebattle","Requires Pokémon",
  E("⚡ POKÉMON BATTLE","🎯 Target: {a}\n❤️ HP and turn system activated.")),

// FIXED: removed self-alias "poketrain"
c("poketrain",[],"Train Pokémon","!poketrain","Gain Pokémon XP",
  E("🏋️ POKÉMON TRAINING","🐾 {a}\n⭐ Training XP calculated.")),

c("pokevolve",["pokeevolve"],"Evolve Pokémon","!pokevolve Pikachu","Requires evolution conditions",
  E("✨ POKÉMON EVOLUTION","⚡ {a}\n🧬 Evolution requirements checked.")),

// FIXED: removed self-alias "pokerelease"
c("pokerelease",[],"Release Pokémon","!pokerelease Pikachu","Confirmation required",
  E("🕊️ RELEASE POKÉMON","🐾 {a}\n⚠️ Release requires confirmation.")),

c("pokefavorite",["pokefav"],"Favorite Pokémon","!pokefavorite Pikachu","Protect favorite",
  E("⭐ FAVORITE POKÉMON","🐾 {a}\n💛 Favorite status updated.")),

c("poketeam",["team"],"View Pokémon team","!poketeam","Show active team",
  G("⚡ POKÉMON TEAM","🐾 Active team loaded.\n🏆 Build your strongest lineup.")),

// FIXED: removed self-alias "poketrade"
c("poketrade",[],"Trade Pokémon","!poketrade @user Pikachu","Target accepts trade",
  E("🔄 POKÉMON TRADE","👤 Target: {a}\n⏳ Trade request created.")),

c("pokeinfo",["pokedex"],"Inspect Pokémon","!pokeinfo Pikachu","View information",
  E("📖 POKÉDEX","🔎 {a}\n⭐ Rarity\n❤️ Stats\n⚡ Ability\n🧬 Evolution path")),

c("pokestats",["pokestat"],"View Pokémon stats","!pokestats Pikachu","Battle stats",
  E("📊 POKÉMON STATS","🐾 {a}\n❤️ HP\n⚔️ Attack\n🛡️ Defense\n⚡ Speed\n✨ XP")),

c("love",["lovecheck"],"Love compatibility","!love @user","Social game",
  E("💖 LOVE CHECK","👤 Target: {a}\n💕 Compatibility calculated for fun.")),

c("kiss",["smooch"],"Kiss player","!kiss @user","Reply or mention",
  E("💋 KISS","💖 Target: {a}\n😂 Somebody got kissed!")),

c("slap",["smack"],"Slap player","!slap @user","Reply or mention",
  E("👋 SLAP","💥 Target: {a}\n😂 BONK!")),

c("hug",["embrace"],"Hug player","!hug @user","Reply or mention",
  E("🤗 HUG","💞 Target: {a}\n🫂 Wholesome energy deployed.")),

c("pat",["headpat"],"Pat player","!pat @user","Reply or mention",
  E("🫳 PAT","🐾 Target: {a}\n😊 Pat delivered.")),

// FIXED: canonical social command changed to pokeuser.
// !poke remains reserved for Pokémon.
c("pokeuser",["pokeplayer"],"Poke player","!pokeuser @user","Reply or mention",
  E("👉 POKE","😂 Target: {a}\n👀 You have been poked.")),

c("highfive",["five"],"High five","!highfive @user","Reply or mention",
  E("🙌 HIGH FIVE","🔥 Target: {a}\n💥 SLAP!")),

c("cuddle",["snuggle"],"Cuddle player","!cuddle @user","Reply or mention",
  E("🫂 CUDDLE","💞 Target: {a}\n🥹 Maximum wholesome.")),

c("marry",["marriage"],"Send marriage request","!marry @user","Target accepts request",
  E("💍 MARRIAGE REQUEST","💖 Target: {a}\n💌 Proposal sent.\n⏳ Target must ACCEPT.")),

c("divorce",["breakup"],"End relationship","!divorce @user","Confirmation required",
  E("💔 DIVORCE","👤 Target: {a}\n⚠️ Confirmation required.")),

c("couple",["co"],"Relationship request","!co @user","Target accepts request",
  E("💖 CO REQUEST","👤 Target: {a}\n💌 Relationship request sent.\n⏳ ACCEPT / DECLINE.")),

c("crush",["crushcheck"],"Check or send crush","!crush @user","Reply/mention supported",
  E("💘 CRUSH","👤 Target: {a}\n💓 Crush interaction processed.")),

c("ship",["shipcheck"],"Ship two players","!ship @user1 @user2","Two targets",
  E("🚢 SHIP METER","💕 Pair: {a}\n📊 Compatibility calculated for fun.")),

c("pair",["randompair"],"Random pair","!pair","Group social game",
  G("💞 RANDOM PAIR","🎲 Pairing players...\n💕 A random match will be selected.")),

c("friend",["friendadd"],"Friend request","!friend @user","Target accepts",
  E("🤝 FRIEND REQUEST","👤 Target: {a}\n💌 Request sent.")),

c("friends",["friendlist"],"View friends","!friends","Social list",
  G("👥 FRIENDS","🤝 Friend list loaded.\n⭐ Reputation and activity available.")),

c("family",["familytree"],"View family","!family","Social family",
  G("👪 FAMILY","🌳 Family network loaded.\n💕 Relationships are stored in the social system.")),

c("reputation",["rep"],"View reputation","!reputation","Social reputation",
  G("⭐ REPUTATION","🏆 Reputation score loaded.\n🤝 Positive interactions can increase reputation.")),

c("social",["socialstats"],"Social profile","!social","View social stats",
  G("🎭 SOCIAL PROFILE","💕 Relationships\n🤝 Friends\n⭐ Reputation\n🏆 Social achievements")),

c("autopair",["pairauto"],"Automatic pairing","!autopair","Group feature",
  G("💞 AUTO-PAIR","🎲 Automatic pairing requested.\n🛡️ Uses eligible group members only.")),

c("autocrush",["crushauto"],"Automatic crush","!autocrush","Group social game",
  G("💘 AUTO-CRUSH","🎲 Random crush system activated for the group.")),

c("randomcrush",["crushrandom"],"Random crush","!randomcrush","Group social game",
  G("💘 RANDOM CRUSH","🎯 A random eligible player will be selected.")),

c("match",["matchme"],"Find social match","!match","Compatibility game",
  G("💕 MATCHMAKER","🔎 Searching eligible social profiles...\n💖 Match calculated for fun.")),

c("profile",["me","userinfo"],"View profile","!profile","Reply/mention supported",
  E("👤 NEXUS PROFILE","👤 {a}\n💰 Economy\n⭐ Level\n⚔️ Power\n🐾 Pets\n🏆 Achievements")),

c("uid",["id","myuid"],"Show user ID","!uid","Account identifier",
  E("🆔 USER ID","👤 {a}\n🔢 User identifier lookup requested.")),

c("avatar",["profilepic"],"View avatar","!avatar","Profile picture",
  E("🖼️ AVATAR","👤 {a}\n📸 Profile image lookup requested.")),

// FIXED: removed duplicate "members" alias
c("count",[],"Count group members","!count","Group utility",
  G("👥 MEMBER COUNT","📊 Current group member count requested.")),

c("groupstats",["gcstats"],"Group statistics","!groupstats","Group activity",
  G("📊 GROUP STATS","👥 Members\n💬 Activity\n🏆 Events\n🎮 Games\n⚔️ Battles")),

c("time",["clock"],"Show time","!time","Time utility",
  G("🕐 TIME","🌍 Time service requested.")),

c("date",["today"],"Show date","!date","Date utility",
  G("📅 DATE","🌍 Date service requested.")),

c("calc",["calculate"],"Calculate expression","!calc 25*4","Math utility",
  E("🧮 CALCULATOR","🔢 {a}\n⚡ Calculation requested.")),

c("convert",["conversion"],"Convert units","!convert 10 km mi","Unit utility",
  E("🔄 CONVERTER","📏 {a}\n⚡ Conversion requested.")),

c("currency",["fx"],"Currency conversion","!currency 100 USD GHS","Currency utility",
  E("💱 CURRENCY","💰 {a}\n📈 Current conversion requested.")),

c("search",["lookup"],"Search information","!search <query>","Search provider",
  E("🔎 SEARCH","🌐 {a}\n📚 Search request submitted.")),

c("shorten",["shorturl"],"Shorten a URL","!shorten <url>","URL utility",
  E("🔗 URL SHORTENER","🌐 {a}\n⚡ Shortening request submitted.")),

c("qr",["qrcode"],"Generate QR request","!qr <text>","QR utility",
  E("📱 QR CODE","🔳 {a}\n🎨 QR generation requested.")),

c("remind",["reminder"],"Create reminder","!remind 10m Check farm","Reminder utility",
  E("⏰ REMINDER","📝 {a}\n🔔 Reminder request created.")),

c("timer",["countdown"],"Start timer","!timer 60","Timer utility",
  E("⏱️ TIMER","⌛ {a}\n🔥 Timer started.")),

c("poll",["vote"],"Create poll","!poll <question>","Group utility",
  E("📊 POLL","❓ {a}\n🗳️ Poll created.")),

c("help",["h"],"Show command help","!help <command>","Command information",
  E("📖 NEXUS HELP","🔎 {a}\n💡 Use !help <command> for syntax and requirements.")),

c("nexus",["nexusmenu"],"Open NEXUS menu","!nexus","Category menu",
  G("🎭 NEXUS","🎰 Casino\n🧠 AI\n🟡 Pokémon\n💖 Social\n🎮 Mini-games\n🛠️ Utilities\n\n💡 Try !help <command>."))

];
