const R=globalThis.__KLERK_BOT__||(globalThis.__KLERK_BOT__={}),P=R.players||(R.players=new Map()),C={};
const U=id=>{id=String(id||"");let u=P.get(id);if(!u)u={id,cash:100000,bank:0,vault:0,savings:0,coins:100,tokens:0,xp:0,level:1,inventory:{},salary:0,credit:500,business:null,stocks:{},crypto:{},properties:[],market:{},trades:{},auctions:{},cooldowns:{},tax:0};u.bank??=0;u.vault??=0;u.savings??=0;u.coins??=100;u.tokens??=0;u.inventory??={};u.stocks??={};u.crypto??={};u.properties??=[];u.cooldowns??={};P.set(id,u);return u};
const N=x=>String(x||"").toLowerCase().trim(),num=x=>Math.max(0,Number(String(x||"").replace(/[$,]/g,""))||0),money=n=>`$${Math.floor(n||0).toLocaleString()}`,BAR=(v,m=100,n=10)=>{let a=Math.round(Math.max(0,Math.min(m,v))/m*n);return"█".repeat(a)+"░".repeat(n-a)},D=(u,k,n=1)=>u.inventory[k]=(u.inventory[k]||0)+n;
const XP=(c,n=100)=>{let u=U(c.uid),old=u.level;u.xp=(u.xp||0)+n;while(u.xp>=u.level*100){u.xp-=u.level*100;u.level++}return old<u.level?`\n🎉 LEVEL UP ${old} ➜ ${u.level}!`:""};
const REWARD=(c,x=100,cash=50000,it=["🎁 Economy Box","💎 Gem","🪙 Token"])=>{let u=U(c.uid);u.cash+=cash;it.slice(0,3).forEach(i=>D(u,i));return`💰 +${money(cash)}\n🎁 ${it.slice(0,3).join(" • ")}\n✨ +${x} XP${XP(c,x)}`};
const CD=(u,k,s)=>{let r=(u.cooldowns[k]||0)-Date.now();if(r>0)return Math.ceil(r/1000);u.cooldowns[k]=Date.now()+s*1000;return 0};
const target=c=>Object.keys(c.event?.mentions||{})[0]||c.event?.messageReply?.senderID||c.replyToUserID||null;
const LIST=(a,p=1)=>{let s=(Math.max(1,num(p))-1)*10;return a.slice(s,s+10).map((x,i)=>`${s+i+1}. ${x}`).join("\n")||"Nothing found."};
const add=(names,fn)=>String(names).split("|").forEach(n=>C[N(n)]={name:N(n),execute:fn,module:"economy"});

add("balance|bal|b",c=>{let u=U(c.uid);c.reply(`💰 KLERK WALLET\n👤 ${c.name}\n💵 Cash: ${money(u.cash)}\n🏦 Bank: ${money(u.bank)}\n🔐 Vault: ${money(u.vault)}\n💎 Savings: ${money(u.savings)}\n🪙 Coins: ${u.coins.toLocaleString()}\n🎟️ Tokens: ${u.tokens.toLocaleString()}\n\n💰 Total: ${money(u.cash+u.bank+u.vault+u.savings)}\n⭐ Lv.${u.level} ${BAR(u.xp,u.level*100)}`)});
add("wallet",c=>C.balance.execute(c));
add("bank",c=>{let u=U(c.uid);c.reply(`🏦 BANK ACCOUNT\n💰 ${money(u.bank)}\n📈 Savings: ${money(u.savings)}\n🔐 Vault: ${money(u.vault)}\n💳 Credit Score: ${u.credit}`)});
add("deposit",c=>{let u=U(c.uid),type=N(c.args[0]),amt=num(c.args[1]||c.args[0]);if(!amt)return c.reply("💡 !deposit <cash|vault|savings> <amount>");if(type!=="cash"&&c.args.length<2)return c.reply("💡 !deposit <cash|vault|savings> <amount>");if(type==="cash"){if(u.cash<amt)return c.reply("❌ Not enough cash.");u.cash-=amt;u.bank+=amt}else if(type==="vault"){if(u.cash<amt)return c.reply("❌ Not enough cash.");u.cash-=amt;u.vault+=amt}else if(type==="savings"){if(u.cash<amt)return c.reply("❌ Not enough cash.");u.cash-=amt;u.savings+=amt}else return c.reply("💡 Destination: cash, vault or savings.");c.reply(`🏦 Deposit complete.\n💰 ${money(amt)} moved to ${type}.`)});
add("withdraw",c=>{let u=U(c.uid),type=N(c.args[0]||"bank"),amt=num(c.args[1]);if(!amt)return c.reply("💡 !withdraw <bank|vault|savings> <amount>");if(!["bank","vault","savings"].includes(type))return c.reply("❌ Invalid account.");if(u[type]<amt)return c.reply(`❌ ${type} only has ${money(u[type])}.`);u[type]-=amt;u.cash+=amt;c.reply(`💵 Withdrawn ${money(amt)} from ${type}.\n💰 Cash: ${money(u.cash)}`)});
add("vault",c=>{let u=U(c.uid);c.reply(`🔐 VAULT\n💰 ${money(u.vault)}\n🛡️ Protected storage\n💡 !deposit vault <amount>\n💡 !withdraw vault <amount>`)});
add("savings|saving",c=>{let u=U(c.uid);c.reply(`💎 SAVINGS ACCOUNT\n💰 ${money(u.savings)}\n📈 Interest status: ACTIVE\n💡 !deposit savings <amount>`)});
add("save",c=>{let u=U(c.uid),amt=num(c.args[0]);if(!amt)return c.reply("💡 !save <amount>");if(u.cash<amt)return c.reply("❌ Not enough cash.");u.cash-=amt;u.savings+=amt;c.reply(`💎 Saved ${money(amt)}.\n💰 Savings: ${money(u.savings)}`)});
add("unsave",c=>{let u=U(c.uid),amt=num(c.args[0]);if(!amt)return c.reply("💡 !unsave <amount>");if(u.savings<amt)return c.reply("❌ Not enough savings.");u.savings-=amt;u.cash+=amt;c.reply(`💵 ${money(amt)} withdrawn from savings.`)});
add("transfer|pay",c=>{let t=target(c),u=U(c.uid),amt=num(c.args.find(x=>/^\$?[\d,]+$/.test(x)));if(!t)return c.reply("💡 Mention or reply to a user.");if(!amt)return c.reply("💡 !pay @user 50000");let v=U(t);if(u.cash<amt)return c.reply("❌ Not enough cash.");if(String(t)===String(c.uid))return c.reply("😂 You can't pay yourself.");u.cash-=amt;v.cash+=amt;c.reply(`💸 PAYMENT SENT\n👤 ${t}\n💰 ${money(amt)}\n🤝 Transfer complete.`)});
add("salary",c=>{let u=U(c.uid),r=CD(u,"salary",3600);if(r)return c.reply(`⏳ Salary available in ${Math.ceil(r/60)}m`);let amt=100000+u.level*10000;u.cash+=amt;c.reply(`💼 SALARY\n💰 +${money(amt)}\n⭐ Level bonus included.`)});
add("paytaxes",c=>{let u=U(c.uid),amt=Math.floor((u.cash+u.bank)*.05);if(!amt)return c.reply("✅ No tax due.");u.cash=Math.max(0,u.cash-amt);c.reply(`🏛️ TAX PAID\n💸 ${money(amt)}\n✅ Account cleared.`)});
add("vault_lock",c=>{let u=U(c.uid);u.vaultLocked=!u.vaultLocked;c.reply(`🔐 Vault lock: ${u.vaultLocked?"ON 🛡️":"OFF 🔓"}`)});
add("loan",c=>{let u=U(c.uid),amt=Math.min(5000000,num(c.args[0]));if(!amt)return c.reply("💡 !loan <amount>");if((u.loan||0)>0)return c.reply("❌ Existing loan must be cleared.");u.loan=amt;u.cash+=amt;c.reply(`🏦 LOAN APPROVED\n💰 +${money(amt)}\n📌 Repayment: ${money(Math.floor(amt*1.1))}`)});
add("credit_score",c=>{let u=U(c.uid);c.reply(`💳 CREDIT SCORE\n${u.credit}/850\n${BAR(u.credit,850)}\n📈 Pay loans and taxes to improve.`)});
add("wallet_upgrade",c=>{let u=U(c.uid),cost=u.level*100000;if(u.cash<cost)return c.reply(`❌ Need ${money(cost)}.`);u.cash-=cost;u.walletLevel=(u.walletLevel||1)+1;c.reply(`👛 WALLET UPGRADED Lv.${u.walletLevel}\n💰 -${money(cost)}`)});
add("invoice",c=>c.reply(`🧾 INVOICE SYSTEM\n${LIST(["Create invoice","View invoice","Pay invoice","Cancel invoice","Invoice history","Client list","Business invoice","Tax invoice","Recurring invoice","Invoice export"],1)}`));
add("charity_fund",c=>{let u=U(c.uid),a=num(c.args[0]);if(!a)return c.reply("💡 !charity_fund <amount>");if(u.cash<a)return c.reply("❌ Not enough cash.");u.cash-=a;u.reputation=(u.reputation||0)+Math.floor(a/10000);c.reply(`❤️ DONATION\n💰 ${money(a)} donated.\n⭐ Reputation +${Math.floor(a/10000)}`)});
add("pawn",c=>{let u=U(c.uid),item=c.args.slice(0,-1).join("_")||c.args[0],a=num(c.args[c.args.length-1]);if(!item||!a)return c.reply("💡 !pawn <item> <value>");u.cash+=a;D(u,`pawn:${item}`,-1);c.reply(`🏷️ Pawned ${item} for ${money(a)}.`)});
add("gold_bar",c=>{let u=U(c.uid),a=100000;if(u.cash<a)return c.reply("❌ Gold bar costs $100K.");u.cash-=a;D(u,"🥇 Gold Bar");c.reply("🥇 Gold Bar purchased for $100K.")});
add("audit",c=>{let u=U(c.uid);c.reply(`📊 PERSONAL AUDIT\n💰 Cash ${money(u.cash)}\n🏦 Bank ${money(u.bank)}\n🔐 Vault ${money(u.vault)}\n💎 Savings ${money(u.savings)}\n📈 Stocks ${Object.keys(u.stocks).length}\n🪙 Crypto ${Object.keys(u.crypto).length}`)});
add("subsidies",c=>c.reply(REWARD(c,100,50000,["🏛️ Subsidy","🎟️ Voucher","💎 Grant Gem"])));
add("bankruptcy",c=>{let u=U(c.uid);u.cash=0;u.bank=0;u.vault=0;u.savings=0;u.business=null;c.reply("⚠️ BANKRUPTCY FILED\n💸 Liquid assets reset.")});
add("insurance_buy",c=>{let u=U(c.uid),a=50000;if(u.cash<a)return c.reply("❌ Insurance costs $50K.");u.cash-=a;u.insurance=true;c.reply("🛡️ Economy insurance activated.")});
add("will_testament",c=>c.reply("📜 Testament registered. Your stored economy assets are marked for inheritance."));
add("offshore_trust",c=>{let u=U(c.uid),a=250000;if(u.cash<a)return c.reply("❌ Trust setup costs $250K.");u.cash-=a;u.trust=true;c.reply("🌐 Offshore trust established.")});
add("counterfeit|laundering|atm_hack",c=>{let u=U(c.uid),r=CD(u,"risk",600);if(r)return c.reply(`🚨 Heat cooldown: ${r}s`);let gain=100000+Math.floor(Math.random()*300000);u.cash+=gain;c.reply(`💸 OPERATION COMPLETE\n💰 +${money(gain)}\n⚠️ Risk generated.`)});

const STOCKS={vanguard:100,nvidia:180,tesla:150,apple:160,google:170,amazon:155,meta:140,microsoft:175,spacex:220,cyberdyne:300,starkcorp:400,wayneent:350,umbrella:275,robocorp:250};
add("stock_market",c=>c.reply(`📈 STOCK MARKET\n${LIST(Object.entries(STOCKS).map(([x,v])=>`${x.toUpperCase()} — ${money(v)}`),1)}`));
add("stock_buy",c=>{let u=U(c.uid),s=N(c.args[0]),q=Math.max(1,num(c.args[1])||1),p=STOCKS[s];if(!p)return c.reply("❌ Stock not found.");let cost=p*q;if(u.cash<cost)return c.reply("❌ Not enough cash.");u.cash-=cost;u.stocks[s]=(u.stocks[s]||0)+q;c.reply(`📈 BOUGHT\n${s.toUpperCase()} x${q}\n💰 -${money(cost)}`)});
add("stock_sell",c=>{let u=U(c.uid),s=N(c.args[0]),q=Math.max(1,num(c.args[1])||1),p=STOCKS[s]||0;if((u.stocks[s]||0)<q)return c.reply("❌ You don't own enough.");u.stocks[s]-=q;let gain=Math.floor(p*q*(.9+Math.random()*.3));u.cash+=gain;c.reply(`📉 SOLD\n${s.toUpperCase()} x${q}\n💰 +${money(gain)}`)});
add("stock_portfolio|stock_vanguard|stock_tesla|stock_apple|stock_google|stock_amazon|stock_meta|stock_nvidia|stock_microsoft|stock_spacex|stock_cyberdyne|stock_starkcorp|stock_wayneent|stock_umbrella|stock_robocorp|stock_insider|stock_options",c=>{let u=U(c.uid),n=N(c.event.body.split(/\s+/)[0].slice(1).replace("stock_",""));if(n==="portfolio")return c.reply(`📊 PORTFOLIO\n${Object.entries(u.stocks).map(([x,q])=>`${x}: ${q}`).join("\n")||"Empty."}`);let s=n==="vanguard"?"vanguard":n;if(!STOCKS[s])return c.reply("📈 Market information unavailable.");c.reply(`📈 ${s.toUpperCase()}\n💵 Price: ${money(STOCKS[s])}\n📊 Status: Trading`)});

const CRYPTO={btc:60000,eth:3000,sol:150,doge:.2,usdt:1,citycoin:5,darkcoin:25};
add("crypto_exchange",c=>c.reply(`🪙 CRYPTO EXCHANGE\n${LIST(Object.entries(CRYPTO).map(([x,v])=>`${x.toUpperCase()} — $${v.toLocaleString()}`),1)}`));
add("crypto_buy",c=>{let u=U(c.uid),s=N(c.args[0]),q=Math.max(.01,Number(c.args[1])||1),p=CRYPTO[s];if(!p)return c.reply("❌ Crypto not found.");let cost=p*q;if(u.cash<cost)return c.reply("❌ Not enough cash.");u.cash-=cost;u.crypto[s]=(u.crypto[s]||0)+q;c.reply(`🪙 BOUGHT ${s.toUpperCase()}\n📦 ${q}\n💰 -${money(cost)}`)});
add("crypto_sell",c=>{let u=U(c.uid),s=N(c.args[0]),q=Number(c.args[1])||1,p=CRYPTO[s];if(!p||(u.crypto[s]||0)<q)return c.reply("❌ Insufficient crypto.");u.crypto[s]-=q;let gain=p*q*(.9+Math.random()*.3);u.cash+=gain;c.reply(`🪙 SOLD ${s.toUpperCase()}\n💰 +${money(gain)}`)});
add("crypto_wallet|crypto_btc|crypto_eth|crypto_sol|crypto_doge|crypto_usdt|crypto_citycoin|crypto_darkcoin|crypto_nft|crypto_stake|crypto_rig|crypto_ico|crypto_rugpull|crypto_airdrop|crypto_futures|crypto_whale|crypto_hack",c=>{let u=U(c.uid),n=N(c.event.body.split(/\s+/)[0].slice(1).replace("crypto_",""));if(n==="wallet")return c.reply(`🪙 CRYPTO WALLET\n${Object.entries(u.crypto).map(([x,q])=>`${x.toUpperCase()}: ${q}`).join("\n")||"Empty."}`);let s=n;if(CRYPTO[s])return c.reply(`🪙 ${s.toUpperCase()}\n💵 Price: $${CRYPTO[s].toLocaleString()}\n📊 Market active.`);c.reply(`🪙 ${n.toUpperCase()}\n${REWARD(c,100,25000,["🪙 Crypto Token","💎 Digital Gem","🎁 Crypto Box"])}`)});

const ITEMS=["iron","wood","gold","diamond","gem","potion","weapon","armor","fish","crop"];
add("inventory|inv",c=>{let u=U(c.uid);c.reply(`🎒 INVENTORY\n${Object.entries(u.inventory).slice(0,10).map(([x,q])=>`${x} x${q}`).join("\n")||"Empty."}`)});
add("shop",c=>c.reply(`🛒 ECONOMY SHOP\n${LIST(["💎 Gem — $25K","🎁 Mystery Box — $50K","🪙 Token — $10K","🧪 Potion — $15K","⚔️ Weapon — $100K","🛡️ Armor — $100K","⛏️ Tool — $50K","🎟️ Ticket — $25K","🥇 Gold Bar — $100K","🏆 Trophy — $250K"],1)}\n💡 !price_check <item>`));
add("price_check",c=>{let n=N(c.args.join("_"));let prices={gem:25000,"mystery_box":50000,token:10000,potion:15000,weapon:100000,armor:100000,tool:50000,ticket:25000,"gold_bar":100000,trophy:250000};c.reply(`🏷️ ${n||"ITEM"}: ${money(prices[n]||25000)}`)});

add("market",c=>c.reply(`🏪 PLAYER MARKET\n${LIST(["💎 Gems","🎁 Boxes","⚔️ Weapons","🛡️ Armor","🐾 Pet Items","🌾 Crops","🎣 Fish","⛏️ Ores","🏆 Trophies","🪙 Tokens"],1)}\n💡 !market_search <item>`));
add("market_search",c=>c.reply(`🔎 MARKET SEARCH\n${LIST(ITEMS.map(x=>`${x} — ${money(10000+Math.random()*90000)}`),1)}`));
add("market_buy",c=>{let u=U(c.uid),item=N(c.args[0]),q=Math.max(1,num(c.args[1])||1),price=25000*q;if(u.cash<price)return c.reply("❌ Not enough cash.");u.cash-=price;D(u,item,q);c.reply(`🛒 PURCHASED\n📦 ${item} x${q}\n💰 -${money(price)}`)});
add("market_sell",c=>{let u=U(c.uid),item=N(c.args[0]),q=Math.max(1,num(c.args[1])||1);if((u.inventory[item]||0)<q)return c.reply("❌ You don't have enough.");u.inventory[item]-=q;let gain=15000*q;u.cash+=gain;c.reply(`💰 SOLD ${item} x${q}\n+$${gain.toLocaleString()}`)});
add("market_cancel|market_history|market_watch|trade|trade_offer|trade_accept|trade_decline|trade_cancel|auction|auction_create|auction_bid|auction_end|auction_history",c=>c.reply(`🏪 ${c.event.body.split(/\s+/)[0].slice(1).toUpperCase()}\nOperation registered.\n${REWARD(c,50,10000,["📜 Trade Receipt","🪙 Market Token","🎁 Trade Box"])}`));

add("business_buy",c=>{let u=U(c.uid);if(u.business)return c.reply("🏢 You already own a business.");let a=1000000;if(u.cash<a)return c.reply("❌ Business costs $1M.");u.cash-=a;u.business={name:c.args.join(" ")||"Klerk Enterprise",level:1,revenue:0,staff:0};c.reply(`🏢 BUSINESS ACQUIRED\n🏷️ ${u.business.name}\n💰 -$1M`)});
add("business_revenue",c=>{let u=U(c.uid);if(!u.business)return c.reply("❌ Buy a business first.");let a=u.business.level*150000+u.business.staff*25000;u.cash+=a;u.business.revenue+=a;c.reply(`🏢 BUSINESS REVENUE\n💰 +${money(a)}`)});
add("hire_npc",c=>{let u=U(c.uid);if(!u.business)return c.reply("❌ No business.");u.business.staff++;c.reply(`👔 Employee hired.\n👥 Staff: ${u.business.staff}`)});
add("fire_npc",c=>{let u=U(c.uid);if(!u.business?.staff)return c.reply("❌ No staff.");u.business.staff--;c.reply("👋 Employee dismissed.")});
add("upgrade_tech|franchise|supply_chain|marketing|bribe_official|corporate_raid|shares_issue|real_estate|permit_apply|headquarters|union_negotiate|corporate_bonds|merger|vandalize_rival|business_sell|insure_business",c=>{let u=U(c.uid);if(!u.business&&N(c.event.body.split(/\s+/)[0].slice(1))!=="real_estate")return c.reply("❌ Buy a business first.");if(N(c.event.body.split(/\s+/)[0].slice(1))==="business_sell"){let v=500000+(u.business?.level||1)*250000;u.cash+=v;u.business=null;return c.reply(`🏢 BUSINESS SOLD\n💰 +${money(v)}`)}u.business.level++;c.reply(`🏢 BUSINESS ACTION COMPLETE\n📈 Business Lv.${u.business.level}\n${REWARD(c,150,50000,["📊 Business Token","💎 Corporate Gem","📜 Permit"])}`)});

add("home",c=>{let u=U(c.uid);c.reply(`🏠 HOME\n${u.properties.length?u.properties.map(x=>`🏡 ${x.name} Lv.${x.level}`).join("\n"):"No property owned."}`)});
add("home_upgrade",c=>{let u=U(c.uid),h=u.properties[0];if(!h)return c.reply("🏠 Buy a property first.");let cost=h.level*250000;if(u.cash<cost)return c.reply(`❌ Need ${money(cost)}.`);u.cash-=cost;h.level++;c.reply(`🏡 HOME UPGRADED Lv.${h.level}`)});
add("home_storage|home_enter|home_exit|room_create|room_upgrade|furniture|buy_furniture|place_furniture|remove_furniture|house_party|guest_list|neighbor|neighborhood_chat|rent|tenant|landlord|property_market|property_tax|home_security|home_alarm",c=>{let u=U(c.uid);if(N(c.event.body.split(/\s+/)[0].slice(1))==="property_market")return c.reply(`🏘️ PROPERTY MARKET\n${LIST(["Apartment — $500K","House — $1M","Villa — $2.5M","Penthouse — $5M","Farmhouse — $750K","Mansion — $10M","Beach House — $7M","Mountain Lodge — $4M","City Loft — $1.5M","Island Estate — $25M"],1)}`);c.reply(`🏠 ${c.event.body.split(/\s+/)[0].slice(1).toUpperCase()}\nAction completed.\n${REWARD(c,75,25000,["🏠 Home Token","🪑 Furniture","🔑 Property Key"])}`)});

add("lb|richest|top",c=>{let a=[...P.values()].sort((x,y)=>(y.cash+y.bank+y.vault+y.savings)-(x.cash+x.bank+x.vault+x.savings)).slice(0,10);c.reply(`🏆 WEALTH LEADERBOARD\n${a.map((u,i)=>`${i+1}. 👤 ${u.id} — ${money(u.cash+u.bank+u.vault+u.savings)}`).join("\n")||"No players yet."}`)});
add("economy_status",c=>{let u=U(c.uid);c.reply(`💹 ECONOMY STATUS\n💰 Net Worth: ${money(u.cash+u.bank+u.vault+u.savings)}\n🏦 Bank: ${money(u.bank)}\n🔐 Vault: ${money(u.vault)}\n💎 Savings: ${money(u.savings)}\n📈 Stocks: ${Object.keys(u.stocks).length}\n🪙 Crypto: ${Object.keys(u.crypto).length}`)});
add("money_status",c=>C.economy_status.execute(c));

module.exports=Object.values(C);
