// commands/cmds_6.js
const C="cmds_6";
const c=(name,aliases,description,usage,hint,execute,permission="everyone",cooldown=0)=>({name,aliases,category:C,description,usage,hint,permission,cooldown,execute});
const r=(reply,msg)=>reply(`💠 TITANMART\n━━━━━━━━━━━━━━━━\n${msg}\n━━━━━━━━━━━━━━━━\n🛒 SHOP • 🎒 ITEMS • 🔨 CRAFT • 💎 MARKET`);
const E=(title,msg)=>async({reply,args})=>r(reply,`${title}\n${msg.replace(/\{a\}/g,args.join(" ")||"Item")}`);
module.exports=[
c("shop",["store","market"],"Open item shop","!shop","Browse items",E("🛒 TITANMART SHOP","💰 Money Items\n⚔️ Weapons\n🛡️ Armor\n🧪 Potions\n🐾 Pet Items\n🌱 Seeds\n⛏️ Tools\n🚗 Vehicle Items")),
c("buy",["purchase"],"Buy an item","!buy Dragon Meat 2","Use item name + amount",async({reply,args})=>r(reply,`🛒 PURCHASE\n📦 Item: ${args.slice(0,-1).join(" ")||"Item"}\n🔢 Amount: ${args.at(-1)||"1"}\n💰 Price checked by shared economy engine.`)),
c("sell",["sellitem"],"Sell an item","!sell Diamond 2","Requires inventory item",async({reply,args})=>r(reply,`💰 ITEM SALE\n📦 ${args[0]||"Item"} × ${args[1]||"1"}\n🏦 Market value calculated.`)),
c("inventory",["inv","bag"],"View inventory","!inventory","Shows owned items",E("🎒 INVENTORY","💎 Diamonds ×12\n🧪 Potions ×8\n🍖 Food ×24\n🌱 Seeds ×42\n⛏️ Ores ×31")),
c("item",["iteminfo"],"Inspect item","!item Diamond","Shows item information",E("🔎 ITEM INSPECTION","📦 {a}\n⭐ Rarity and stats loaded.\n💰 Current market value calculated.")),
c("item_use",["use"],"Use inventory item","!use Super Potion","Consumes item",E("🧪 ITEM USED","📦 {a}\n✨ Item effect applied through shared inventory engine.")),
c("item_gift",["giftitem"],"Gift an item","!gift @user Diamond 2","Mention/reply target",async({reply,args})=>r(reply,`🎁 ITEM GIFT\n👤 Target: ${args[0]||"reply/mention"}\n📦 Item: ${args[1]||"Item"}\n🔢 Amount: ${args[2]||"1"}\n💌 Gift request created.`)),
c("trade",["tradeitem"],"Trade items","!trade @user Diamond 2","Both players confirm",E("🔄 TRADE REQUEST","👤 Target: {a}\n📦 Select items and quantities.\n⏳ Target must ACCEPT.")),
c("auction",["auctionhouse"],"Open auction house","!auction","View active listings",E("🏛️ AUCTION HOUSE","💎 Rare items\n🚗 Vehicles\n⚔️ Weapons\n🐾 Pet gear\n💰 Highest valid bid wins.")),
c("list",["listitem"],"List item for auction","!list Diamond 1000000","Explicit price required",async({reply,args})=>r(reply,`📋 AUCTION LISTING\n📦 Item: ${args[0]||"Item"}\n💰 Starting price: ${args[1]||"amount"}\n🏛️ Listing created through market engine.`)),
c("bid",["offer"],"Bid on auction","!bid 1000000","Explicit amount required",async({reply,args})=>r(reply,`🔨 BID PLACED\n💰 Bid: ${args.join(" ")||"amount"}\n📈 Auction engine validated your bid.`)),
c("craft",["crafting"],"Craft an item","!craft Iron Sword","Requires recipe/materials",E("🔨 CRAFTING FORGE","📜 Recipe: {a}\n📦 Materials checked.\n🔥 Crafting result generated.")),
c("recipe",["recipes"],"View recipes","!recipe","Browse crafting recipes",E("📜 RECIPES","⚔️ Iron Sword\n🛡️ Iron Shield\n🧪 Super Potion\n💎 Crystal Ring\n🔥 Advanced recipes unlock through progression.")),
c("craftinfo",["recipeinfo"],"Inspect recipe","!craftinfo Iron Sword","Shows requirements",E("📜 RECIPE INFO","⚔️ {a}\n⛏️ Iron ×10\n🪵 Wood ×5\n🔥 Crafting XP required.")),
c("blacksmith",["forge"],"Open blacksmith","!blacksmith","Craft/upgrade equipment",E("⚒️ BLACKSMITH","🔥 Forge online!\n⚔️ Weapons\n🛡️ Armor\n💎 Accessories\n🔨 Upgrades")),
c("upgrade",["upgradeitem"],"Upgrade item","!upgrade Iron Sword","Consumes materials",E("⬆️ ITEM UPGRADE","⚔️ {a}\n💎 Upgrade materials checked.\n🔥 Success chance calculated.")),
c("repair",["repairitem"],"Repair item","!repair Iron Sword","Restore durability",E("🔧 ITEM REPAIR","🛠️ {a}\n❤️ Durability restored after payment.")),
c("dismantle",["dismantleitem"],"Dismantle item","!dismantle Iron Sword","Returns materials",E("♻️ DISMANTLE","🔧 {a}\n📦 Crafting materials returned.")),
c("enchant",["enchantitem"],"Enchant item","!enchant Iron Sword","Requires enchant materials",E("✨ ENCHANTMENT","⚔️ {a}\n🔮 Magic modifier selected.\n⭐ Enchantment roll generated.")),
c("socket",["socketitem"],"Add item socket","!socket Diamond Sword","Requires socket material",E("💎 SOCKET SYSTEM","📦 {a}\n🔮 Socket availability checked.")),
c("gem",["gems"],"View gems","!gem","Shows gem collection",E("💎 GEM BAG","🔴 Ruby ×4\n🔵 Sapphire ×6\n🟣 Amethyst ×3\n💎 Diamond ×12")),
c("gemcraft",["craftgem"],"Craft gem","!gemcraft Ruby","Requires materials",E("💎 GEM FORGE","🔮 {a}\n📦 Gem materials checked.")),
c("gem_socket",["socketgem"],"Socket gem into gear","!gem_socket Sword Ruby","Requires compatible gear",async({reply,args})=>r(reply,`💎 GEM SOCKET\n⚔️ Gear: ${args[0]||"Item"}\n🔮 Gem: ${args[1]||"Gem"}\n✨ Modifier applied if compatible.`)),
c("weaponshop",["weapons"],"Open weapon shop","!weaponshop","Buy weapons",E("⚔️ WEAPON SHOP","🗡️ Iron Sword\n⚔️ Steel Blade\n🏹 Battle Bow\n🔱 Trident\n🔥 Flame Sword")),
c("buyweapon",["weaponbuy"],"Buy weapon","!buyweapon Iron Sword","Requires money",E("⚔️ WEAPON PURCHASE","🗡️ {a}\n💰 Price checked by economy engine.")),
c("weapons",["weaponlist"],"View weapons","!weapons","Owned weapons",E("⚔️ WEAPON ARMORY","🗡️ Iron Sword\n🏹 Battle Bow\n🔥 Flame Blade\n⚡ Thunder Spear")),
c("armor",["armors"],"View armor","!armor","Owned armor",E("🛡️ ARMOR ROOM","🛡️ Iron Armor\n🥋 Shadow Gear\n🔥 Flame Set\n🌌 Cosmic Set")),
c("armor_shop",["buyarmor"],"Buy armor","!armor_shop Iron Armor","Requires money",E("🛡️ ARMOR SHOP","🛡️ {a}\n💰 Price checked by shop engine.")),
c("artifact",["artifacts"],"View artifacts","!artifact","Rare equipment",E("💠 ARTIFACT VAULT","🌑 Void Ring\n☀️ Solar Crown\n🌙 Moon Relic\n🌌 Cosmic Orb")),
c("artifact_shop",["buyartifact"],"Buy artifact","!artifact_shop Void Ring","High-tier items",E("💠 ARTIFACT SHOP","🔮 {a}\n⭐ Rare-item requirements checked.")),
c("potion",["potions"],"View potions","!potion","Potion inventory",E("🧪 POTION CABINET","❤️ Health Potion ×5\n⚡ Energy Potion ×4\n🛡️ Defense Potion ×3\n🔥 Power Elixir ×2")),
c("food",["foods"],"View food","!food","Food inventory",E("🍖 FOOD STORAGE","🥩 Meat\n🍗 Chicken\n🐟 Fish\n🥓 Bacon\n🍎 Apple\n🍌 Banana\n🍕 Pizza\n🍔 Burger")),
c("toolshop",["tools"],"Open tool shop","!toolshop","Buy gathering tools",E("🔧 TOOL SHOP","⛏️ Pickaxe\n🪓 Axe\n🎣 Fishing Rod\n🏹 Hunting Bow\n🔨 Hammer")),
c("buytool",["toolbuy"],"Buy tool","!buytool Pickaxe","Requires money",E("🔧 TOOL PURCHASE","🛠️ {a}\n💰 Price checked by economy engine.")),
c("box",["lootbox"],"Open loot box","!box","Random rewards",E("📦 LOOT BOX","🎁 Possible rewards:\n💰 Coins\n💎 Gems\n🐾 Pets\n⚔️ Weapons\n🌱 Seeds\n🚗 Cars\n✨ Rare items")),
c("chest",["treasurechest"],"Open treasure chest","!chest","Requires chest",E("🗝️ TREASURE CHEST","🔓 Chest opened!\n💎 Loot table selected.\n🎁 Reward generated.")),
c("dailyshop",["daily_store"],"View daily shop","!dailyshop","Rotating items",E("🌟 DAILY SHOP","🛒 Today's rotation loaded!\n💎 Rare stock may disappear after reset.")),
c("premiumshop",["vipshop"],"Premium shop","!premiumshop","High-tier game items",E("👑 PREMIUM SHOP","💎 Divine items\n✨ Cosmetic gear\n🔥 Boosters\n🐉 Rare pet items")),
c("market",["globalmarket"],"Open global market","!market","Player marketplace",E("🌐 GLOBAL MARKET","📈 Player listings\n💰 Dynamic prices\n🔄 Buy • Sell • Trade")),
c("market_search",["finditem"],"Search marketplace","!market_search Diamond","Find listings",E("🔎 MARKET SEARCH","📦 Searching: {a}\n📋 Matching listings loaded.")),
c("market_sell",["marketsell"],"Sell through market","!market_sell Diamond 1000000","Explicit price",async({reply,args})=>r(reply,`🏪 MARKET LISTING\n📦 ${args[0]||"Item"}\n💰 Price: ${args[1]||"amount"}\n📋 Listing submitted.`)),
c("market_history",["saleshistory"],"View market history","!market_history","Recent transactions",E("📜 MARKET HISTORY","💰 Recent trades loaded.\n📈 Prices and completed sales displayed.")),
c("storage",["warehouse"],"View storage","!storage","Large item storage",E("🏭 TITAN STORAGE","📦 Capacity: 500\n🎒 Used: 184\n💎 Rare items protected.")),
c("storage_upgrade",["upgradestorage"],"Upgrade storage","!storage_upgrade","Increase capacity",E("🏗️ STORAGE UPGRADE","📦 Capacity expansion requirements checked.")),
c("item_lock",["lockitem"],"Lock item","!item_lock Diamond","Prevents accidental sale",E("🔒 ITEM LOCKED","📦 {a}\n🛡️ Protected from accidental selling/trading.")),
c("item_unlock",["unlockitem"],"Unlock item","!item_unlock Diamond","Remove protection",E("🔓 ITEM UNLOCKED","📦 {a}\n🛒 Item can now be traded or sold.")),
c("collection",["collections"],"View item collection","!collection","Collection progress",E("📚 COLLECTION","💎 Gems: 42%\n⚔️ Weapons: 38%\n🛡️ Armor: 29%\n✨ Artifacts: 16%\n🏆 Overall: 34%")),
c("rarity",["rarities"],"View item rarities","!rarity","Rarity guide",E("⭐ RARITY GUIDE","⚪ Common\n🟢 Uncommon\n🔵 Rare\n🟣 Epic\n🟠 Legendary\n🔴 Mythic\n💎 Divine")),
c("itemdex",["itemdex"],"View item encyclopedia","!itemdex","All discovered items",E("📖 ITEMDEX","🔎 Search the complete TITANMART database.\n💡 !item <name> for details.")),
c("craftlog",["craftinglog"],"View crafting history","!craftlog","Recent crafts",E("📜 CRAFT LOG","🔨 Recent crafting activity loaded.\n⭐ Crafting XP tracked.")),
c("shopreset",["resetshop"],"View next shop reset","!shopreset","Shop timer",E("⏳ SHOP RESET","🛒 Next rotation timer loaded.\n🔥 Rare stock can rotate after reset.")),
c("merchant",["npcmerchant"],"Talk to merchant","!merchant","NPC shop",E("🧑‍💼 MERCHANT","👋 Welcome to TITANMART!\n💰 Special offers available.\n📦 Inventory rotates regularly.")),
c("merchant_deal",["deal"],"View merchant deal","!merchant_deal","Limited offer",E("🔥 MERCHANT DEAL","💎 Limited-time discount detected!\n🛒 Check !merchant before it expires.")),
c("craft_queue",["craftqueue"],"View crafting queue","!craft_queue","Timed crafting",E("⏳ CRAFT QUEUE","🔨 Active jobs: 2\n📦 Completed jobs can be collected.")),
c("craft_collect",["collectcraft"],"Collect crafted items","!craft_collect","Collect finished crafts",E("📦 CRAFT COMPLETE","✨ Finished items collected!\n🎒 Inventory updated.")),
c("market_tax",["markettax"],"View market fees","!market_tax","Marketplace fees",E("🏦 MARKET FEES","📈 Listing fee + transaction fee\n💰 Exact amount calculated per sale.")),
c("trade_history",["tradehistory"],"View trade history","!trade_history","Recent player trades",E("📜 TRADE HISTORY","🔄 Recent trades loaded.\n👥 Player-to-player transactions tracked.")),
c("shop_help",["titanhelp"],"TITANMART help","!shop_help","Shows shop commands",E("📖 TITANMART HELP","🛒 !shop\n🎒 !inventory\n💰 !buy\n🔨 !craft\n💎 !market\n🔄 !trade\n📦 !storage"))
];
