// commands/cmds_3.js
// 🐾 WILDHEART — iKON-BOT
module.exports=({api,event,user,reply,users,profile,fun})=>{
const replyx=t=>api.sendMessage(t,event.threadID,()=>{},event.messageID);
const xp=(u,n=5)=>{u.xp=(u.xp||0)+n;};
const ensure=u=>{u.pets=u.pets||[];u.inventory=u.inventory||{};u.petSlots=u.petSlots||3;};
const petNames=["Wolf","Tiger","Lion","Eagle","Bear","Fox","Panther","Dragon","Phoenix","Griffin","Cerberus","Leviathan","Kitsune","Hydra","Titan","Shadow Wolf","Inferno Dragon","Divine Phoenix"];
const rarity=["Common","Uncommon","Rare","Epic","Legendary","Mythic","Divine"];
const rand=a=>a[Math.floor(Math.random()*a.length)];
const petPower=p=>Math.floor((p.level||1)*20+(p.xp||0)/10+(p.bonus||0));
const findPet=(u,q)=>{ensure(u);q=String(q||"").toLowerCase();return u.pets.find(p=>p.id===q||p.name.toLowerCase()===q||String(p.id).toLowerCase()===q)||u.pets[Number(q)-1]};
const newPet=()=>({id:Math.random().toString(36).slice(2,8),name:rand(petNames),rarity:rand(rarity.slice(0,5)),level:1,xp:0,hp:100,maxHp:100,energy:100,power:20,bonus:0,armor:0,weapon:null,food:0,quests:0});
const cmds=[
{name:"pet",aliases:["mypet"],description:"View your main pet",run:async()=>{ensure(user);let p=user.pets[0];replyx(p?`🐾 ${p.name}\n✨ ${p.rarity} • Lv.${p.level}\n❤️ ${p.hp}/${p.maxHp} • ⚡ ${p.energy}/100\n⚔️ Power: ${petPower(p)}`:"🐾 You have no pet. Use !adopt.")}},
{name:"pets",aliases:["petlist"],description:"View all pets",run:async()=>{ensure(user);replyx(user.pets.length?`🐾 YOUR PETS\n${user.pets.map((p,i)=>`${i+1}. ${p.name} • ${p.rarity} • Lv.${p.level} • ⚔️${petPower(p)}`).join("\n")}`:"🐾 No pets yet.")}},
{name:"adopt",aliases:["adoptpet"],description:"Adopt a random pet",run:async()=>{ensure(user);if(user.pets.length>=user.petSlots)return replyx(`❌ Pet slots full (${user.petSlots}).`);let p=newPet();user.pets.push(p);xp(user,15);replyx(`🐾 NEW PET!\n${p.name} • ${p.rarity}\n⚔️ Power: ${petPower(p)}\n⭐ +15 XP`)}},
{name:"petinfo",aliases:["petdetails"],description:"View pet details",run:async({args})=>{let p=findPet(user,args.join(" "));if(!p)return replyx("❌ Pet not found.");replyx(`🐾 ${p.name}\nRarity: ${p.rarity}\nLevel: ${p.level}\nXP: ${p.xp||0}\n❤️ ${p.hp}/${p.maxHp}\n⚡ ${p.energy}/100\n⚔️ Power: ${petPower(p)}\n🛡️ Armor: ${p.armor||0}`)}},
{name:"feed",aliases:["petfeed"],description:"Feed your pet",run:async({args})=>{ensure(user);let p=findPet(user,args.join(" "))||user.pets[0];if(!p)return replyx("❌ You have no pet.");if((user.inventory.apple||0)<=0&&(user.inventory.fish||0)<=0&&(user.inventory.bread||0)<=0)return replyx("🍖 You need food.");let item=user.inventory.fish?"fish":user.inventory.bread?"bread":"apple";user.inventory[item]--;p.energy=Math.min(100,p.energy+15);p.hp=Math.min(p.maxHp,p.hp+10);p.xp+=10;replyx(`🍖 ${p.name} enjoyed the ${item}!\n❤️ +10 HP • ⚡ +15 Energy`)}},
{name:"train",aliases:["pettrain"],description:"Train a pet",run:async({args})=>{let p=findPet(user,args.join(" "))||user.pets[0];if(!p)return replyx("❌ No pet.");if(p.energy<20)return replyx("⚡ Pet needs at least 20 energy.");p.energy-=20;p.xp+=25;p.bonus=(p.bonus||0)+2;if(p.xp>=p.level*100){p.xp-=p.level*100;p.level++;p.maxHp+=10;p.hp=p.maxHp;replyx(`🔥 ${p.name} LEVEL UP!\n⭐ Level ${p.level}\n⚔️ Power ${petPower(p)}`)}else replyx(`🏋️ ${p.name} trained!\n⭐ +25 XP\n⚔️ +2 Power`);xp(user,10)}},
{name:"evolve",aliases:["petevolve"],description:"Evolve a pet",run:async({args})=>{let p=findPet(user,args.join(" "))||user.pets[0];if(!p)return replyx("❌ No pet.");if(p.level<10)return replyx("🔒 Pet needs level 10.");let order=rarity.indexOf(p.rarity);if(order>=rarity.length-1)return replyx("👑 This pet is already Divine.");if((user.inventory.evolution_stone||0)<1)return replyx("💎 Need 1 Evolution Stone.");user.inventory.evolution_stone--;p.rarity=rarity[order+1];p.bonus=(p.bonus||0)+50;p.maxHp+=50;p.hp=p.maxHp;replyx(`✨ EVOLUTION!\n🐾 ${p.name} → ${p.rarity}\n⚔️ +50 Power`)}},
{name:"petbattle",aliases:["petfight"],description:"Battle another user's pet",run:async({args})=>{let target=event.mentions&&Object.keys(event.mentions)[0];if(!target)return replyx("⚔️ Tag an opponent.");let other=users.get(target);if(!other)return replyx("❌ Opponent not found.");ensure(user);ensure(other);let a=user.pets[0],b=other.pets[0];if(!a||!b)return replyx("❌ Both players need pets.");let ap=petPower(a)+Math.floor(Math.random()*50),bp=petPower(b)+Math.floor(Math.random()*50);replyx(`⚔️ PET BATTLE\n🐾 ${a.name}: ${ap}\n🐾 ${b.name}: ${bp}\n🏆 ${ap>=bp?"You":"Opponent"} wins!`);a.energy=Math.max(0,a.energy-20);b.energy=Math.max(0,b.energy-20);xp(user,20)}},
{name:"pettrade",aliases:["tradepet"],description:"Trade a pet with another user",run:async({args})=>{let target=event.mentions&&Object.keys(event.mentions)[0];if(!target)return replyx("🤝 Tag a player.");let other=users.get(target);if(!other)return replyx("❌ User not found.");ensure(user);ensure(other);if(user.pets.length<=0)return replyx("❌ You have no pet.");let p=user.pets.pop();if(other.pets.length>=other.petSlots){user.pets.push(p);return replyx("❌ Their pet slots are full.");}other.pets.push(p);replyx(`🤝 You traded ${p.name}.`)}},
{name:"release",aliases:["releasepet"],description:"Release a pet",run:async({args})=>{ensure(user);let i=Number(args[0]);if(!Number.isInteger(i)||!user.pets[i-1])return replyx("Usage: !release <pet number>");let p=user.pets.splice(i-1,1)[0];replyx(`🌲 ${p.name} has been released.`)}},
{name:"petstats",aliases:["pstats"],description:"Pet statistics",run:async()=>{ensure(user);let power=user.pets.reduce((s,p)=>s+petPower(p),0);replyx(`📊 PET STATS\n🐾 Pets: ${user.pets.length}\n⚔️ Total Power: ${power}\n🏆 Highest: ${Math.max(0,...user.pets.map(p=>petPower(p)))}`)}},
{name:"petlevel",aliases:["plevel"],description:"View pet level progress",run:async({args})=>{let p=findPet(user,args.join(" "))||user.pets[0];if(!p)return replyx("❌ No pet.");replyx(`⭐ ${p.name}\nLevel: ${p.level}\nXP: ${p.xp}/${p.level*100}\nProgress: ${Math.floor((p.xp/(p.level*100))*100)}%`)}},
{name:"petxp",aliases:["pxp"],description:"Give pet XP",run:async({args})=>{let p=findPet(user,args.join(" "))||user.pets[0];if(!p)return replyx("❌ No pet.");p.xp+=50;replyx(`⭐ ${p.name} gained 50 XP.`)}},
{name:"petheal",aliases:["pheal"],description:"Heal a pet",run:async({args})=>{let p=findPet(user,args.join(" "))||user.pets[0];if(!p)return replyx("❌ No pet.");if((user.inventory.healing_potion||0)<1)return replyx("🧪 Need a Healing Potion.");user.inventory.healing_potion--;p.hp=p.maxHp;replyx(`❤️ ${p.name} is fully healed.`)}},
{name:"petpower",aliases:["ppower"],description:"Show pet power",run:async({args})=>{let p=findPet(user,args.join(" "))||user.pets[0];if(!p)return replyx("❌ No pet.");replyx(`⚔️ ${p.name} Power: ${petPower(p)}`)}},
{name:"petduel",aliases:["pduel"],description:"Duel a random pet",run:async()=>{let p=user.pets?.[0];if(!p)return replyx("❌ Adopt a pet first.");let enemy=newPet();let a=petPower(p)+Math.floor(Math.random()*30),b=petPower(enemy)+Math.floor(Math.random()*30);p.energy=Math.max(0,p.energy-15);if(a>=b){xp(user,30);replyx(`⚔️ DUEL WON!\n${p.name} defeated ${enemy.name}.\n⭐ +30 XP`)}else replyx(`💀 DUEL LOST!\n${enemy.name} defeated ${p.name}.`)}},
{name:"petgift",aliases:["giftpet"],description:"Gift a pet",run:async({args})=>{let target=event.mentions&&Object.keys(event.mentions)[0];if(!target)return replyx("🎁 Tag someone.");let other=users.get(target);ensure(user);ensure(other);if(!user.pets.length)return replyx("❌ No pet.");if(other.pets.length>=other.petSlots)return replyx("❌ Their slots are full.");let p=user.pets.pop();other.pets.push(p);replyx(`🎁 Gifted ${p.name}.`)}},
{name:"petrename",aliases:["renamepet"],description:"Rename a pet",run:async({args})=>{let p=findPet(user,args[0])||user.pets[0];let name=args.slice(1).join(" ");if(!p||!name)return replyx("Usage: !petrename <number> <name>");p.name=name.slice(0,25);replyx(`✏️ Pet renamed to ${p.name}.`)}},
{name:"petcollection",aliases:["petbook"],description:"View pet collection",run:async()=>{ensure(user);let unique=new Set(user.pets.map(p=>p.name)).size;replyx(`📚 PET COLLECTION\nOwned: ${user.pets.length}\nUnique Species: ${unique}`)}},
{name:"petrare",aliases:["rarepet"],description:"Show rare pets",run:async()=>{ensure(user);let r=user.pets.filter(p=>["Legendary","Mythic","Divine"].includes(p.rarity));replyx(r.length?`🌟 RARE PETS\n${r.map(p=>`${p.name} • ${p.rarity}`).join("\n")}`:"❌ No rare pets.")}},
{name:"petbreed",aliases:["breed"],description:"Breed two pets",run:async({args})=>{ensure(user);if(user.pets.length<2)return replyx("🐾 Need at least 2 pets.");let a=user.pets[Number(args[0])-1],b=user.pets[Number(args[1])-1];if(!a||!b||a===b)return replyx("Usage: !petbreed <pet1> <pet2>");if(user.pets.length>=user.petSlots)return replyx("❌ No free pet slot.");let child=newPet();child.name=`${a.name}-${b.name}`.slice(0,20);child.rarity=rarity[Math.min(rarity.indexOf(a.rarity),rarity.indexOf(b.rarity))];user.pets.push(child);replyx(`🥚 BREEDING SUCCESS!\n🐾 ${child.name}\n✨ ${child.rarity}`)}},
{name:"petmerge",aliases:["mergepets"],description:"Merge duplicate pets",run:async()=>{ensure(user);if(user.pets.length<2)return replyx("❌ Need 2 pets.");let a=user.pets[0],b=user.pets[1];if(a.rarity!==b.rarity)return replyx("❌ Pets must have the same rarity.");a.bonus=(a.bonus||0)+(b.bonus||0)+25;a.xp+=b.xp||0;user.pets.splice(1,1);replyx(`🔮 ${a.name} absorbed another pet!\n⚔️ +25 Power`)}},
{name:"petrevive",aliases:["revivepet"],description:"Revive a defeated pet",run:async({args})=>{let p=findPet(user,args.join(" "))||user.pets[0];if(!p)return replyx("❌ No pet.");if(p.hp>0)return replyx("❤️ Your pet is already alive.");p.hp=Math.floor(p.maxHp*.5);replyx(`✨ ${p.name} has been revived.`)}},
{name:"petarmor",aliases:["armorpet"],description:"Equip pet armor",run:async({args})=>{let p=findPet(user,args.join(" "))||user.pets[0];if(!p)return replyx("❌ No pet.");if((user.inventory.steel_armor||0)<1)return replyx("🛡️ Need Steel Armor.");user.inventory.steel_armor--;p.armor=(p.armor||0)+50;p.bonus=(p.bonus||0)+20;replyx(`🛡️ ${p.name} equipped Steel Armor.`)}},
{name:"petweapon",aliases:["weaponpet"],description:"Equip a pet weapon",run:async({args})=>{let p=findPet(user,args.join(" "))||user.pets[0];if(!p)return replyx("❌ No pet.");if((user.inventory.iron_sword||0)<1)return replyx("⚔️ Need an Iron Sword.");user.inventory.iron_sword--;p.weapon="Iron Sword";p.bonus=(p.bonus||0)+40;replyx(`⚔️ ${p.name} equipped Iron Sword.`)}},
{name:"petquest",aliases:["petquests"],description:"Complete a pet quest",run:async()=>{let p=user.pets?.[0];if(!p)return replyx("❌ Adopt a pet.");p.quests=(p.quests||0)+1;p.xp+=40;let reward=3000+p.quests*500;user.wallet=(user.wallet||0)+reward;replyx(`🗺️ PET QUEST COMPLETE!\n💰 +$${reward.toLocaleString()}\n⭐ +40 Pet XP`)}},
{name:"petmission",aliases:["petmissions"],description:"Send pet on mission",run:async()=>{let p=user.pets?.[0];if(!p)return replyx("❌ No pet.");if(p.energy<30)return replyx("⚡ Pet needs 30 energy.");p.energy-=30;let reward=5000+petPower(p)*5;user.wallet=(user.wallet||0)+reward;p.xp+=50;replyx(`🗺️ Mission complete!\n🐾 ${p.name}\n💰 +$${reward.toLocaleString()}\n⭐ +50 XP`)}},
{name:"petfood",aliases:["petfoods"],description:"View pet food",run:async()=>replyx("🍖 PET FOOD\n• Apple — +3 HP\n• Bread — +6 HP\n• Fish — +10 HP\nFeed pets with !feed.")},
{name:"petgear",aliases:["petitems"],description:"View pet equipment",run:async()=>replyx("⚔️ PET GEAR\n• Iron Sword — +40 Power\n• Steel Armor — +20 Power +50 Armor\nUse !petweapon or !petarmor.")},
{name:"petsearch",aliases:["findpet"],description:"Search your pets",run:async({args})=>{ensure(user);let q=args.join(" ").toLowerCase();let r=user.pets.filter(p=>p.name.toLowerCase().includes(q)||p.rarity.toLowerCase().includes(q));replyx(r.length?`🔎 PET SEARCH\n${r.map(p=>`${p.name} • ${p.rarity} • Lv.${p.level}`).join("\n")}`:"❌ No matching pet.")}},
{name:"petleaderboard",aliases:["petlb","petleaders"],description:"Pet power leaderboard",run:async()=>{let list=[...users.values()].map(u=>({name:u.name||u.uid,p:(u.pets||[]).reduce((s,p)=>s+petPower(p),0)})).sort((a,b)=>b.p-a.p).slice(0,10);replyx(`🏆 PET POWER LB\n${list.map((x,i)=>`${i+1}. ${x.name} — ⚔️${x.p}`).join("\n")}`)}},
{name:"petstatus",aliases:["pstatus"],description:"Pet health and energy",run:async()=>{let p=user.pets?.[0];if(!p)return replyx("❌ No pet.");replyx(`🐾 ${p.name}\n❤️ ${p.hp}/${p.maxHp}\n⚡ ${p.energy}/100\n🛡️ ${p.armor||0}\n⚔️ ${petPower(p)}`)}},
{name:"petreset",aliases:["resetpet"],description:"Reset pet training bonus",run:async()=>{let p=user.pets?.[0];if(!p)return replyx("❌ No pet.");p.bonus=0;p.energy=100;replyx(`🔄 ${p.name}'s training bonus was reset.`)}},
{name:"pethunt",aliases:["petadventure"],description:"Send pet hunting",run:async()=>{let p=user.pets?.[0];if(!p)return replyx("❌ No pet.");if(p.energy<25)return replyx("⚡ Need 25 energy.");p.energy-=25;let reward=Math.floor(Math.random()*7000)+1000;user.wallet=(user.wallet||0)+reward;p.xp+=20;replyx(`🌲 HUNT COMPLETE!\n🐾 ${p.name} found $${reward.toLocaleString()}!\n⭐ +20 XP`)}},
{name:"pethelp",aliases:["petcommands"],description:"Pet command help",run:async()=>replyx("🐾 WILDHEART\n!pet • !pets • !adopt • !petinfo • !feed • !train • !evolve • !petbattle • !pettrade • !petquest • !petmission • !petbreed • !petmerge")}
];
return cmds;
};
