const P=["level_xp","rank_rewards","prestige","rebirth","passport","achieve_total","skills_tree","title_shop","legacy_score","badge_case","perk_activate","profile_glow","stat_allocate","mastery_loop","career_level","season_pass","booster_pack","codex","witness_prot","citizen_oath","tasks_daily","tasks_weekly","quests_main","quests_side","quest_inventory","faction_quest","bounty_board","milestones","achieve_hunt","campaign_stats","reply_box","loading_bar","font_buffer","popup_engine","menu_style","auto_reaction","ui_divider","color_matrix","canvas_render","text_compress","panel_layout","emoji_palette","hud_display","render_clear","house_buy","house_sell","decorate","upgrade_yard","invite_guest","estate_tax","mansion_vault","neighborhood","appliances","room_rent","land_deed","home_defense","safe_box","estate_bonds","garage_view","wardrobe","power_grid","estate_audit"],AI=["ask","chat","summarize","analyze","rewrite","code_assistant","ai_persona","brain_dump","generate","imagine","remix","upscale","img_to_text","avatar_gen","deep_dream","translate","dialect_shift","ocr_translate","audio_trans","dictionary","censor_scan","lang_pack","ai_mode","ai_config","ai_status","ai_blacklist","ai_bounty","ai_quota","ai_logs","ai_shutdown","riddle_bot","roast_ai","compliment_ai","fortune_ai","oracle","news_anchor","prompt_shop","download","downloadfile","downloadimage","downloadaudio","downloadvideo","downloadtext","downloadcode","downloadresult"];

const out=(t,x=25)=>({text:t,xp:x,rewards:["xp_token","progress_badge","bonus_ticket"],gameplay:false}),list=(t,a)=>async c=>out(`${t}\n\n${a.map((x,i)=>`${i+1}. ${x}`).join("\n")}`,0);

const commands=[
{name:"level_xp",aliases:["xp","level"],category:"Progression",run:async c=>out(`⭐ LEVEL ${c.user.level||1}\n✨ XP ${c.user.xp||0}`,0)},
{name:"rank_rewards",aliases:["rankreward"],category:"Progression",run:async c=>out("🏆 RANK REWARDS\nRewards unlock as your rank increases.",0)},
{name:"prestige",aliases:["prest"],category:"Progression",run:async c=>out(`👑 PRESTIGE ${c.user.prestige||0}`,0)},
{name:"rebirth",aliases:["reborn"],category:"Progression",run:async c=>out("♻️ REBIRTH SYSTEM\nReset progression for permanent bonuses.",50)},
{name:"passport",aliases:["profile_pass"],category:"Progression",run:async c=>out(`🛂 PASSPORT\n👤 ${c.user.name||"Player"}\n⭐ Level ${c.user.level||1}`,0)},
{name:"achieve_total",aliases:["achievement_total"],category:"Progression",run:async c=>out("🏆 ACHIEVEMENT TOTAL\nYour completed achievements are tracked here.",0)},
{name:"skills_tree",aliases:["skilltree"],category:"Progression",run:list("🌳 SKILL TREE",["Economy","Combat","Pets","Crime","Social","AI","Crafting","Exploration"])},
{name:"title_shop",aliases:["titles"],category:"Progression",run:list("🏅 TITLE SHOP",["Rookie","Veteran","Elite","Legend","Mythic","Divine"])},
{name:"legacy_score",aliases:["legacy"],category:"Progression",run:async c=>out(`📜 LEGACY SCORE\n${c.user.legacy||0}`,0)},
{name:"badge_case",aliases:["badges"],category:"Progression",run:async c=>out("🏅 BADGE CASE\nYour earned badges appear here.",0)},
{name:"perk_activate",aliases:["perk"],category:"Progression",run:async c=>out("✨ PERK ACTIVATED\nYour available progression perk has been applied.",25)},
{name:"stat_allocate",aliases:["stats"],category:"Progression",run:async c=>out("📊 STAT ALLOCATION\nUse your progression points to improve attributes.",0)},
{name:"mastery_loop",aliases:["mastery"],category:"Progression",run:async c=>out("🔁 MASTERY LOOP\nMastery levels increase through repeated legitimate activity.",25)},
{name:"career_level",aliases:["career"],category:"Progression",run:async c=>out(`💼 CAREER LEVEL ${c.user.jobLevel||1}`,0)},
{name:"season_pass",aliases:["season"],category:"Progression",run:async c=>out("🎟️ SEASON PASS\nComplete activities to unlock seasonal rewards.",0)},
{name:"booster_pack",aliases:["booster"],category:"Progression",run:async c=>out("🚀 BOOSTER PACK\nXP and activity boosters are available.",25)},
{name:"codex",aliases:["encyclopedia"],category:"Progression",run:async c=>out("📚 CODEX\nWorld discoveries, items, pets and achievements.",0)},
{name:"tasks_daily",aliases:["daily_tasks"],category:"Progression",run:async c=>out("📋 DAILY TASKS\nComplete today's objectives for rewards.",0)},
{name:"tasks_weekly",aliases:["weekly_tasks"],category:"Progression",run:async c=>out("📋 WEEKLY TASKS\nComplete weekly objectives for larger rewards.",0)},
{name:"quests_main",aliases:["mainquests"],category:"Progression",run:async c=>out("📜 MAIN QUESTS\nYour primary storyline quests.",0)},
{name:"quests_side",aliases:["sidequests"],category:"Progression",run:async c=>out("📜 SIDE QUESTS\nOptional adventures and rewards.",0)},
{name:"quest_inventory",aliases:["questitems"],category:"Progression",run:async c=>out("🎒 QUEST INVENTORY\nQuest items are tracked here.",0)},
{name:"faction_quest",aliases:["factionquest"],category:"Progression",run:async c=>out("🏰 FACTION QUEST\nComplete faction objectives to gain reputation.",0)},
{name:"bounty_board",aliases:["bounties"],category:"Progression",run:async c=>out("🎯 BOUNTY BOARD\nAvailable world bounties are listed here.",0)},
{name:"milestones",aliases:["milestone"],category:"Progression",run:async c=>out("🏆 MILESTONES\nMajor achievements unlock permanent rewards.",0)},
{name:"achieve_hunt",aliases:["achievement_hunt"],category:"Progression",run:async c=>out("🔎 ACHIEVEMENT HUNT\nDiscover hidden achievements.",25)},
{name:"campaign_stats",aliases:["campaign"],category:"Progression",run:async c=>out("📈 CAMPAIGN STATS\nMission and campaign progress.",0)},
{name:"house_buy",aliases:["buyhouse"],category:"Life",run:async c=>out("🏠 HOUSE MARKET\nAvailable properties can be purchased here.",0)},
{name:"house_sell",aliases:["sellhouse"],category:"Life",run:async c=>out("🏠 PROPERTY SALE\nYour property value is calculated by the housing system.",0)},
{name:"decorate",aliases:["decor"],category:"Life",run:async c=>out("🛋️ DECORATION MODE\nCustomize your property.",25)},
{name:"upgrade_yard",aliases:["yard_upgrade"],category:"Life",run:async c=>out("🌳 YARD UPGRADED\nProperty value and capacity improved.",50)},
{name:"invite_guest",aliases:["guest"],category:"Life",run:async c=>out("🏠 GUEST SYSTEM\nInvite community members to your home.",0)},
{name:"mansion_vault",aliases:["home_vault"],category:"Life",run:async c=>out("🔐 MANSION VAULT\nSecure property storage.",0)},
{name:"neighborhood",aliases:["neighbors"],category:"Life",run:async c=>out("🏘️ NEIGHBORHOOD\nView nearby properties and residents.",0)},
{name:"room_rent",aliases:["rentroom"],category:"Life",run:async c=>out("🛏️ ROOM RENTAL\nManage rooms and rental income.",25)},
{name:"home_defense",aliases:["homedefense"],category:"Life",run:async c=>out("🛡️ HOME DEFENSE\nSecurity system activated.",25)},
{name:"safe_box",aliases:["safebox"],category:"Life",run:async c=>out("🔐 SAFE BOX\nPrivate item storage.",0)},
{name:"estate_audit",aliases:["property_audit"],category:"Life",run:async c=>out("📋 ESTATE AUDIT\nProperty finances and upgrades checked.",0)},
{name:"ui_divider",aliases:["divider"],category:"UI",run:async c=>out("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",0)},
{name:"menu_style",aliases:["menustyle"],category:"UI",run:async c=>out("🎨 MENU STYLE\nMain menu style is active.",0)},
{name:"emoji_palette",aliases:["emojis"],category:"UI",run:async c=>out("😀 EMOJI PALETTE\nEmoji interface loaded.",0)},
{name:"hud_display",aliases:["hud"],category:"UI",run:async c=>out("📊 HUD DISPLAY\nPlayer status interface loaded.",0)},
{name:"render_clear",aliases:["clear_render"],category:"UI",run:async c=>out("🧹 RENDER CACHE CLEARED.",0)},
{name:"text_compress",aliases:["compress"],category:"UI",run:async c=>out("📦 TEXT COMPRESSION ENABLED.",0)},
{name:"ai",aliases:["ask","chat","ai_chat"],category:"AI",run:async c=>{if(!c.gemini)return out("🤖 Gemini is not configured. Add GEMINI_API_KEY.",0);return out(await c.gemini(c.args.join(" ")||"Hello"),0)}},
{name:"summarize",aliases:["summary"],category:"AI",run:async c=>{if(!c.gemini)return out("🤖 Gemini unavailable.",0);return out(await c.gemini("Summarize this briefly: "+c.args.join(" ")),25)}},
{name:"analyze",aliases:["analysis"],category:"AI",run:async c=>{if(!c.gemini)return out("🤖 Gemini unavailable.",0);return out(await c.gemini("Analyze this: "+c.args.join(" ")),25)}},
{name:"rewrite",aliases:["rephrase"],category:"AI",run:async c=>{if(!c.gemini)return out("🤖 Gemini unavailable.",0);return out(await c.gemini("Rewrite this clearly: "+c.args.join(" ")),25)}},
{name:"translate",aliases:["trans"],category:"AI",run:async c=>{if(!c.gemini)return out("🤖 Gemini unavailable.",0);return out(await c.gemini("Translate this: "+c.args.join(" ")),25)}},
{name:"code_assistant",aliases:["codeai"],category:"AI",run:async c=>{if(!c.gemini)return out("🤖 Gemini unavailable.",0);return out(await c.gemini("Help with this code request: "+c.args.join(" ")),25)}},
{name:"ai_persona",aliases:["persona"],category:"AI",run:async c=>out("🤖 AI PERSONA\nChoose the personality used by the AI system.",0)},
{name:"generate",aliases:["create"],category:"AI",run:async c=>{if(!c.gemini)return out("🤖 Gemini unavailable.",0);return out(await c.gemini("Generate: "+c.args.join(" ")),25)}},
{name:"riddle_bot",aliases:["riddle"],category:"AI",run:async c=>{if(!c.gemini)return out("🧩 AI unavailable.",0);return out(await c.gemini("Give me one difficult riddle."),25)}},
{name:"roast_ai",aliases:["airoast"],category:"AI",run:async c=>{if(!c.gemini)return out("🔥 AI unavailable.",0);return out(await c.gemini("Give a playful harmless roast."),25)}},
{name:"compliment_ai",aliases:["aicompliment"],category:"AI",run:async c=>{if(!c.gemini)return out("💖 AI unavailable.",0);return out(await c.gemini("Give a friendly compliment."),25)}},
{name:"fortune_ai",aliases:["aifortune"],category:"AI",run:async c=>{if(!c.gemini)return out("🔮 AI unavailable.",0);return out(await c.gemini("Give a clearly fictional fun fortune."),25)}},
{name:"oracle",aliases:["ai_oracle"],category:"AI",run:async c=>{if(!c.gemini)return out("🔮 AI unavailable.",0);return out(await c.gemini("Give a fictional oracle-style message."),25)}},
{name:"prompt_shop",aliases:["prompts"],category:"AI",run:list("🧠 PROMPT SHOP",["Creative","Coding","Business","Study","Roleplay","Image"])},
{name:"ai_status",aliases:["aistatus"],category:"AI",run:async c=>out(`🤖 AI STATUS\n${c.gemini?"🟢 Gemini Ready":"🔴 Gemini Not Configured"}`,0)}
];

for(const x of P.concat(AI))if(!commands.some(c=>c.name===x||c.aliases?.includes(x)))commands.push({name:x,aliases:[],category:P.includes(x)?"Progression":"AI",purpose:`${x} system`,run:async c=>out(`✅ ${x.replaceAll("_"," ").toUpperCase()} executed.`,25)});
module.exports=commands;
