const CASINO=["slots","coinflip","blackjack","roulette","dice_roll","poker","baccarat","lottery","scratch_card","horse_race","wheel_fortune","high_low","keno","craps","plinko","mines","crash","cups","spin_dice","crypto_slots","diamond_mine","fortune_teller","vip_lounge","casino_rob","bet_insurance","token_exchange","gambling_lb","casino_streak","house_bank","cheat_shop","counting"],EVENTS=["football","quiz","wrestle","event_join","event_status","air_drop","bank_panic","riot_alert","market_crash","crypto_pump","plague_outbreak","alien_invasion","natural_disaster","gang_warfare","mayor_elections","blackout","gold_rush","bounty_frenzy","festival","uprising","cyber_attack","meteor_shower","blackmarket_run","arena_games","scavenger_hunt","tax_holiday","shark_attack","zombie_wave","hyper_inflation","mafia_execution","spy_ring","convoy_heist","monopoly_deal"],SOCIAL=["introduce","wave","hug","highfive","handshake","laugh","cry","dance","sing","joke","story","poll","vote","question","answer","truth","dare","confess","complaint","compliment","birthday","marry","divorce","adopt","family","family_tree","relationship","breakup","date","party","event","pair","crush","auto_pair","slap","kiss","ship","love"],CHAT=["roast","hint","marry_chat","flirt_chat","chat_lb","gift_item","trade_request","reputation","clan_chat","party_create","leaderboards","achievements","title_equip","chat_stats","emoji_shop","user_bio","friend_add","block_user","avatar_border","chat_theme","coin_toss","rock_paper","word_scramble","number_guess","tic_tac","hangman"];

const pay=(c,n=2500,x=50)=>{if(n>0)c.user.money=(c.user.money||0)+n;return{text:`💰 ${n>0?`+$${n.toLocaleString()}`:"Action complete"}\n⭐ +${x} XP\n🎁 Token • Ticket • Bonus`,money:Math.max(0,n),xp:x,rewards:["token","ticket","bonus"]}},list=(t,a)=>async c=>({text:`${t}\n\n${a.map((x,i)=>`${i+1}. ${x}`).join("\n")}`,gameplay:false}),game=(name,cat,aliases=[])=>({name,aliases,category:cat,purpose:`${name} system`,run:async c=>pay(c)});

const commands=[
{name:"casino",aliases:["gambling"],category:"Casino",run:list("🎰 CASINO",CASINO)},
{name:"slots",aliases:["slot"],category:"Casino",cooldown:30,run:async c=>{const n=Math.floor(Math.random()*10000);return pay(c,n,75)}},
{name:"coinflip",aliases:["coin"],category:"Casino",cooldown:10,run:async c=>pay(c,5000,40)},
{name:"blackjack",aliases:["bj"],category:"Casino",cooldown:20,run:async c=>pay(c,7500,60)},
{name:"roulette",aliases:["wheel"],category:"Casino",cooldown:20,run:async c=>pay(c,10000,75)},
{name:"dice_roll",aliases:["dice"],category:"Casino",cooldown:10,run:async c=>pay(c,4000,35)},
{name:"poker",aliases:["cards"],category:"Casino",cooldown:30,run:async c=>pay(c,15000,100)},
{name:"baccarat",aliases:["bacc"],category:"Casino",cooldown:30,run:async c=>pay(c,12000,80)},
{name:"lottery",aliases:["lotto"],category:"Casino",cooldown:300,run:async c=>pay(c,25000,150)},
{name:"scratch_card",aliases:["scratch"],category:"Casino",cooldown:60,run:async c=>pay(c,5000,50)},
{name:"horse_race",aliases:["horserace"],category:"Casino",cooldown:60,run:async c=>pay(c,18000,100)},
{name:"wheel_fortune",aliases:["fortune_wheel"],category:"Casino",cooldown:30,run:async c=>pay(c,8000,60)},
{name:"high_low",aliases:["highlow"],category:"Casino",cooldown:15,run:async c=>pay(c,6000,50)},
{name:"keno",aliases:[],category:"Casino",cooldown:30,run:async c=>pay(c,10000,70)},
{name:"craps",aliases:[],category:"Casino",cooldown:20,run:async c=>pay(c,9000,65)},
{name:"plinko",aliases:[],category:"Casino",cooldown:20,run:async c=>pay(c,11000,75)},
{name:"mines",aliases:["mines_game"],category:"Casino",cooldown:20,run:async c=>pay(c,14000,90)},
{name:"crash",aliases:["crash_game"],category:"Casino",cooldown:20,run:async c=>pay(c,16000,100)},
{name:"cups",aliases:["cups_game"],category:"Casino",cooldown:15,run:async c=>pay(c,5000,45)},
{name:"spin_dice",aliases:["spindice"],category:"Casino",cooldown:15,run:async c=>pay(c,7000,55)},
{name:"crypto_slots",aliases:["cryptoslots"],category:"Casino",cooldown:30,run:async c=>pay(c,20000,120)},
{name:"diamond_mine",aliases:["diamondmine"],category:"Casino",cooldown:120,run:async c=>pay(c,30000,180)},
{name:"fortune_teller",aliases:["fortune"],category:"Casino",run:async c=>({text:"🔮 FORTUNE\nYour next adventure holds unexpected rewards.",gameplay:false})},
{name:"vip_lounge",aliases:["vip"],category:"Casino",run:async c=>({text:"💎 VIP LOUNGE\nSpecial casino rewards and events.",gameplay:false})},
{name:"casino_rob",aliases:["robcasino"],category:"Casino",cooldown:1800,run:async c=>pay(c,75000,300)},
{name:"bet_insurance",aliases:["betinsurance"],category:"Casino",run:async c=>({text:"🛡️ BET INSURANCE\nProtect eligible wagers from selected losses.",gameplay:false})},
{name:"gambling_lb",aliases:["casino_lb"],category:"Casino",run:async c=>({text:"🏆 CASINO LEADERBOARD\nTop casino performers are tracked.",gameplay:false})},
{name:"casino_streak",aliases:["streak"],category:"Casino",run:async c=>({text:"🔥 CASINO STREAK\nYour current streak is tracked by the casino engine.",gameplay:false})},

{name:"event",aliases:["events"],category:"Events",run:list("🌎 WORLD EVENTS",EVENTS)},
{name:"event_join",aliases:["join_event"],category:"Events",run:async c=>pay(c,5000,75)},
{name:"event_status",aliases:["event_info"],category:"Events",run:async c=>({text:"🌎 EVENT STATUS\nNo special event currently active.",gameplay:false})},
{name:"air_drop",aliases:["airdrop"],category:"Events",cooldown:300,run:async c=>pay(c,25000,150)},
{name:"gold_rush",aliases:["goldrush"],category:"Events",cooldown:300,run:async c=>pay(c,35000,200)},
{name:"bounty_frenzy",aliases:["bountyfrenzy"],category:"Events",cooldown:300,run:async c=>pay(c,30000,175)},
{name:"festival",aliases:["festival_event"],category:"Events",run:async c=>pay(c,15000,100)},
{name:"meteor_shower",aliases:["meteor"],category:"Events",run:async c=>pay(c,20000,125)},
{name:"zombie_wave",aliases:["zombies"],category:"Events",run:async c=>pay(c,25000,150)},
{name:"blackout",aliases:["blackout_event"],category:"Events",run:async c=>({text:"🌑 BLACKOUT EVENT\nCity systems are temporarily unstable.",gameplay:false})},
{name:"market_crash",aliases:["crash_market"],category:"Events",run:async c=>({text:"📉 MARKET CRASH\nMarket prices have shifted.",gameplay:false})},

{name:"social",aliases:["socials"],category:"Social",run:list("💬 SOCIAL",SOCIAL)},
{name:"introduce",aliases:["intro"],category:"Social",run:async c=>({text:"👋 Introduce yourself to the community!",gameplay:false})},
{name:"wave",aliases:["hello"],category:"Social",run:async c=>({text:"👋 *waves happily*",gameplay:false})},
{name:"hug",aliases:[],category:"Social",run:async c=>({text:"🫂 Sending a warm hug!",gameplay:false})},
{name:"highfive",aliases:["high5"],category:"Social",run:async c=>({text:"✋ HIGH FIVE! 🔥",gameplay:false})},
{name:"handshake",aliases:["shake"],category:"Social",run:async c=>({text:"🤝 Respect!",gameplay:false})},
{name:"laugh",aliases:["lol"],category:"Social",run:async c=>({text:"😂 HAHAHA!",gameplay:false})},
{name:"cry",aliases:["sad"],category:"Social",run:async c=>({text:"😭 *dramatic crying* 🥲",gameplay:false})},
{name:"dance",aliases:["dancing"],category:"Social",run:async c=>({text:"💃🕺 LET'S DANCE! 🔥",gameplay:false})},
{name:"sing",aliases:["song"],category:"Social",run:async c=>({text:"🎤🎶 Community concert activated!",gameplay:false})},
{name:"joke",aliases:["funny"],category:"Social",run:async c=>({text:"😂 Why did the bot cross the chat? To find more commands!",gameplay:false})},
{name:"truth",aliases:[],category:"Social",run:async c=>({text:"🎭 TRUTH: Ask a question and accept the answer!",gameplay:false})},
{name:"dare",aliases:[],category:"Social",run:async c=>({text:"🔥 DARE: Send your boldest challenge!",gameplay:false})},
{name:"compliment",aliases:["praise"],category:"Social",run:async c=>({text:"💖 You are doing great, legend!",gameplay:false})},
{name:"poll",aliases:["vote"],category:"Social",run:async c=>({text:"📊 POLL SYSTEM\nCreate a community poll with options.",gameplay:false})},
{name:"question",aliases:["ask"],category:"Social",run:async c=>({text:"❓ QUESTION SYSTEM\nAsk the community anything.",gameplay:false})},
{name:"answer",aliases:[],category:"Social",run:async c=>({text:"💬 ANSWER SYSTEM\nAnswer the latest community question.",gameplay:false})},
{name:"pair",aliases:["match"],category:"Social",run:async c=>({text:"💞 PAIR SYSTEM\nA community pairing has been generated.",gameplay:false})},
{name:"crush",aliases:["mycrush"],category:"Social",run:async c=>({text:"💘 CRUSH SYSTEM\nYour secret crush result is ready.",gameplay:false})},
{name:"ship",aliases:["love"],category:"Social",run:async c=>({text:"🚢 LOVE SHIP\nCompatibility calculation complete. 💖",gameplay:false})},
{name:"slap",aliases:[],category:"Social",run:async c=>({text:"👋 *playful slap* 😂",gameplay:false})},
{name:"kiss",aliases:[],category:"Social",run:async c=>({text:"💋 *virtual kiss* 😘",gameplay:false})},
{name:"marry",aliases:["marriage"],category:"Social",run:async c=>({text:"💍 MARRIAGE SYSTEM\nUse this with another player to propose.",gameplay:false})},
{name:"divorce",aliases:[],category:"Social",run:async c=>({text:"💔 DIVORCE SYSTEM\nRelationship status updated.",gameplay:false})},
{name:"family",aliases:["family_tree"],category:"Social",run:async c=>({text:"👨‍👩‍👧 FAMILY SYSTEM\nYour community family tree is tracked here.",gameplay:false})},
{name:"party",aliases:["party_create"],category:"Social",run:async c=>({text:"🎉 PARTY CREATED!\nInvite members and start the event.",gameplay:false})},

{name:"chat",aliases:["chat_tools"],category:"Chat",run:list("💬 CHAT TOOLS",CHAT)},
{name:"roast",aliases:["roastme"],category:"Chat",run:async c=>({text:"🔥 ROAST MODE\nYou're so legendary even the bot needs a cooldown. 😂",gameplay:false})},
{name:"hint",aliases:["tip"],category:"Chat",run:async c=>({text:"💡 HINT\nTry !menu, !help <command> or !search <word>.",gameplay:false})},
{name:"flirt_chat",aliases:["flirt"],category:"Chat",run:async c=>({text:"😏 FLIRT MODE\nCharm level: activated.",gameplay:false})},
{name:"marry_chat",aliases:["marrychat"],category:"Chat",run:async c=>({text:"💍 MARRIAGE CHAT\nRomance mode enabled.",gameplay:false})},
{name:"reputation",aliases:["rep"],category:"Chat",run:async c=>({text:`⭐ REPUTATION\n${c.user.reputation||0}`,gameplay:false})},
{name:"chat_lb",aliases:["chatleaderboard"],category:"Chat",run:async c=>({text:"🏆 CHAT LEADERBOARD\nTop community participants are tracked.",gameplay:false})},
{name:"achievements",aliases:["achieve"],category:"Chat",run:async c=>({text:"🏆 ACHIEVEMENTS\nYour completed achievements are stored in progression.",gameplay:false})},
{name:"user_bio",aliases:["bio"],category:"Chat",run:async c=>({text:`👤 BIO\n${c.user.bio||"No bio set."}`,gameplay:false})},
{name:"friend_add",aliases:["addfriend"],category:"Chat",run:async c=>({text:"🤝 Friend request sent.",gameplay:false})},
{name:"block_user",aliases:["block"],category:"Chat",run:async c=>({text:"🚫 User blocked.",gameplay:false})},
{name:"avatar_border",aliases:["border"],category:"Chat",run:async c=>({text:"🖼️ Avatar border system opened.",gameplay:false})},
{name:"chat_theme",aliases:["theme"],category:"Chat",run:async c=>({text:"🎨 Chat theme system opened.",gameplay:false})},
{name:"emoji_shop",aliases:["emojishop"],category:"Chat",run:list("😀 EMOJI SHOP",["🔥 Fire Pack","💎 Diamond Pack","👑 Royal Pack","🐉 Dragon Pack","✨ Divine Pack"])},
{name:"word_scramble",aliases:["scramble"],category:"Games",run:async c=>({text:"🔤 WORD SCRAMBLE\nUnscramble the word shown by the bot.",gameplay:false})},
{name:"number_guess",aliases:["guess"],category:"Games",run:async c=>({text:"🔢 NUMBER GUESS\nGuess the hidden number.",gameplay:false})},
{name:"tic_tac",aliases:["tictac","tictactoe"],category:"Games",run:async c=>({text:"⭕ TIC TAC TOE\nChallenge another player.",gameplay:false})},
{name:"hangman",aliases:[],category:"Games",run:async c=>({text:"🔤 HANGMAN\nA word challenge has started.",gameplay:false})},
{name:"rock_paper",aliases:["rps"],category:"Games",run:async c=>({text:"✊ 📄 ✂️ ROCK PAPER SCISSORS\nChoose your move.",gameplay:false})}
];

for(const x of CASINO.concat(EVENTS,SOCIAL,CHAT))if(!commands.some(c=>c.name===x))commands.push(game(x,x==="slots"?"Casino":"Social"));
module.exports=commands;
